fsl_pci: fix build when pci is disabled
JIRAID: LIN5-18572

1/1 [
Author: Yong Zhang
Email: yong.zhang@windriver.com
Subject: fsl_pci: fix build when pci is disabled
Date: Mon, 28 Apr 2014 14:25:55 +0800

When pci is disabled, kernel can't build:
arch/powerpc/platforms/85xx/corenet_ds.c: In function 'corenet_ds_setup_arch':
arch/powerpc/platforms/85xx/corenet_ds.c:59:2: error: implicit declaration of
function 'fsl_pci_assign_primary' [-Werror=implicit-function-declaration]

The reason is that there is no definition of fsl_pci_assign_primary()
when CONFIG_FSL_PCI=n. But looking at the code, both CONFIG_FSL_PCI
and CONFIG_PCI take the same effect with regarding to define
fsl_pci_assign_primary(). So remove CONFIG_FSL_PCI to make the build
successfully.

Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>