Revert "wrhv: dont include mpic on hyp builds."
Unwind the mpic removal.  Busted code is still calling into it
even though it should not be.

In function `smp_85xx_setup_cpu':
linux/arch/powerpc/platforms/85xx/smp.c:137:
undefined reference to `mpic_setup_this_cpu'

This reverts commit 725a7c758aba61b335464ced3bd1ef2796f19a64.