add PREEMPT_RT_FULL support for arm64 kernel on WRLinux 7.0
Issue: LIN7-6357

1/8 [
Author: Anders Roxell
Email: anders.roxell@linaro.org
Subject: arch/arm64: Add lazy preempt support
Date: Thu, 1 Oct 2015 17:01:21 -0700

arm64 is missing support for PREEMPT_RT. The main feature which is
lacking is support for lazy preemption. The arch-specific entry code,
thread information structure definitions, and associated data tables
have to be extended to provide this support. Then the Kconfig file has
to be extended to indicate the support is available, and also to
indicate that support for full RT preemption is now available.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
[Adjust context due to arm64 uprobe patches merge]
Signed-off-by: Yang Shi <yang.shi@windriver.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/8 [
Author: Anders Roxell
Email: anders.roxell@linaro.org
Subject: arm64: Allow forced irq threading
Date: Mon, 27 Apr 2015 22:53:09 +0200

Now its safe to allow forced interrupt threading for arm64,
all timer interrupts and the perf interrupt are marked NO_THREAD, as is
the case with arch/arm: da0ec6f ARM: 7814/2: Allow forced irq threading

[ upstream commit: e8557d1f0c4d ]

Suggested-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

3/8 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: irq_work: fix multiple definition with arch_irq_work_raise
Date: Fri, 3 Jun 2016 08:52:06 +0000

Remove the redundant definition arch_irq_work_raise to fix the building error
multiple definition with arch_irq_work_raise if rt full is enabled.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

4/8 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: arm64: Fix typos in KGDB macros
Date: Thu, 25 Sep 2014 13:47:47 +0100

Some of the KGDB macros used for generating the BRK instructions had the
wrong spelling for DBG and KGDB abbreviations.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

5/8 [
Author: Pratyush Anand
Email: panand@redhat.com
Subject: arm64: fix kgdb_step_brk_fn to ignore other's exception
Date: Tue, 13 Jan 2015 14:20:55 +0530

Taken from:
git://github.com/pratyushanand/linux.git:uprobe/upstream_arm64_devel

ARM64 step exception does not have any syndrome information. So, it is
responsibility of exception handler to take care that they handle it
only if exception was raised for them.
After kprobe support, both kprobe and kgdb uses register_step_hook
mechanism to register its step handler. So, if call_step_hook calls kgdb
handler first, it was always returning 0 and in that case if an
exception was raised for kprobe, it would never be handled.

Signed-off-by: Pratyush Anand <panand@redhat.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

6/8 [
Author: Yang Shi
Email: yang.shi@linaro.org
Subject: arm64: replace read_lock to rcu lock in call_break_hook
Date: Mon, 5 Oct 2015 14:32:51 -0700

BUG: sleeping function called from invalid context at kernel/locking/rtmutex.c:917
in_atomic(): 0, irqs_disabled(): 128, pid: 342, name: perf
1 lock held by perf/342:
 #0:  (break_hook_lock){+.+...}, at: [<ffffffc0000851ac>] call_break_hook+0x34/0xd0
irq event stamp: 62224
hardirqs last  enabled at (62223): [<ffffffc00010b7bc>] __call_rcu.constprop.59+0x104/0x270
hardirqs last disabled at (62224): [<ffffffc0000fbe20>] vprintk_emit+0x68/0x640
softirqs last  enabled at (0): [<ffffffc000097928>] copy_process.part.8+0x428/0x17f8
softirqs last disabled at (0): [<          (null)>]           (null)
CPU: 0 PID: 342 Comm: perf Not tainted 4.1.6-rt5 #4
Hardware name: linux,dummy-virt (DT)
Call trace:
[<ffffffc000089968>] dump_backtrace+0x0/0x128
[<ffffffc000089ab0>] show_stack+0x20/0x30
[<ffffffc0007030d0>] dump_stack+0x7c/0xa0
[<ffffffc0000c878c>] ___might_sleep+0x174/0x260
[<ffffffc000708ac8>] __rt_spin_lock+0x28/0x40
[<ffffffc000708db0>] rt_read_lock+0x60/0x80
[<ffffffc0000851a8>] call_break_hook+0x30/0xd0
[<ffffffc000085a70>] brk_handler+0x30/0x98
[<ffffffc000082248>] do_debug_exception+0x50/0xb8
Exception stack(0xffffffc00514fe30 to 0xffffffc00514ff50)
fe20:                                     00000000 00000000 c1594680 0000007f
fe40: ffffffff ffffffff 92063940 0000007f 0550dcd8 ffffffc0 00000000 00000000
fe60: 0514fe70 ffffffc0 000be1f8 ffffffc0 0514feb0 ffffffc0 0008948c ffffffc0
fe80: 00000004 00000000 0514fed0 ffffffc0 ffffffff ffffffff 9282a948 0000007f
fea0: 00000000 00000000 9282b708 0000007f c1592820 0000007f 00083914 ffffffc0
fec0: 00000000 00000000 00000010 00000000 00000064 00000000 00000001 00000000
fee0: 005101e0 00000000 c1594680 0000007f c1594740 0000007f ffffffd8 ffffff80
ff00: 00000000 00000000 00000000 00000000 c1594770 0000007f c1594770 0000007f
ff20: 00665e10 00000000 7f7f7f7f 7f7f7f7f 01010101 01010101 00000000 00000000
ff40: 928e4cc0 0000007f 91ff11e8 0000007f

call_break_hook is called in atomic context (hard irq disabled), so replace
the sleepable lock to rcu lock, replace relevant list operations to rcu
version and call synchronize_rcu() in unregister_break_hook().

And, replace write lock to spinlock in {un}register_break_hook.

Signed-off-by: Yang Shi <yang.shi@linaro.org>
Signed-off-by: Will Deacon <will.deacon@arm.com>
]

7/8 [
Author: He Zhe
Email: zhe.he@windriver.com
Subject: arm64: replace read_lock with rcu lock in call_step_hook
Date: Wed, 9 Dec 2015 02:32:27 -0500

BUG: sleeping function called from invalid context at kernel/locking/rtmutex.c:917
in_atomic(): 1, irqs_disabled(): 128, pid: 383, name: sh
Preemption disabled at:[<ffff800000124c18>] kgdb_cpu_enter+0x158/0x6b8

CPU: 3 PID: 383 Comm: sh Tainted: G        W       4.1.13-rt13-WR8.0.0.0_preempt-rt #2
Hardware name: Freescale Layerscape 2085a RDB Board (DT)
Call trace:
[<ffff8000000885e8>] dump_backtrace+0x0/0x128
[<ffff800000088734>] show_stack+0x24/0x30
[<ffff80000079a7c4>] dump_stack+0x80/0xa0
[<ffff8000000bd324>] ___might_sleep+0x18c/0x1a0
[<ffff8000007a20ac>] __rt_spin_lock+0x2c/0x40
[<ffff8000007a2268>] rt_read_lock+0x40/0x58
[<ffff800000085328>] single_step_handler+0x38/0xd8
[<ffff800000082368>] do_debug_exception+0x58/0xb8
Exception stack(0xffff80834a1e7c80 to 0xffff80834a1e7da0)
7c80: ffffff9c ffffffff 92c23ba0 0000ffff 4a1e7e40 ffff8083 001bfcc4 ffff8000
7ca0: f2000400 00000000 00000000 00000000 4a1e7d80 ffff8083 0049501c ffff8000
7cc0: 00005402 00000000 00aaa210 ffff8000 4a1e7ea0 ffff8083 000833f4 ffff8000
7ce0: ffffff9c ffffffff 92c23ba0 0000ffff 4a1e7ea0 ffff8083 001bfcc0 ffff8000
7d00: 4a0fc400 ffff8083 00005402 00000000 4a1e7d40 ffff8083 00490324 ffff8000
7d20: ffffff9c 00000000 92c23ba0 0000ffff 000a0000 00000000 00000000 00000000
7d40: 00000008 00000000 00080000 00000000 92c23b8b 0000ffff 92c23b8e 0000ffff
7d60: 00000038 00000000 00001cb2 00000000 00000005 00000000 92d7b498 0000ffff
7d80: 01010101 01010101 92be9000 0000ffff 00000000 00000000 00000030 00000000
[<ffff8000000833f4>] el1_dbg+0x18/0x6c

This issue is similar with 8a793c107fced7f66fa6dd2fafd4de84252238ae "arm64:
replace read_lock to rcu lock in call_break_hook", but comes to
single_step_handler.

single_step_handler is called when hard irqs are disabled. It calls read_lock
which will be converted to sleepable one when preempt rt is enabled and thus
causes the above call trace.

This patch replaces read lock with rcu read lock and replaces related write lock
with spin lock.

After this change, if a new single step handler is being registered by holding
the spin lock at first, it might not be used by the immediate debug interrupt,
since the searching operation is only protected by rcu, not synced with
registration. But currently the critical section is only accessed by
register_step_hook/unregister_step_hook/call_step_hook, and the registration
only happens in init time(called by kgdb_arch_init), so there will not be race
condition.

Signed-off-by: He Zhe <zhe.he@windriver.com>
]

8/8 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: debug-monitors: fix a typo KGDB_DYN_DBG_BRK_IMM to resolve build error
Date: Wed, 15 Jun 2016 10:08:18 +0800

arch/arm64/kernel/kgdb.c:241:29: error: 'KGDB_DYN_DBG_BRK_IMM' undeclared here
(not in a function)
   .esr_val = DBG_ESR_VAL_BRK(KGDB_DYN_DBG_BRK_IMM),
                              ^

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>