add cpu hotplug support for e500mc/e5500
CQID: WIND00391977

1/5 [
Author: York Sun
Email: yorksun@freescale.com
Subject: powerpc/mpc85xx: Change spin table to cached memory
Date: Sat, 29 Sep 2012 16:44:35 -0700

commit bc15236fbed1e017b465e38a9d2092393778a2f7 upstream

ePAPR v1.1 requires the spin table to be in cached memory. So we need
to change the call argument of ioremap to enable cache and coherence.
We also flush the cache after writing to spin table to keep it compatible
with previous cache-inhibit spin table. Flushing before and after
accessing spin table is recommended by ePAPR.

Signed-off-by: York Sun <yorksun@freescale.com>
Acked-by: Timur Tabi <timur@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
[Kevin: Just minor context mods in order to port to 3.4 kernel.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

2/5 [
Author: Chen-Hui Zhao
Email: chenhui.zhao@freescale.com
Subject: powerpc/85xx: add cpu hotplug support for e500mc/e5500
Date: Tue, 20 Nov 2012 18:15:13 +0000

Add support to disable and re-enable individual cores at runtime.
This supports e500mc/e5500 core based SoCs.

To prevent the register access race, only read/write RCPM registers
in platform_cpu_die() on the boot cpu instead of accessing by individual
cpus. Platform implementations can override the platform_cpu_die().

Signed-off-by: Zhao Chenhui <chenhui.zhao@freescale.com>
Signed-off-by: Li Yang <leoli@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>
[Kevin: Original patch taken from the FSL
QorIQ-SDK-V1.3.1-SOURCE-20121220-yocto.iso. Don't apply the parts
for changing guts_regs name since we already use this name in our
kernel.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

3/5 [
Author: Chen-Hui Zhao
Email: chenhui.zhao@freescale.com
Subject: powerpc/85xx: fix 64-bit support for cpu hotplug
Date: Tue, 20 Nov 2012 18:15:14 +0000

* The paca[cpu].cpu_start is used as a signal to indicate if the cpu
  should start. So it should be cleard in .cpu_die().
* The limit memory routine only needs to be ran once at boot time
  by the boot cpu. Prevent other cpus running it again.
* Rearrange the code segment in smp_85xx_kick_cpu() to share codes
  between PPC64 and PPC32 as far as possible.

Signed-off-by: Zhao Chenhui <chenhui.zhao@freescale.com>
Signed-off-by: Li Yang <leoli@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>
[Kevin: Original patch taken from the FSL
QorIQ-SDK-V1.3.1-SOURCE-20121220-yocto.iso. Minor context mods
in order to port to 3.4 kernel.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

4/5 [
Author: Zhao Chenhui
Email: chenhui.zhao@freescale.com
Subject: powerpc/85xx: fix compile error when CONFIG_HOTPLUG_CPU is disabled
Date: Thu, 29 Nov 2012 18:50:29 +0800

../arch/powerpc/platforms/85xx/smp.c:306:4:
error: implicit declaration of function 'generic_set_cpu_up'
../arch/powerpc/platforms/85xx/smp.c:321:4:
error: implicit declaration of function 'is_core_down'
make[3]: *** [arch/powerpc/platforms/85xx/smp.o] Error 1

Signed-off-by: Zhao Chenhui <chenhui.zhao@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>
[Kevin: Original patch taken from the FSL
QorIQ-SDK-V1.3.1-SOURCE-20121220-yocto.iso. Remove the mods for smp.c
since we still don't support smt yet.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

5/5 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: net/fsl_pq_mdio: add check for null tbipa
Date: Wed, 26 Dec 2012 16:52:05 +0800

We don't need to set the tbi address for fman mdio.
So initialize the tbipa to null, and check for null
before writing the tbi address. This will drop the
hardcoded #ifndef CONFIG_FSL_FMAN and also fix the
null dereferencing oops when CONFIG_FSL_FMAN is not
enabled on DPAA SoCs.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>