fs/nfs: Fix used uninitialized warn in nfs4_slot_seqid_in_use()
1/2 [
Author: Shuah Khan
Email: shuahkh@osg.samsung.com
Subject: fs/nfs: Fix used uninitialized warn in nfs4_slot_seqid_in_use()
Date: Wed, 16 Nov 2016 15:36:39 -0500

commit 0ac84b72c0ed96ace1d8973a06f0120a3b905177 upstream.

Fix the following warn:

fs/nfs/nfs4session.c: In function â~@~Xnfs4_slot_seqid_in_useâ~@~Y:
fs/nfs/nfs4session.c:203:54: warning: â~@~Xcur_seqâ~@~Y may be used uninitialized in this function [-Wmaybe-uninitialized]
  if (nfs4_slot_get_seqid(tbl, slotid, &cur_seq) == 0 &&
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
	      cur_seq == seq_nr && test_bit(slotid, tbl->used_slots))
	            ~~~~~~~~~~~~~~~~~

Signed-off-by: Shuah Khan <shuahkh@osg.samsung.com>
Signed-off-by: Anna Schumaker <Anna.Schumaker@Netapp.com>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

2/2 [
Author: Arnd Bergmann
Email: arnd@arndb.de
Subject: NFSv4.1: work around -Wmaybe-uninitialized warning
Date: Wed, 16 Nov 2016 15:36:40 -0500

commit e84efa32b9d2763fb92e73c8942100d8f55ad4ed upstream.

A bugfix introduced a harmless gcc warning in nfs4_slot_seqid_in_use if
we enable -Wmaybe-uninitialized again:

  fs/nfs/nfs4session.c:203:54: error: 'cur_seq' may be used uninitialized in this function [-Werror=maybe-uninitialized]

gcc is not smart enough to conclude that the IS_ERR/PTR_ERR pair results
in a nonzero return value here.  Using PTR_ERR_OR_ZERO() instead makes
this clear to the compiler.

Fixes: e09c978aae5b ("NFSv4.1: Fix Oopsable condition in server callback races")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
[Fix context conflict]
Signed-off-by: Yang Shi <yang.shi@windriver.com>