ocf/talitos: Need to replace CONFIG_PPC_MERGE by CONFIG_PPC
CQID: WIND00391242

1/5 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: ocf/talitos: Replace CONFIG_PPC_MERGE by CONFIG_PPC
Date: Thu, 29 Nov 2012 10:20:35 +0800

Since commit dbc1c5c2 "powerpc: Remove Kconfig support for PPC_MERGE",
PPC_MERGE Kconfig support has been removed, so we need to update ocf/talitos
code accordingly by changing CONFIG_PPC_MERGE to CONFIG_PPC.

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

2/5 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: ocf/talitos: Update driver code so as to keep consistent with kernel
Date: Mon, 3 Dec 2012 12:14:38 +0800

Since commit 2dc11581 "of/device: Replace struct of_device with
struct platform_device" and commit 4018294b "of: Remove duplicate
fields from of_platform_driver", the latest kernel has replaced
struct of_device with struct platform_device and do some cleanups in
struct of_platform_driver, moreover, of_platform_driver is getting
removed, and a single platform_driver can now support both devicetree
and non-devicetree use cases. However, the ocf/talitos driver didn't
update to meet the latest kernel's needs and compiling errors happen
like below:
  linux/crypto/ocf/talitos/talitos.c:158:64: warning: 'struct of_device' declared \
  inside parameter list
  linux/crypto/ocf/talitos/talitos.c:158:64: warning: its scope is only this \
  definition or declaration, which is probably not what you want
  linux/crypto/ocf/talitos/talitos.c:158:12: note: previous declaration of \
  'talitos_probe' was here
  linux/crypto/ocf/talitos/talitos.c: In function 'talitos_probe':
  linux/crypto/ocf/talitos/talitos.c:1093:32: error: dereferencing pointer to \
  incomplete type
  linux/crypto/ocf/talitos/talitos.c:1269:12: error: conflicting types \
  for 'talitos_remove'
  linux/crypto/ocf/talitos/talitos.c:159:12: note: previous declaration \
  of 'talitos_remove' was here
  linux/crypto/ocf/talitos/talitos.c: In function 'talitos_remove':
  linux/crypto/ocf/talitos/talitos.c:1275:51: error: dereferencing pointer \
  to incomplete type
  linux/crypto/ocf/talitos/talitos.c:1314:2: error: unknown field 'name' \
  specified in initializer
  linux/crypto/ocf/talitos/talitos.c:1315:2: error: unknown field 'match_table' \
  specified in initializer
  linux/crypto/ocf/talitos/talitos.c:1322:2: error: implicit declaration of function \
  'of_register_platform_driver'
  linux/crypto/ocf/talitos/talitos.c: In function 'talitos_exit':
  linux/crypto/ocf/talitos/talitos.c:1327:2: error: implicit declaration of function \
  'of_unregister_platform_driver'

Update the ocf/talitos driver code to fix the compiling errors and also
update the of_match_table because the compatible name in dts is not generally
called 'talitos'.

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

3/5 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: ocf/talitos: redundant codes cleanup
Date: Mon, 3 Dec 2012 12:36:30 +0800

After commit "ocf/talitos: Update driver code so as to keep consistent
with kernel", some codes are redundant and need to be cleanup.

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

4/5 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: ocf/talitos: Replace NULL with true device pointer in dma_map_single
Date: Mon, 3 Dec 2012 15:20:30 +0800

After commit 46bab4e4 "powerpc: Use asm-generic/dma-mapping-common.h",
powerpc no longer allows passing NULL to the dev parameter of the DMA API.
The NULL parameter in dma_map_single() of talitos source code could
lead to kernel Oops when run benchmark test:
  Unable to handle kernel paging request for data at address 0x0000000c
  Faulting instruction address: 0xf1072900
  Oops: Kernel access of bad area, sig: 11 [#2]
  NIP [f1072900] talitos_process+0x498/0xdfc [talitos]
  LR [f107261c] talitos_process+0x1b4/0xdfc [talitos]
  Call Trace:
  [eeed7c20] [f107261c] talitos_process+0x1b4/0xdfc [talitos] (unreliable)
  [eeed7c90] [f105b138] crypto_invoke.isra.1+0x78/0x198 [ocf]
  [eeed7cc0] [f105bba8] crypto_dispatch+0x160/0x308 [ocf]
  [eeed7cf0] [f106ccc0] cryptodev_ioctl.isra.3+0x182c/0x2048 [cryptodev]
  [eeed7e80] [f106d4f8] cryptodev_unlocked_ioctl+0x1c/0x40 [cryptodev]
  [eeed7e90] [c016246c] do_vfs_ioctl+0xac/0x778
  [eeed7f00] [c0162bd8] sys_ioctl+0xa0/0x134
  [eeed7f40] [c0010690] ret_from_syscall+0x0/0x3c

Fix this problem by replacing the NULL parameter with true device pointer
in dma_map_single().

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

5/5 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: ocf/talitos: Restrict out_fifo length for all hash algorithms
Date: Mon, 3 Dec 2012 15:22:31 +0800

The below benchmark program makes SEC triggers an Address
Error interrupt or kernel Oops:
/>./cryptotest -va md5 1 1024
crid = 3000000
alg = md5
session = 0x0
device = talitos0
count = 1, size = 1024
cleartext:
0000: 68 38 30 61 73 36 65 73 33 39 75 62 21 6e 35 34
0010: 6a 31 6f 37 36 74 65 35 61 33 74 38 73 34 62 35
0020: 6f 6e 74 32 68 6f 33 31 34 39 75 34 32 68 35 30
0030: 39 69 34 61 74 6e 75 68 36 33 62 39 38 61 61 6f
cryptotest: line 465:ioctl(CIOCCRYPT): Input/output error
Unable to handle kernel paging request for data at address 0x00000004
Faulting instruction address: 0xc00d18fc
Oops: Kernel access of bad area, sig: 11 [#1]
PREEMPT 8 68 38 65 33 73SMP NR_CPUS=2  LTT NESTING LEVEL : 0
MPC8572 DS
NIP [c00d18fc] vma_prio_tree_remove+0x118/0x130
LR [c00de52c] __remove_shared_vm_struct+0x60/0x90
Call Trace:
[ef115de0] [c141c0b8] 0xc141c0b8 (unreliable)
[ef115e00] [c00de52c] __remove_shared_vm_struct+0x60/0x90
[ef115e10] [c00de59c] unlink_file_vma+0x40/0x5c
[ef115e30] [c00dbde8] free_pgtables+0x60/0xbc
[ef115e50] [c00de238] exit_mmap+0x124/0x1b4
[ef115e80] [c0044c1c] mmput+0x58/0x120
[ef115e90] [c0049948] exit_mm+0x148/0x168
[ef115ec0] [c004baac] do_exit+0x5d8/0x6b0
[ef115f10] [c004bbcc] do_group_exit+0x48/0xa8
[ef115f30] [c004bc40] sys_exit_group+0x14/0x28
[ef115f40] [c0010ef0] ret_from_syscall+0x0/0x4

This problem also exists in other hash algorithms, restricting out_fifo length
for all hash algorithm to avoid MEDU generating error interrupt although it may
increase the chance of collisions.

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>