ls1021: include the missing phy/phy_fixed.h header file
Rally: US68643

1/1 [
Author: Auto Configured
Email: auto.configured
Subject: ls1021: include the missing phy/phy_fixed.h header file
Date: Thu, 4 Feb 2016 04:16:37 +0000

Fix the following build errors:
arch/arm/mach-imx/mach-ls1021a.c: In function 'of_add_fixed_phys':
arch/arm/mach-imx/mach-ls1021a.c:64:9: error: variable 'status' has initializer but incomplete type
  struct fixed_phy_status status = {};
         ^
arch/arm/mach-imx/mach-ls1021a.c:77:3: error: implicit declaration of function 'fixed_phy_add' [-Werror=implicit-function-declaration]
  ret = fixed_phy_add(PHY_POLL, be32_to_cpu(fixed_link[0]), &status);

Signed-off-by: czou <cao.zou@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>