net: ethernet: xilinx: axienet: fix 'lp' undeclared error
Issue: LIN9-7171

1/1 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: net: ethernet: xilinx: axienet: fix 'lp' undeclared error
Date: Thu, 19 Jul 2018 08:18:56 +0000

Fixes the following build error when CONFIG_XILINX_AXI_EMAC=y and
CONFIG_XILINX_AXI_EMAC_HWTSTAMP is not set:
/drivers/net/ethernet/xilinx/xilinx_axienet_main.c:1729:24: error: 'lp' undeclared (first use in this function)
| return phy_mii_ioctl(lp->phy_dev, rq, cmd);
| ^~

This issue is specific to the WRL9 xilinx-zynq kernel, introduced by
commit d84994f8d27a [drivers: net: ethernet: axienet: fix compilation error].

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>