grsec: undo git fuzz error
These two upstream commits caused git to be confused, and we didn't
notice the fuzz failure:
33efe2910bf7865a7d1fba4b06c9fa4b6fda6856
14cfd9f986d521f3f97139fa2ae5db67886059d1

git put the hunk into do_get_mempolicy() instead of mbind_range(),
resulting in the following error when CONFIG_PAX_SEGMEXEC=y:

mm/mempolicy.c: In function 'mbind_range':
mm/mempolicy.c:659:25: warning: unused variable 'vma_m' [-Wunused-variable]
mm/mempolicy.c: In function 'do_get_mempolicy':
mm/mempolicy.c:912:3: error: 'vma_m' undeclared (first use in this function)
mm/mempolicy.c:912:3: note: each undeclared identifier is reported only once for each function it appears in
mm/mempolicy.c:914:43: error: 'new_pol' undeclared (first use in this function)

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>