sched.c: fixup sched-add-exit-for-cpuctl for fcn rename
Our cherry pick of upstream b2b5ce022acf5e9f52f

  "sched, cgroup: Fixup broken cgroup movement"

means a function rename, which will cause this patch to trigger:

kernel/sched.c: In function 'cpu_cgroup_exit':
kernel/sched.c:8764: error: 'const struct sched_class' has no member named 'moved_group'
kernel/sched.c:8765: error: 'const struct sched_class' has no member named 'moved_group'
scripts/Makefile.build:365: *** [kernel/sched.o] Error 1

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>