fsl-t2xxx: Fix compile errors when disabling CONFIG_SMP
commit 346350378dadffd66e0d73bb2e903bf1834a7e72 upstream.

Issue: LIN7-3499

1/1 [
Author: Jianchuan Wang
Email: jianchuan.wang@windriver.com
Subject: fsl-t2xxx: Fix compile errors when disabling CONFIG_SMP
Date: Thu, 23 Apr 2015 15:55:49 +0800

There are some compile errors when disabling CONFIG_SMP
- boot_cpuid isn't declared in the ics.c,it hints:

    | arch/powerpc/platforms/wsp/ics.c: In function 'wsp_ics_set_default_server':
    | arch/powerpc/platforms/wsp/ics.c:655:23: error: 'boot_cpuid' undeclared (first use in this function)
    |   np = of_get_cpu_node(boot_cpuid, NULL);
    |                        ^
    | arch/powerpc/platforms/wsp/ics.c:655:23: note: each undeclared identifier is reported only once for each function it appears in
    | arch/powerpc/platforms/wsp/ics.c:658:2: error: implicit declaration of function 'get_hard_smp_processor_id' [-Werror=implicit-function-declaration]
    |   hwid = get_hard_smp_processor_id(boot_cpuid);

- nr_cpu_ids isn't defined in the exceptions-64e.S/head_64.S, it hints:

    | arch/powerpc/kernel/head_64.S:231: undefined reference to `nr_cpu_ids'

Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>