fsl-t2xxx: add edac driver
1/7 [
Author: York Sun
Email: yorksun@freescale.com
Subject: powerpc/mpc85xx: Fix EDAC address capture
Date: Fri, 11 May 2012 05:24:06 +0000

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Extend err_addr to cover 64 bits for DDR errors.

Signed-off-by: York Sun <yorksun@freescale.com>
Change-Id: Idb112c4a106416a9cad9933c415e6f62de5cf07b
Reviewed-on: http://git.am.freescale.net:8181/553
Tested-by: Schmitt Richard-B43082 <B43082@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

2/7 [
Author: York Sun
Email: yorksun@freescale.com
Subject: powerpc/mpc8xxx: Change EDAC for FSL SoC
Date: Fri, 21 Sep 2012 09:40:50 +0000

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Remove mpc83xx and mpc85xx as dependency.

Signed-off-by: York Sun <yorksun@freescale.com>
Change-Id: I92ff2ecf38b00e48a713baf2443495f8a1468beb
Reviewed-on: http://git.am.freescale.net:8181/554
Reviewed-by: Schmitt Richard-B43082 <B43082@freescale.com>
Tested-by: Schmitt Richard-B43082 <B43082@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

3/7 [
Author: Varun Sethi
Email: Varun.Sethi@freescale.com
Subject: powerpc/edac: Call work queue clean up routine only when edac_op_state is set to polling.
Date: Mon, 11 Jun 2012 14:21:19 +0000

For pci errors we set the edac op state to "interrupt" and thus do not setup the work queue. While performing
edac pci device cleanup, work queue cleanup should only be performed if the op state is set to polling.

Signed-off-by: Varun Sethi <Varun.Sethi@freescale.com>
Change-Id: Iee10865f671dc5d177a5a56cfc782673ef7ebd2f
Reviewed-on: http://git.am.freescale.net:8181/555
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

4/7 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: edac/mpc85xx_edac: Fix a call trace when removing this module
Date: Wed, 20 Feb 2013 09:52:38 +0800

When removing mpc85xx_edac module, the following warning is thrown by kernel.
The root cause of the issue is the devm_free_irq() shoulb be invoked to free the irq
before invoking irq_dispose_mapping() to unmap an interrupt.

WARNING: at fs/proc/generic.c:849
Modules linked in: edac_core mpc85xx_edac(-) minix
NIP: c01bfa9c LR: c01bfa9c CTR: c03fb234
REGS: ef3bbc70 TRAP: 0700   Not tainted  (3.4.20-rt29-WR5.0.1.0_preempt-rt)
MSR: 00029000 <CE,EE,ME>  CR: 22008684  XER: 20000000
TASK = ee5fd310[919] 'rmmod' THREAD: ef3ba000 CPU: 1
GPR00: c01bfa9c ef3bbd20 ee5fd310 00000061 00029000 ffffffff c03fdc7c 0001ffff
GPR08: ee5fd310 c083e324 00000001 00728000 22008622 1001a478 00000000 00000000
GPR16: 00000000 00000000 100c07f4 100f0000 101161a8 100f0000 10002114 10010000
GPR24: 00000000 c0897a00 ef3bbd98 ee44e664 ee44e689 ee44e664 ee44e66c ee44e620
NIP [c01bfa9c] remove_proc_entry+0x278/0x29c
LR [c01bfa9c] remove_proc_entry+0x278/0x29c
Call Trace:
[ef3bbd20] [c01bfa9c] remove_proc_entry+0x278/0x29c (unreliable)
[ef3bbd90] [c00caf88] unregister_irq_proc+0xbc/0xd0
[ef3bbdc0] [c00c4810] free_desc+0x40/0x80
[ef3bbde0] [c00c4904] irq_free_descs+0x5c/0xac
[ef3bbe00] [c00c9cec] irq_dispose_mapping+0xf8/0x130
[ef3bbe20] [f1077a68] mpc85xx_l2_err_remove+0x94/0xf4 [mpc85xx_edac]
[ef3bbe40] [c040ef40] platform_drv_remove+0x2c/0x3c
[ef3bbe50] [c040ce88] __device_release_driver+0x74/0xd8
[ef3bbe60] [c040d878] driver_detach+0xc4/0xe8
[ef3bbe80] [c040cc18] bus_remove_driver+0x9c/0xe8
[ef3bbea0] [c040e0b0] driver_unregister+0x68/0x90
[ef3bbeb0] [c040f3f4] platform_driver_unregister+0x20/0x30
[ef3bbec0] [f1078ebc] mpc85xx_mc_exit+0x4c/0x498 [mpc85xx_edac]
[ef3bbed0] [c00a7984] sys_delete_module+0x16c/0x22c
[ef3bbf40] [c0011248] ret_from_syscall+0x0/0x3c
    LR = 0x10000f68
Instruction dump:
901f0040 4bfffedc 80bf0024 3c80c069 3c60c076 388440c0 38840220 38a50069
7f86e378 38e70069 3863a654 484a8d21 <0fe00000> 4bffff74 80010074 8181004c

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

5/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: edac: mpc85xx: don't do the ecc scrubbing for the reserved memory
Date: Fri, 14 Nov 2014 10:46:18 +0800

On the mpc85xx platform, we use lwarx/stwcx pair to do a atomic
scrubbing when detecting a single bit ecc error. This method works
fine for normal memory. But for some reserved memories such as the
dedicated private memories for QMAN or BMAN, the cache coherence is
disabled for performance. If a single bit ecc error occurs in these
memory areas, the atomic scrubbing may conflict with the QMAN/BMAN
dma store access and then crash the data there.

In order to fix this issue, we choose to skip all the ecc scrubbing
for the reserved memories. We implement this by using the
ctl_page_to_phys callback of mem_ctl_info struct. If an ecc error
occurs in a reserved memory, we would return a invalid physical
address. This will cause the edac core to skip the ecc scrubbing.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

6/7 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/pci: export two function symbols for mpc85xx_edac module
Date: Mon, 14 Jan 2013 16:31:07 +0800

When building mpc85xx_edac as module, the following build errors occur

drivers/edac/mpc85xx_edac.c:437:12:
warning: 'mpc85xx_pci_err_remove' defined but not used [-Wunused-function]
   LD [M]  drivers/edac/edac_core.o
   Building modules, stage 2.
   MODPOST 176 modules
 ERROR: "pci_find_hose_for_OF_device" [drivers/edac/mpc85xx_edac.ko] undefined!
 ERROR: "early_find_capability" [drivers/edac/mpc85xx_edac.ko] undefined!
 make[3]: *** [__modpost] Error 1
 make[2]: *** [modules] Error 2
 make[1]: *** [sub-make] Error 2
 make: *** [all] Error 2

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

7/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: memblock: change the annotation to __init_memblock for memblock_is_reserved()
Date: Fri, 14 Nov 2014 10:41:12 +0800

This function may be used by modules, so change the annotation to
__init_memblock and also export the symbol.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>