perf: fix bench numa compilation
1/1 [
Author: Riccardo Magliocchetti
Email: riccardo.magliocchetti@gmail.com
Subject: perf: fix bench numa compilation
Date: Thu, 17 Oct 2013 15:11:25 -0700

Taken from: https://lkml.org/lkml/2013/6/20/80

Fix the following errors on gcc 4.8.1 / x86:

bench/numa.c: In function worker_thread:
bench/numa.c:1113:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if (diff.tv_sec >= g->p.nr_secs) {
                    ^
bench/numa.c:1161:6: error: format %lx expects argument of type long unsigned int, but argument 5 has type u64 [-Werror=format=]
      process_nr, thread_nr, runtime_ns_max / bytes_done, val);
      ^
Signed-off-by: Riccardo Magliocchetti <riccardo.magliocchetti@gmail.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

Conflicts:
	features/perf/perf.scc