A bugfix introduced a harmless gcc warning in nfs4_slot_seqid_in_use
1/1 [
Author: "Kexin(Casey) Chen"
Email: Casey.Chen@windriver.com
Subject: A bugfix introduced a harmless gcc warning in nfs4_slot_seqid_in_use:
Date: Tue, 15 Nov 2016 11:56:29 -0800

fs/nfs/nfs4session.c:203:54: error: 'cur_seq' may be used
uninitialized in this function [-Werror=maybe-uninitialized]

gcc is not smart enough to conclude that the IS_ERR/PTR_ERR pair
results in a nonzero return value here. Using PTR_ERR_OR_ZERO()
instead makes this clear to the compiler.

https://groups.google.com/forum/#!topic/linux.kernel/bVGGqwmAzVo

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Signed-off-by: Kexin(Casey) Chen <Casey.Chen@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>