Applying: gresecurity: fix several compiling error on MIPS
CQID: WIND00379971

1/1 [
Author: "Roy.Li"
Email: rongqing.li@windriver.com
Subject: gresecurity: fix several compiling error on MIPS
Date: Fri, 19 Apr 2013 15:37:38 +0800

1. machine_power_off/halt/restart have been defined as noreturn function,
but they will exit in MIPS arch. now make them  as noreturn.

	arch/mips/kernel/reset.c:44:1: error: 'noreturn' function does
	return [-Werror]

2. fix a typOS, backport from grsecurity-2.9.1-3.2.39-201302252105.patch

	arch/mips/mm/mmap.c:152:29: error: 'vmm' undeclared (first use in
	this function)

3. include <linux/prefetch.h> explicitly, to avoid the compile error, because
prefetch funtion is not defined in <asm/processor.h> which is included by
sched.h indirectly. like on MIPS arch, when CPU_HAS_PREFETCH is disabled.

	grsecurity/gracl.c:215:3: error: implicit declaration of function
	'prefetch' [-Werror=implicit-function-declaration]

Signed-off-by: Roy.Li <rongqing.li@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>