f2fs: fix a build error
Issue: LIN6-14912

1/1 [
Author: Jibin Xu
Email: jibin.xu@windriver.com
Subject: f2fs: fix a build error
Date: Fri, 31 Aug 2018 14:19:58 +0800

When build kernel with f2fs be enabled, it will print
error messages as below:
"error: 'struct bio' has no member named 'bi_sector'".

The reason is 5b7f13ce372e backport a patch, but it is
incomplete, so complete it to fix the build error.

Signed-off-by: Jibin Xu <jibin.xu@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>