syscall: Sort out syscall_restart name clash.
CQID: WIND00365672

1/1 [
Author: "Eric W. Biederman"
Email: ebiederm@aristanetworks.com
Subject: syscall: Sort out syscall_restart name clash.
Date: Wed, 20 May 2009 15:52:40 -0700

commit 288ddad5b095ff65812cf1060c67d23c07568871 upstream.

Stephen Rothwell <sfr@canb.auug.org.au> writes:

> Today's linux-next build of at least some av32 and arm configs failed like this:
>
> arch/avr32/kernel/signal.c:216: error: conflicting types for 'restart_syscall'
> include/linux/sched.h:2184: error: previous definition of 'restart_syscall' was here
>
> Caused by commit 690cc3ffe33ac4a2857583c22d4c6244ae11684d ("syscall:
> Implement a convinience function restart_syscall") from the net tree.

Grrr. Some days it feels like all of the good names are already taken.

Let's just rename the two static users in arm and avr32 to get this
sorted out.

Signed-off-by: Eric W. Biederman <ebiederm@aristanetworks.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>