powerpc/fsl-p2020: common patches
CQID: WIND00375824

1/21 [
Author: Li Yang
Email: leoli@freescale.com
Subject: fsl-p2020: espi dts support for p2020ds
Date: Mon, 4 Jan 2010 19:16:44 +0800

extract from vendor drop QorIQ_SDK_V1_03_20110929_Patch.iso

Add the SPI node and the partitions to DTS file

Signed-off-by: Jerry Huang <Chang-Ming.Huang@freescale.com>
]

2/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: P2020DS: Disable USB device in M1575
Date: Wed, 23 May 2012 15:00:33 +0800

P2020ds pull USB CLK signal down. It is impossible to
access the deveice. we have to invalid it to un-classified device
to prevent access it.

Signed-off-by: Yongli He <yongli.he@windriver.com>
]

3/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: fsl_p2020: Add EEPROM device node for P2020DS
Date: Fri, 25 May 2012 10:00:40 +0800

Two EEPROM are attached to I2C-0 bus.

Signed-off-by: Andrew Liu <shengping.liu@windriver.com>
Signed-off-by: Yongli He <yongli.he@windriver.com>
]

4/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: fsl-p2020:Add DS1339 RTC device node for P2020DS
Date: Mon, 24 Sep 2012 11:11:27 +0800

There are two RTC devices on fsl_p2020DS board, one(rtc_cmos)
is on ISA bus using i8259 interrupt controller, the other(ds1339)
is on I2C-1 bus.

Signed-off-by: Andrew Liu <shengping.liu@windriver.com>
Signed-off-by: Yongli He <yongli.he@windriver.com>
]

5/21 [
Author: Chunhe Lan
Email: Chunhe.Lan@freescale.com
Subject: MMC: Make sure the power is up, when detect the card
Date: Fri, 9 Sep 2011 16:32:44 +0800

The patch is extracted from QorIQ-SDK-V1.2-SOURCE-20120614-yocto.iso

Before running get_cd() recall function to detect whether the card is
present, must make sure the power is up.

Signed-off-by: Jerry Huang <Chang-Ming.Huang@freescale.com>
Signed-off-by: Chunhe Lan <Chunhe.Lan@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
]

6/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: powerpc/p2020: update the espi device node
Date: Tue, 12 Jun 2012 10:04:39 +0800

Since we begin to use the mainline driver for espi controller and
m25p80 flash, update the espi device node according to this change.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
ntegrated-by: Wei Yang <wei.yang@windriver.com>
]

7/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: p2020ds: add srio support
Date: Thu, 14 Jun 2012 16:34:04 +0800

Add the corresponding RapidIO device node on dts.

Signed-off-by: Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

8/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p2020: add several i2c device nodes
Date: Mon, 15 Oct 2012 15:09:50 +0800

- Add Analog ADT7461, eeprom on p2020rdb.
- Add ZL2006 on p2020DS.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

9/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: p2020ds: add AMP dts
Date: Tue, 10 Jul 2012 16:18:24 +0800

AMP DTS for core0 and core1.

Signed-off-by: Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

10/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: p2020ds: add 36bit map support
Date: Tue, 17 Jul 2012 16:45:40 +0800

1.36bit dts
2.AMP 36bit dts

Signed-off-by: Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

11/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: p2020rdb: add 36bit support
Date: Wed, 1 Aug 2012 13:31:48 +0800

1.36bit dts
2.36bit AMP dts

Signed-off-by: Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

12/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: Revert "powerpc/85xx: p2020rdb - move the NAND address."
Date: Mon, 6 Aug 2012 16:47:04 +0800

commit 4b2e185d23fe76225f64d243a841985dd4f71733 upstream

This reverts commit 0c00f65653389a408dfbbee7578e671664eea26a.
The initial commit was my fault. There are two boards out there:
P2020RDB and P2020RDB-PC. I wasn't aware of that and assumed that I have
a RDB board in front of me while I the RDB-PC. This patch makes it work
for the RDB-PC variant and breaks it for the RDB. Now there is a device
tree file available for the RDB-PC which was not there earlier. So with
this revert, everything gets back to normal :)

Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
]

13/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: p2020rdb: Update dtb
Date: Tue, 31 Jul 2012 16:38:23 +0800

add srio stub

Signed-off-by: Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

14/21 [
Author: yhe
Email: yongli.he@windriver.com
Subject: dts: gianfar: L2SRAM integration for bd allocation
Date: Thu, 28 Jun 2012 11:15:18 +0800

This provides support for allocation of bd's in L2SRAM.
This option can be enabled via the config variable
CONFIG_GIANFAR_L2SRAM.

Signed-off-by:Yongli He <yongli.he@windriver.com>
Integrated-by: Wei Yang <wei.yang@windriver.com>
]

15/21 [
Author: Yang Wei
Email: Wei.Yang@windriver.com
Subject: fsl-p2020:Fix the following compile error
Date: Mon, 24 Sep 2012 13:10:09 +0800

arch/powerpc/sysdev/fsl_pmc.c:123:3: error: implicit declaration of function 'enable_kernel_spe'
arch/powerpc/sysdev/fsl_pmc.c:125:3: error: implicit declaration of function 'enable_kernel_fp'

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

16/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: gianfar: Adjust the argument passed to put_page
Date: Wed, 10 Oct 2012 13:55:46 +0800

The skb_frag_struct structure is changed in 3.4 kernel, hence the
argument passed to put_page need to be adjusted.

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

17/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: dts: adjust the size of nand flash partition for P2020RDB
Date: Mon, 22 Oct 2012 15:23:26 +0800

adjust the size of nand flash partition to leave the
enough flash space with windriver jffs2 image

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

18/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: mmc: Fix the warning of mmc when CPU is being in sleep mode.
Date: Thu, 18 Oct 2012 09:35:07 +0800

When CPU is being put to sleep by echoing "standby" to
/sys/power/state, the below kernel warning is generated.

sysfs: kobject mmcblk0 without dirent
------------[ cut here ]------------
WARNING: at
linux-windriver-3.4-r0/linux/fs/sysfs/file.c:498

Modules linked in:
NIP: c01c1b20 LR: c01c1b20 CTR: c0494a20
REGS: ef311c20 TRAP: 0700   Not tainted  (3.4.10-WR5.0.0.0_standard+)
MSR: 00029000 <CE,EE,ME>  CR: 22442684  XER: 00000000
TASK = ef9985a0[791] 'sh' THREAD: ef310000 CPU: 1
GPR00: c01c1b20 ef311cd0 ef9985a0 0000002c 00021000 fffffff	c0420250 0001ffff
GPR08: c0903344 c089f2c4 00000001 00f6f000 82442622 100f485	00000000 00000000
GPR16: 100ecee0 100f0000 100f0000 100f0000 100fb908 10116568 0000000 00000000
GPR24: c06f5850 ffffffed c0796730 00000008 ef16e000 ef16e000 ef16ae68 ef16e290
NIP [c01c1b20] sysfs_attr_ns+0xb8/0xd0
LR [c01c1b20] sysfs_attr_ns+0xb8/0xd0
Call Trace:
[ef311cd0] [c01c1b20] sysfs_attr_ns+0xb8/0xd0 (unreliable)
[ef311ce0] [c01c1b64] sysfs_remove_file+0x2c/0x58
[ef311d00] [c042bac0] device_remove_file+0x28/0x38
[ef311d10] [c056eb34] mmc_blk_remove_req+0x44/0xb4
[ef311d20] [c0570ecc] mmc_blk_remove+0xbc/0xdc
[ef311d40] [c0563e38] mmc_bus_remove+0x2c/0x40
[ef311d50] [c042f314] __device_release_driver+0x74/0xd8
[ef311d60] [c042f3ac] device_release_driver+0x34/0x50
[ef311d70] [c042ed54] bus_remove_device+0xe8/0x120
[ef311d90] [c042bcd0] device_del+0x120/0x1b8
[ef311db0] [c056456c] mmc_remove_card+0x6c/0xb0
[ef311dc0] [c0567da8] mmc_sd_remove+0x40/0x5c
[ef311dd0] [c0563d60] mmc_pm_notify+0xe4/0x128
[ef311df0] [c06ac0a0] notifier_call_chain+0x70/0xc0
[ef311e20] [c006ede4] __blocking_notifier_call_chain+0x5c/0x80
[ef311e40] [c006ee2c] blocking_notifier_call_chain+0x24/0x34
[ef311e50] [c0089048] pm_notifier_call_chain+0x30/0x54
[ef311e60] [c0089df8] pm_suspend+0xf0/0x1f0
[ef311e80] [c0088bd0] state_store+0xa8/0xec
[ef311ea0] [c03be6cc] kobj_attr_store+0x24/0x3c
[ef311eb0] [c01c11d8] sysfs_write_file+0x104/0x1a4
[ef311ee0] [c0152a64] vfs_write+0xb4/0x178
[ef311f00] [c0152e34] sys_write+0x5c/0x138
[ef311f40] [c00106ac] ret_from_syscall+0x0/0x3c
]

19/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: gianfar: use spin_lock_irqsave/unlock_restore instead of spin_lock/unlock_irq
Date: Thu, 18 Oct 2012 16:34:43 +0800

The below Call Trace is threw in process of using kgdboe to debug
kernel.

netpoll_send_skb(): eth1 enabled interrupts in poll (gfar_start_xmit+0x0/0x774)
KGDB: re-enter exception: ALL breakpoints killed
Call Trace:
[cfbf3ac0] [c0008c14] show_stack+0x10c/0x1c0 (unreliable)
[cfbf3b10] [c064b050] dump_stack+0x24/0x34
[cfbf3b20] [c00a9590] kgdb_handle_exception+0x190/0x1b0
[cfbf3b70] [c00116b0] kgdb_handle_breakpoint+0x4c/0x90
[cfbf3b80] [c0643d3c] program_check_exception+0x238/0x254
[cfbf3b90] [c0010954] ret_from_except_full+0x0/0x4c
]

20/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: net/gianfar_ptp: use correct resource tree
Date: Tue, 23 Oct 2012 13:49:46 +0800

Since the type of the device resource is IORESOURCE_MEM,
so use "iomem_resource" instead of "ioports_resource".

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

21/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/smp: save each CPU's idle task structure
Date: Thu, 25 Oct 2012 16:22:32 +0800

When enabling ftrace function profiling via the following command,

	 echo 1 >/sys/kernel/debug/tracing/function_profile_enabled

and then cycling CPU1 offline and online. the following warning call
trace is thrown by kernel.

WARNING: at kernel/trace/ftrace.c:4609

Modules linked in: loop jbd2 exportfs ext4 xfs jfs reiserfs squashfs
isofs cramfs jffs2 yaffs fat vfat msdos nls_cp437 nls_iso8859_1 tipc
[last unloaded: control_crash]
NIP: c00dbdec LR: c062a474 CTR: 00000000
REGS: ef8c5d60 TRAP: 0700   Tainted: G        W  O
(3.4.10-WR5.0.0.0_standard)
MSR: 00029000 <CE,EE,ME>  CR: 24042088  XER: 20000000
TASK = ef8d0e60[10] 'kworker/0:1' THREAD: ef8c4000 CPU: 0
GPR00: 00000001 ef8c5e10 ef8d0e60 eeac5640 00000001 80000000 00000000 a6290174
GPR08: 00f60000 00000000 ef8c4000 00f69000 24042082 00043382 00000000 3ff94374
GPR16: c0000a00 00000014 3fffffff 00ff6000 c08f0000 c08ef270 c08a5220 c08a5220
GPR24: ef8c4000 00000000 00029000 c180e240 00000000 00000004 00000001 eeac5640
NIP [c00dbdec] ftrace_graph_init_idle_task+0x58/0x10c
LR [c062a474] init_idle+0x164/0x194
Call Trace:
[ef8c5e10] [00000004] 0x4 (unreliable)
[ef8c5e30] [c062a474] init_idle+0x164/0x194
[ef8c5e50] [c0628ba4] fork_idle+0x90/0xa8
[ef8c5f20] [c06283d0] do_fork_idle+0x1c/0x3c
[ef8c5f30] [c0061308] process_one_work+0x15c/0x4b8
[ef8c5f70] [c0061ea8] worker_thread+0x198/0x370

When we successfully create idle task for each CPU, respectively,
we must invoke set_idle_for_cpu() to save the idle task structure to
the idle_thread_array variable for each CPU. The intention is to avoid
to recreate idle task when CPU is brought back online. If not, when CPU
is brought back online, the kernel will invoke fork_idle() to recreate
idle task, The function will eventually trigger trace_graph_init_task()
that allocate a return stack for newly created task. The new allocated
return stack must be not equal the idle_ret_stack variable. Hence,When
CPU is brought online, the WARNING is generated.

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>