MIPS: OCTEON: use cpumask_set_cpu function replace cpu_set
Issue: LIN8-5508

1/1 [
Author: Zhixiong Chi
Email: zhixiong.chi@windriver.com
Subject: MIPS: OCTEON: use cpumask_set_cpu function replace cpu_set
Date: Thu, 12 Jan 2017 15:52:05 +0800

Use cpumask_set_cpu() replace cpu_set function which is not defined or
declared in the file, so when we build kernel with NUMA supported config
via menuconfig, it will occour the error info as follows:
In function 'octeon_setup_numa':
arch/mips/cavium-octeon/octeon-numa.c:41:2: error:
  implicit declaration of function 'cpu_set' [-Werror=implicit-function-declaration]
  cpu_set(0, *mask);
  ^

Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>