Fix the build issue if FIQ is enabled on zyqn
JIRAID: LIN5-18017

1/1 [
Author: "Xudong.zhu"
Email: xudong.zhu@windriver.com
Subject: Fix the build issue if FIQ is enabled on zyqn
Date: Thu, 20 Feb 2014 17:50:12 +0800

JIRAID: LIN5-18017

When enable FIQ on ZYNQ platform, the error below will happen.

arch/arm/kernel/fiq.c:In function 'enable_fiq':
arch/arm/kernel/fiq.c:127:19:error: 'FIQ_START' undeclared (first use in this function)
arch/arm/kernel/fiq.c:127:19:note: each undeclared identifier is reported only once for
                             each function it appears in
arch/arm/kernel/fiq.c:In function 'disable_fiq':
arch/arm/kernel/fiq.c:132:20:error: 'FIQ_START' undeclared (first use in this function)

The reason is FIQ_START is not defined for specific platform.
To fix this error, FIQ_START is required if the hardware supports FIQ mode,
plus Xilinx zynq platform is based on ARM A9 cpu, so FIQ is supported and
the FIQ_START is 28.

Signed-off-by: Xudong.zhu <xudong.zhu@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>