security: fix compile issue
CQID: WIND00340326

1/1 [
Author: Junxiao Bi
Email: junxiao.bi@windriver.com
Subject: security: fix compile issue
Date: Tue, 20 Mar 2012 17:15:56 +0800

When CONFIG_SECURITY is disabled, the following compile error is reported,
In file included from init/main.c:33:
include/linux/security.h:1820: error: static declaration of 'security_capable' follows non-static declaration
include/linux/capability.h:523: error: previous declaration of 'security_capable' was here
include/linux/security.h:1825: error: static declaration of 'security_capable_noaudit' follows non-static declaration
linux/capability.h:524: error: previous declaration of 'security_capable_noaudit' was here
scripts/Makefile.build:214: *** [init/main.o] Error 1
Makefile:872: *** [init] Error 2
Makefile:128: *** [sub-make] Error 2

As these two functions have been declared in include/linux/security.h,
so remove them here.

Signed-off-by: Junxiao Bi <junxiao.bi@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>