I2C: mv64xxx: fix compile errors
Issue: LIN5-20356

1/1 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: I2C: mv64xxx: fix compile errors.
Date: Thu, 23 Apr 2015 15:36:04 +0800

Commit "I2C: mv64xxx: fix race between FSM/interrupt and process context"
introduced some compilation error as follows:

| drivers/i2c/busses/i2c-mv64xxx.c:114:19: error: duplicate member 'msg'
| drivers/i2c/busses/i2c-mv64xxx.c: In function 'mv64xxx_i2c_do_action':
| drivers/i2c/busses/i2c-mv64xxx.c:262:11: error: 'struct mv64xxx_i2c_data' has no member named 'msgs'
| drivers/i2c/busses/i2c-mv64xxx.c:266:3: error: implicit declaration of function 'mv64xxx_i2c_prepare_for_io' [-Werror=implicit-function-declaration]
| drivers/i2c/busses/i2c-mv64xxx.c:266:48: error: 'struct mv64xxx_i2c_data' has no member named 'msgs'
| drivers/i2c/busses/i2c-mv64xxx.c: At top level:
| drivers/i2c/busses/i2c-mv64xxx.c:375:1: warning: conflicting types for 'mv64xxx_i2c_prepare_for_io' [enabled by default]
| drivers/i2c/busses/i2c-mv64xxx.c:375:1: error: static declaration of 'mv64xxx_i2c_prepare_for_io' follows non-static declaration
| drivers/i2c/busses/i2c-mv64xxx.c:266:3: note: previous implicit declaration of 'mv64xxx_i2c_prepare_for_io' was here
| drivers/i2c/busses/i2c-mv64xxx.c: In function 'mv64xxx_i2c_xfer':
| drivers/i2c/busses/i2c-mv64xxx.c:478:2: error: 'struct mv64xxx_i2c_data' has no member named 'msgs'
| drivers/i2c/busses/i2c-mv64xxx.c:479:10: error: 'struct mv64xxx_i2c_data' has no member named 'msgs'
| drivers/i2c/busses/i2c-mv64xxx.c:487:10: error: 'struct mv64xxx_i2c_data' has no member named 'msgs'
| drivers/i2c/busses/i2c-mv64xxx.c:489:2: error: expected ';' before 'return'
| drivers/i2c/busses/i2c-mv64xxx.c:490:1: warning: control reaches end of non-void function [-Wreturn-type]

Three bugs need to be fixed:
-) The first domain of structure mv64xxx_i2c_data should be
"msgs" instead of "msg";
-) Static function should be defined before it was used;
-) An ";" was missed at the end of a setence.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>