Revert "x86/platform/iosf_mbi: Remove duplicate definitions"
Issue: LIN8-5400

1/1 [
Author: Zhenbo Gao
Email: zhenbo.gao@windriver.com
Subject: Revert "x86/platform/iosf_mbi: Remove duplicate definitions"
Date: Tue, 10 Jan 2017 10:48:17 +0800

Kernel 4.1.x doesn't need this commit since there is no duplicate
definition issue here.

Compile will fail if not reverting this commit, the error output:
----
../drivers/thermal/intel_soc_dts_thermal.c:124:42: error: \
'BT_MBI_BUNIT_READ' undeclared (first use in this function)
  status = iosf_mbi_read(BT_MBI_UNIT_PMC, BT_MBI_BUNIT_READ,
...

This reverts commit 9dd7102d0644383a72e10d862b6940ac73c611f2.

Signed-off-by: Zhenbo Gao <zhenbo.gao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>