X86: add cpu_feature function for x86
1/1 [
Author: Jianchuan Wang
Email: jianchuan.wang@windriver.com
Subject: X86: add cpu_feature function for x86
Date: Fri, 10 Oct 2014 15:53:22 +0800

When cpu feature based module autoloading is enabled, the following
build error is triggered in all x86 builds:

 include/linux/cpufeature.h:47:15:
 error: implicit declaration of function 'cpu_feature'
 [-Werror=implicit-function-declaration]

To fix this issue, we can define cpu_feature in a similar manner as
ARM64 in commit 64acd011a12.

Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>