remove cgroup module patch, it breaks mod compiles.
  CC [M]  net/sched/cls_cgroup.o
net/sched/cls_cgroup.c: In function 'cgrp_cls_state':
net/sched/cls_cgroup.c:47: error: 'net_cls_subsys_id' undeclared (first use in this function)
net/sched/cls_cgroup.c:47: error: (Each undeclared identifier is reported only once
net/sched/cls_cgroup.c:47: error: for each function it appears in.)
net/sched/cls_cgroup.c: In function 'task_cls_state':
net/sched/cls_cgroup.c:53: error: 'net_cls_subsys_id' undeclared (first use in this function)
make[2]: *** [net/sched/cls_cgroup.o] Error 1
make[1]: *** [net/sched/cls_cgroup.o] Error 2
make: *** [sub-make] Error 2

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>