Freescale P4080 to sdk dpaa-1.0 - WR integration patches
CQID: WIND00283218

1/4 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: mmc/host: fix mfspr undefined error
Date: Wed, 27 Jul 2011 16:25:31 +0800

mfspr is only defined in PPC platform, so add #ifdef CONFIG_PPC
to control it.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

2/4 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: mtd/devices/m25p80: fix compile error in non-ppc platform
Date: Wed, 27 Jul 2011 16:25:34 +0800

In non-ppc platform, compile error happens:
drivers/mtd/devices/m25p80.c: In function 'parse_flash_partition':
drivers/mtd/devices/m25p80.c:840: error: 'struct dev_archdata' has no member named 'of_node'
scripts/Makefile.build:313: *** [drivers/mtd/devices/m25p80.o] Error 1
scripts/Makefile.build:365: *** [drivers/mtd/devices] Error 2

function parse_flash_partition is introduced by fsl spi driver, so
use CONFIG_SPI_FSL_LIB to restrict it here.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

3/4 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: powerpc/mmu: restrict next_tlbcam_idx declaration
Date: Fri, 29 Jul 2011 14:46:49 +0800

next_tlbcam_idx is defined that way:
arch/powerpc/mm/tlb_nohash.c:
...
139 #ifdef CONFIG_PPC_FSL_BOOK3E
140 /* next_tlbcam_idx is used to round-robin tlbcam entry assignment */
141 DEFINE_PER_CPU(int, next_tlbcam_idx);
142 EXPORT_PER_CPU_SYMBOL(next_tlbcam_idx);
143 #endif
...

So when DECLARE_PER_CPU(int, next_tlbcam_idx), macro CONFIG_PPC_FSL_BOOK3E
is also needed.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

4/4 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: net/dpa: set CONFIG_FSL_FMAN default value as n
Date: Fri, 29 Jul 2011 14:46:51 +0800

Currently CONFIG_FSL_FMAN is enabled by default, and the
result is CONFIG_FSL_FMAN is always y in all boards. it is not
right(even no harm), so here set CONFIG_FSL_FMAN to n by default.
CONFIG_FSL_FMAN needs to be turned on explicitly in board cfg.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>