selinux: fix parallel compile error
1/1 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: selinux: fix parallel compile error
Date: Fri, 6 Aug 2010 14:12:00 -0700

Selinux has an autogenerated file, "flask.h" which is included by
two other selinux files.  The current makefile has a single dependency
on the first object file in the selinux-y list, assuming that will get
flask.h generated before anyone looks for it, but that assumption breaks
down in a "make -jN" situation and you get:

   selinux/selinuxfs.c:35: fatal error: flask.h: No such file or directory
   compilation terminated.
   remake[9]: *** [security/selinux/selinuxfs.o] Error 1

Since flask.h is included by security.h which in turn is included
nearly everywhere, make the dependency apply to all of the selinux-y
list of objs.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>