msa: fix conflicting variable naming for macro expanding
CQID: WIND00417948

1/1 [
Author: Xin Ouyang
Email: Xin.Ouyang@windriver.com
Subject: msa: fix conflicting variable naming for macro expanding
Date: Mon, 20 May 2013 13:37:50 +0800

In cputime_msa.h, cputime_div() macro will pass a variable __x to do_div().
While do_div()'s arm implementation also has a same named local variable __x.

  #define cputime_div(__a, __n) ({ u64 __x = (__a);do_div(__x, __n);...})
  #define do_div(n, base)       ({ ... { unsigned long long __x, __n = n;...})

This will cause variable collision, and the __x passed by cputime_div() will
be overrided by the local __x. Because cputime_div will be expanded as:

  unsigned long long __x, __n = __x;

This would cause build failures.

KERNELPATH/grsecurity/gracl.c: In function 'gr_acl_handle_psacct':
KERNELPATH/grsecurity/gracl.c:3851:12: error: '__x' may be used
uninitialized in this function [-Werror=uninitialized]

So, rename __x in cputime_div() to avoid this.

Signed-off-by: Xin Ouyang <Xin.Ouyang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>