support P1020_P1011RDB, P1021_P1012MDS and P1023RDB for fsl-p10xx BSP
CQID: WIND00383933

1/21 [
Author: Jiang Lu
Email: lu.jiang@windriver.com
Subject: PowerPC:P1021MDS: add CAMP support
Date: Tue, 25 Jan 2011 17:30:09 +0800

Add device tree for AMP Core0 & Core1 of P1021MDS.

[Extracted from the P1022DS_20100925-ltib.iso vendor drop.
add i2c device nodes,
modify partition table with merging 2 writable partition,
add comment on USB node.]

Remove eTSEC3 and crypto from Core1

Signed-off-by: Haiying Wang <Haiying.Wang@freescale.com>
Signed-off-by: Jin Yanjiang <B30464@freescale.com>
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Wei Yang <wei.yang@windriver.com>
]

2/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1021mds: set/release muxed QE12 pin for UEC MII and LBCTL
Date: Wed, 13 Mar 2013 15:52:51 +0800

P1021 has QE_MDIO pin muxed with LBCTL pin, which is controlled by
PMUXCR[QE12]. For accessing mdio by probing mdio bus and read/write phy
registers, QE12 needs to be set together with QE9 to enable both
QE_MDIO and QE_MDC. However, after accessing mdio, QE12 needs to be
released so that eLBC can be accessed properly.

Signed-off-by: Haiying Wang <Haiying.Wang@freescale.com>
[Extracted from the P1021MDS-20101124-ltib.iso vendor drop.
Fixed context to apply to Wind River kernel tree.]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

3/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/QE: Add support for Timestamp timer on QE
Date: Thu, 14 Mar 2013 16:12:14 +0800

This patch adds support for Timestamp timer on QUICC Engine.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
 mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

4/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: atm: add ATM driver for UCC of QE
Date: Wed, 13 Mar 2013 17:15:17 +0800

Add ATM driver for UCC of QE.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso some context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

5/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: PowerPC/QE: add support for utopia upc on QE
Date: Wed, 13 Mar 2013 17:29:00 +0800

The UPC (UTOPIA/POS-PHY L2 bus Controller) is the UTOPIA/POS-PHY
MAC peripheral of the QUICC Engine block. It is a user
programmable hardware controller which interfaces directly to the
Utopia / POS-PHY L2 bus.

This patch adds support for utopia upc on QUICC Engine.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

6/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: P1021MDS/ATM: QE pio initial code for ATM feature
Date: Thu, 14 Mar 2013 10:21:40 +0800

The patch add QE pio initial code for ATM feature.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

7/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/ucc: UCC modification for ATM
Date: Thu, 14 Mar 2013 16:58:13 +0800

If UCC works as ATM, its clocks come from UPC and do not needs io pins

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
 mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

8/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/atm: ATM cofiguration for P1021MDS
Date: Fri, 15 Mar 2013 13:28:09 +0800

include bcsr and PMUXCR settings.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

9/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/dts: Add ATM support for P1021MDS
Date: Fri, 15 Mar 2013 13:29:59 +0800

This patch add corresponding device node for ATM support.

Signed-off-by: Liu Yu <yu.liu@freescale.com>
[Extracted from P1021MDS_20101124_ltib.iso Just some minor context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

10/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/dts: update p1021 dts file
Date: Mon, 18 Mar 2013 10:00:36 +0800

Update the espi device node according to the fsl espi driver
Update TDM device node according to UCC TDM driver
add "sdhci,auto-cmd12" to sdhci device node to uses Auto CMD12 command
to stop the transfer.

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

11/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1022ds: Fix a building error
Date: Mon, 4 Feb 2013 17:15:40 +0800

Fix the following buidling error. ';' is missed.
arch/powerpc/platforms/85xx/p1022_ds.c:606:1: error: expected ',' or ';' before 'static'
arch/powerpc/platforms/85xx/p1022_ds.c: In function '__machine_initcall_p1022_ds_p1022_ds_publish_elbc_device':
arch/powerpc/platforms/85xx/p1022_ds.c:610:1: error: implicit declaration of function 'p1022_ds_publish_elbc_device' [-Werror=implicit-function-declaration]
arch/powerpc/platforms/85xx/p1022_ds.c: At top level:
arch/powerpc/platforms/85xx/p1022_ds.c:601:39: error: 'p1022_elbc_ids' defined but not used [-Werror=unused-variable]
cc1: all warnings being treated as errors
make[4]: *** [arch/powerpc/platforms/85xx/p1022_ds.o] Error 1

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

12/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1021mds: support TDM for P1021MDS
Date: Tue, 19 Mar 2013 17:38:49 +0800

set bcsr and PMUXCR register to support TDM for P1021MDS

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

13/21 [
Author: Anatolij Gustschin
Email: agust@denx.de
Subject: USB: fix fsl_otg config dependency
Date: Tue, 4 Dec 2012 14:26:11 +0100

commit b33d74db39aae32e7d57265e25c94a488c42e37 upstream

USB_GADGET_FSL_USB2 has been changed to USB_FSL_USB2 by commit
193ab2a6070039e7ee2b9b9bebea754a7c52fd1b (usb: gadget: allow
multiple gadgets to be built). But old USB_GADGET_FSL_USB2 is
still listed as dependency for fsl_otg driver, so the driver
cannot be selected in the configuration currently. Fix it.

Signed-off-by: Anatolij Gustschin <agust@denx.de>
Signed-off-by: Felipe Balbi <balbi@ti.com>
]

14/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/dts: Add dts file for TDM feature of P1021MDS
Date: Thu, 21 Mar 2013 11:15:53 +0800

The dts file support QE-TDM function and PQ-MDS-T1 card for P1021MDS
PQ-MDS-T1 is connected to the board by PMC.
Signed-off-by: Kai.Jiang <Kai.Jiang@freescale.com>
[Extracted from P1021MDS_20110118_TDM_Patch.iso some context mods in
order to port to kernel 3.4]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

15/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: tdm/line_ctrl:make Zarlink Slic module optional
Date: Thu, 21 Mar 2013 11:26:17 +0800

According to Kconfig, the module is not selected by default.
so modify the Makefile to make the module optional

Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

16/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1021mds: remove ehci controller compatible property
Date: Mon, 25 Mar 2013 12:13:11 +0800

If ehci controller version is 1.6 or above, we need to check
PHY_CLK_VALID to avoid that kernel booting up will hang during USB
initialization while missing USB PHY clock.

Per p1021MDS specific pdf, PHY_CLK_VALID isn't defined in the USB
control register actually. So we should remove this compatible property
in dts to skip this undefined behaviour.

Signed-off-by: Tiejun Chen <tiejun.chen@windriver.com>
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

17/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1023rdb: Add p1023rdb board support
Date: Mon, 25 Mar 2013 13:22:53 +0800

Signed-off-by: John Rigby <jcrigby@silicontkx.com>
[Extracted from SDK 1.2.1 for p1023, minor patch context modifications.]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

18/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/p1023rdb: Fix phy nodes in device tree
Date: Mon, 25 Mar 2013 13:32:30 +0800

Signed-off-by: John Rigby <jcrigby@silicontkx.com>
[Extracted from SDK 1.2.1 for p1023, minor patch context modifications.]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

19/21 [
Author: Kumar Gala
Email: galak@kernel.crashing.org
Subject: powerpc/85xx: Add DPAA support to P1023 SoC device tree files
Date: Fri, 18 Nov 2011 09:25:25 -0600

P1023 has 2 FMan ethernet ports, 3 Q/Bman SW portals, and 3 Qman pool
channels.

Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
[Extracted from SDK 1.2.1 for p1023, minor patch context modifications.]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

20/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: qbman/dpaa_eht/usdpaa: dynmaic pool-channel/CGR allocation
Date: Mon, 25 Mar 2013 14:36:58 +0800

Pool-channels are now described via a range node+property (specifying
 the range of channel IDs) rather than a separate node for each pool containing
 a channel ID property. The set of valid CGR IDs are also specified via a
 range node+property. Allocator APIs are added for both type of object
 (in-kernel as well as for USDPAA).

 Consequently, the dpaa_eth "ethernet" nodes no longer link to the pool
 channel they are to use, the driver is modified to instead dynamically
 allocate a single pool-channel for all its interfaces.

Signed-off-by: Geoff Thorpe <Geoff.Thorpe@freescale.com>
[Extracted from SDK 1.2.1 for p1023, minor patch context modifications.]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

21/21 [
Author: Wei Yang
Email: Wei.Yang@windriver.com
Subject: powerpc/85xx: Add DPAA/networking support for P1023RDS/RDB
Date: Wed, 27 Mar 2013 17:19:49 +0800

The original patch only supports P1023RDS, compared with the original
patch, only add DPAA support for P1023RDB.

Signed-off-by: Roy Zang <tie-fei.zang@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
[QorIQ-SDK-V1.3.1-20121220-yocto image. Just some minor context
mods in order to port to 3.4 kernel]
Signed-off-by: Wei Yang <Wei.Yang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>