EDAC driver for Denverton/Goldmont
1/5 [
Author: Liwei Song
Email: liwei.song@windriver.com
Subject: Revert "EDAC: pnd2_edac: Add new EDAC driver for Intel SoC platforms"
Date: Mon, 10 Apr 2017 04:14:18 -0400

This reverts patch "EDAC: pnd2_edac: Add new EDAC driver for Intel SoC
platforms".
Since it is just part of upstream commit [EDAC, pnd2_edac: Add new EDAC
driver for Intel SoC platforms] 5c71ad17f97e84d6d7e11a8e193d5d96890ed2ed
so revert it to use the upstream one instead of this one.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

2/5 [
Author: Tony Luck
Email: tony.luck@intel.com
Subject: EDAC, pnd2_edac: Add new EDAC driver for Intel SoC platforms
Date: Thu, 9 Mar 2017 01:45:39 +0800

commit 5c71ad17f97e84d6d7e11a8e193d5d96890ed2ed upstream.

Initial target for this driver is the Intel Apollo Lake platform and
Denverton micro-server, they use the same internal memory controller IP
called Pondicherry2.

Memory controller registers are not in PCI config space like earlier
Intel memory controllers. For Apollo Lake platform they are accessed via
a "side-band" interface, for Denverton micro-server they are access via
PCI config space and memory map I/O. This driver is for Apollo Lake and
Denverton, but only the Denverton is fully enabled while we wait for the
sideband driver.

Apollo lake driver and initial cut at Denverton driver by Tony Luck.
Extensive cleanup, refactoring and basic verification by Qiuxu Zhuo.

Signed-off-by: Tony Luck <tony.luck@intel.com>
Signed-off-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
Cc: linux-edac <linux-edac@vger.kernel.org>
Link: http://lkml.kernel.org/r/20170308174539.14432-1-qiuxu.zhuo@intel.com
Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

3/5 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC, pnd2_edac: Fix !EDAC_DEBUG build
Date: Sat, 18 Mar 2017 18:26:34 +0100

commit cd1be315ac9766fe83e4fb788d5d9fe032a9b877 upstream.

Provide debugfs function stubs when EDAC_DEBUG is not enabled so that we
don't fail the build:

  drivers/edac/pnd2_edac.c: In function ‘pnd2_init’:
  drivers/edac/pnd2_edac.c:1521:2: error: implicit declaration of function ‘setup_pnd2_debug’ [-Werror=implicit-function-declaration]
    setup_pnd2_debug();
    ^
  drivers/edac/pnd2_edac.c: In function ‘pnd2_exit’:
  drivers/edac/pnd2_edac.c:1529:2: error: implicit declaration of function ‘teardown_pnd2_debug’ [-Werror=implicit-function-declaration]
    teardown_pnd2_debug();
    ^

Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

4/5 [
Author: Qiuxu Zhuo
Email: qiuxu.zhuo@intel.com
Subject: EDAC, pnd2_edac: Fix reported DIMM number
Date: Sat, 25 Mar 2017 19:29:01 +0800

commit 819f60fb7db169d851186d04e571e9bca27321e8 upstream.

DIMM number passed to edac_mc_handle_error() was accidentally hardcoded
to zero. Pass in the correct daddr->dimm value.

Signed-off-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

5/5 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC: Select DEBUG_FS
Date: Sat, 18 Mar 2017 18:25:05 +0100

commit 1c5bf78114d38c2761721108a2d925bccb496027 upstream.

The debugfs.c functionality relies on DEBUG_FS so select it.

Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>