imx6/fsl: #ifdef use of platform_pad_change function pointer
CQID: WIND00344719

1/1 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: imx6/fsl: #ifdef use of platform_pad_change function pointer
Date: Wed, 9 Jan 2013 11:29:32 -0500

On fsl ppc boards (non-imx):
drivers/mmc/host/sdhci-esdhc.h:87:15: error: dereferencing pointer to incomplete type
drivers/mmc/host/sdhci-esdhc.h:88:12: error: dereferencing pointer to incomplete type

Function pointer platform_pad_change is added to struct
esdhc_platform_data in arch/arm/plat-mxc/include/mach/esdhc.h, so it
should only be used by that arch, so ifdef with this:

config MMC_SDHCI_ESDHC_IMX
        tristate "SDHCI support for the Freescale eSDHC/uSDHC i.MX controller"
        depends on ARCH_MXC || ARCH_MX6

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>