msa: make depend on BROKEN
CQID: WIND00417931

1/1 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: msa: make depend on BROKEN
Date: Wed, 22 May 2013 09:27:48 -0400

Feature isol introduces changes that are not compatible with msa.  This
results in breakage when msa is configured:

kernel/sched/cputime.c:151:6: error: redefinition of 'account_user_time'
include/linux/kernel_stat.h:127:20: note: previous definition of 'account_user_time' was here
kernel/sched/cputime.c:227:6: error: redefinition of 'account_system_time'
include/linux/kernel_stat.h:129:20: note: previous definition of 'account_system_time' was here
kernel/sched/cputime.c:262:6: error: redefinition of 'account_idle_time'
include/linux/kernel_stat.h:131:20: note: previous definition of 'account_idle_time' was here
kernel/sched/cputime.c: In function 'cputime_adjust':
kernel/sched/cputime.c:598:2: error: implicit declaration of function 'nsecs_to_cputime' [-Werror=implicit-function-declaration]
kernel/sched/cputime.c: In function 'task_cputime_adjusted':
kernel/sched/cputime.c:637:29: error: 'struct task_struct' has no member named 'prev_cputime'

Additionally, during review it was noted:
"the accounting code has been changed significantly in order to do the
no hertz stuff, and I don't see trying to reconcile the two as
[valuable]"

Force msa to be disabled on the ovp kernel.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>