secure kernel build failure fixes
1/3 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: pax: disable the plugin checks for now
Date: Wed, 15 Jan 2014 19:01:38 -0500

Need to determine if supporting plugins in a cross compile
environment is worthwhile.  In the interim, the host checks
are counterproductive in forcing a failure and suggesting
that plugins get installed.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

2/3 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: grsec: Fix build failure
Date: Fri, 14 Feb 2014 10:25:32 -0800

Add missing ")" to fix the below build failure:

grsecurity/gracl_compat.c: In function 'copy_gr_arg_wrapper_compat':
grsecurity/gracl_compat.c:17:17: error: expected ')' before 'return'
                 return -EINVAL;
                 ^
grsecurity/gracl_compat.c:24:1: error: expected expression before '}' token
 }
 ^
grsecurity/gracl_compat.c:24:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^

Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

3/3 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: grsec: Use atomic operation interface to manipulate atomic variable
Date: Fri, 14 Feb 2014 11:54:07 -0800

The files counter in pipe_inode_info is atomic variable, so it has to be
manipulated by atomic interface.

Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>