Fix build error when build with kts layer
Issue: LIN6-10354

1/1 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: Fix build error when build with kts layer
Date: Tue, 22 Sep 2015 13:48:56 +0800

When build with kernel config CONFIG_DEBUG_LOCK_ALLOC enabled, the following
build error will occur:
include/linux/mutex.h:190:57: error: '#' is not followed by a macro parameter
|  # define __WW_CLASS_MUTEX_INITIALIZER(lockname, ww_class) \

the macro is defined, but has no proper definition. the following commit introduce
this error:
Date:   Wed Feb 11 13:05:18 2015 +0800

    preempt-rt: adjust backport radeon driver support to WRL6

it moved the macro location and not added the definition later, Add it
to fix this issue.
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>