fix build for wrs_sbcp4080 when erratum A-004510 is moved to standard
arch/powerpc/sysdev/fsl_pamu.c:349: warning: "CONFIG_P3041_DS" is not defined
arch/powerpc/sysdev/fsl_pamu.c:351: warning: "CONFIG_P4080_DS" is not defined
arch/powerpc/sysdev/fsl_pamu.c:353: warning: "CONFIG_P5020_DS" is not defined
arch/powerpc/sysdev/fsl_pamu.c: In function 'create_csd':
arch/powerpc/sysdev/fsl_pamu.c:473: error: 'CSD_PORT_ID' undeclared (first use in this function)
arch/powerpc/sysdev/fsl_pamu.c:473: error: (Each undeclared identifier is reported only once
arch/powerpc/sysdev/fsl_pamu.c:473: error: for each function it appears in.)

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>