Revert "patch refresh for CONFIG_WRHV"
Unwind the mpic removal.  Busted code is still calling into it
even though it should not be.

In function `smp_85xx_setup_cpu':
linux/arch/powerpc/platforms/85xx/smp.c:137:
undefined reference to `mpic_setup_this_cpu'

This reverts commit 8c250b27130eb6574040749cbc17ec4d0c58ea2d.