Add kmemleak feature
This feature will always be patched into the kernel
however it requires that you enable it by including
it as a feature on your configure line.

1/22 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: kmemleak: Add the base support
Date: Mon, 15 Mar 2010 10:11:54 +0800

It's initially imported to mainline kernel in
following commit. But this is the rolled up support
and I add changes from then to 2.6.34-rc1

Integrated-by: Liming Wang <liming.wang@windriver.com>

commit 3c7b4e6b8be4c16f1e6e5c558e33b7ff0db2dfaf
Author: Catalin Marinas <catalin.marinas@arm.com>
Date:   Thu Jun 11 13:22:39 2009 +0100

    kmemleak: Add the base support

    This patch adds the base support for the kernel memory leak
    detector. It traces the memory allocation/freeing in a way similar to
    the Boehm's conservative garbage collector, the difference being that
    the unreferenced objects are not freed but only shown in
    /sys/kernel/debug/kmemleak. Enabling this feature introduces an
    overhead to memory allocations.

    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Ingo Molnar <mingo@elte.hu>
    Acked-by: Pekka Enberg <penberg@cs.helsinki.fi>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Reviewed-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
]

2/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Enable the building of the memory leak detector
Date: Mon, 15 Mar 2010 10:11:55 +0800

commit 3bba00d7bdd57cb7aa739b751fa0a1fbbb04dc18 upstream

This patch adds the Kconfig.debug and Makefile entries needed for
building kmemleak into the kernel.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

3/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Simple testing module for kmemleak
Date: Mon, 15 Mar 2010 10:11:56 +0800

commit 0822ee4ac1ae6af5a953f97f75553738834b10b9 upstream

This patch adds a loadable module that deliberately leaks memory. It
is used for testing various memory leaking scenarios.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

4/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add documentation on the memory leak detector
Date: Mon, 15 Mar 2010 10:11:57 +0800

initial commit:
commit 04f70336c80c43a15e617b36c2043dfa0ad6ed0f upstream
but take Documentation/kmemleak.txt directly from 2.6.34-rc1

This patch adds the Documentation/kmemleak.txt file with some
information about how kmemleak works.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

5/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Allow the early log buffer to be configurable.
Date: Mon, 15 Mar 2010 10:11:58 +0800

commit a9d9058abab4ac17b79d500506e6c74bd16cecdc upstream
but only take lib/Kconfig.debug modification.

(feature suggested by Sergey Senozhatsky)

Kmemleak needs to track all the memory allocations but some of these
happen before kmemleak is initialised. These are stored in an internal
buffer which may be exceeded in some kernel configurations. This patch
adds a configuration option with a default value of 400 and also removes
the stack dump when the early log buffer is exceeded.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Sergey Senozhatsky <sergey.senozhatsky@mail.by>
]

6/22 [
Author: Pekka Enberg
Email: penberg@cs.helsinki.fi
Subject: kmemleak: Don't scan uninitialized memory when kmemcheck is enabled
Date: Mon, 15 Mar 2010 10:11:59 +0800

commit 8e019366ba749a536131cde1947af6dcaccf8e8f upstream
but withdraw kmemleak.c modification.

Ingo Molnar reported the following kmemcheck warning when running both
kmemleak and kmemcheck enabled:

  PM: Adding info for No Bus:vcsa7
  WARNING: kmemcheck: Caught 32-bit read from uninitialized memory
  (f6f6e1a4)
  d873f9f600000000c42ae4c1005c87f70000000070665f666978656400000000
   i i i i u u u u i i i i i i i i i i i i i i i i i i i i i u u u
           ^

  Pid: 3091, comm: kmemleak Not tainted (2.6.31-rc7-tip #1303) P4DC6
  EIP: 0060:[<c110301f>] EFLAGS: 00010006 CPU: 0
  EIP is at scan_block+0x3f/0xe0
  EAX: f40bd700 EBX: f40bd780 ECX: f16b46c0 EDX: 00000001
  ESI: f6f6e1a4 EDI: 00000000 EBP: f10f3f4c ESP: c2605fcc
   DS: 007b ES: 007b FS: 00d8 GS: 00e0 SS: 0068
  CR0: 8005003b CR2: e89a4844 CR3: 30ff1000 CR4: 000006f0
  DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
  DR6: ffff4ff0 DR7: 00000400
   [<c110313c>] scan_object+0x7c/0xf0
   [<c1103389>] kmemleak_scan+0x1d9/0x400
   [<c1103a3c>] kmemleak_scan_thread+0x4c/0xb0
   [<c10819d4>] kthread+0x74/0x80
   [<c10257db>] kernel_thread_helper+0x7/0x3c
   [<ffffffff>] 0xffffffff
  kmemleak: 515 new suspected memory leaks (see
  /sys/kernel/debug/kmemleak)
  kmemleak: 42 new suspected memory leaks (see /sys/kernel/debug/kmemleak)

The problem here is that kmemleak will scan partially initialized
objects that makes kmemcheck complain. Fix that up by skipping
uninitialized memory regions when kmemcheck is enabled.

Reported-by: Ingo Molnar <mingo@elte.hu>
Acked-by: Ingo Molnar <mingo@elte.hu>
Acked-by: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
]

7/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add the slab memory allocation/freeing hooks
Date: Mon, 15 Mar 2010 10:12:00 +0800

commit d5cff635290aec9ad7e6ee546aa4fae895361cbb upstream

This patch adds the callbacks to kmemleak_(alloc|free) functions from
the slab allocator. The patch also adds the SLAB_NOLEAKTRACE flag to
avoid recursive calls to kmemleak when it allocates its own data
structures.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Reviewed-by: Pekka Enberg <penberg@cs.helsinki.fi>
]

8/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add the slub memory allocation/freeing hooks
Date: Mon, 15 Mar 2010 10:12:01 +0800

commit 06f22f13f3cc2eff00db09f053218e5d4b757bc8 upstream

This patch adds the callbacks to kmemleak_(alloc|free) functions from the
slub allocator.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Cc: Christoph Lameter <cl@linux-foundation.org>
Reviewed-by: Pekka Enberg <penberg@cs.helsinki.fi>
]

9/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add the slob memory allocation/freeing hooks
Date: Mon, 15 Mar 2010 10:12:02 +0800

commit 4374e616d28e65265a5b433ceece275449f3d2e3 upstream
with a little modification

This patch adds the callbacks to kmemleak_(alloc|free) functions from the
slob allocator.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Matt Mackall <mpm@selenic.com>
Acked-by: Pekka Enberg <penberg@cs.helsinki.fi>
]

10/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: x86: Provide _sdata in the vmlinux.lds.S file
Date: Mon, 15 Mar 2010 10:12:03 +0800

commit 1260866a271abc84274345580f3d613d3bceff87 upstream
but apply to vmlinux_32.lds.S and vmlinux_64.lds.S two files.

_sdata is a common symbol defined by many architectures and made
available to the kernel via asm-generic/sections.h. Kmemleak uses this
symbol when scanning the data sections.

[ Impact: add new global symbol ]

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
LKML-Reference: <20090511122105.26556.96593.stgit@pc1117.cambridge.arm.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
]

11/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add kmemleak_alloc callback from alloc_large_system_hash
Date: Mon, 15 Mar 2010 10:12:04 +0800

combin following commits.

commit 264ef8a904943ed7d0b04fa958894d7a5c2b2c61
Author: Catalin Marinas <catalin.marinas@arm.com>
Date:   Tue Jul 7 10:33:01 2009 +0100

    kmemleak: Remove alloc_bootmem annotations introduced in the past

    kmemleak_alloc() calls were added in some places where alloc_bootmem was
    called. Since now kmemleak tracks bootmem allocations, these explicit
    calls should be run.

    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Ingo Molnar <mingo@elte.hu>
    Acked-by: Pekka Enberg <penberg@cs.helsinki.fi>

commit 12de38b186c2af97bf0b4a1f907f766df46b1def
Author: Catalin Marinas <catalin.marinas@arm.com>
Date:   Mon Jun 29 17:13:55 2009 +0100

    kmemleak: Inform kmemleak about pid_hash

    Kmemleak does not track alloc_bootmem calls but the pid_hash allocated
    in pidhash_init() would need to be scanned as it contains pointers to
    struct pid objects.

    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

commit dbb1f81ca67a56c6cfce4c94d07c76378fd4af9e
Author: Catalin Marinas <catalin.marinas@arm.com>
Date:   Thu Jun 11 13:23:19 2009 +0100

    kmemleak: Add kmemleak_alloc callback from alloc_large_system_hash

    The alloc_large_system_hash function is called from various places in
    the kernel and it contains pointers to other allocated structures. It
    therefore needs to be traced by kmemleak.

    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

Integrated-by: Liming Wang <liming.wang@windriver.com>
]

12/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add callbacks to the bootmem allocator
Date: Mon, 15 Mar 2010 10:12:05 +0800

commit ec3a354bd46cbdaa7933ba57a142ee2d2dbde0e5 upstream

This patch adds kmemleak_alloc/free callbacks to the bootmem allocator.
This would allow scanning of such blocks and help avoiding a whole class
of false positives and more kmemleak annotations.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Cc: Ingo Molnar <mingo@elte.hu>
Acked-by: Pekka Enberg <penberg@cs.helsinki.fi>
Reviewed-by: Johannes Weiner <hannes@cmpxchg.org>
]

13/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Do not report alloc_bootmem blocks as leaks
Date: Mon, 15 Mar 2010 10:12:06 +0800

commit 008139d9146f9afee0e58df4b7422d0c9921f8ce upstream

This patch sets the min_count for alloc_bootmem objects to 0 so that
they are never reported as leaks. This is because many of these blocks
are only referred via the physical address which is not looked up by
kmemleak.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Cc: Pekka Enberg <penberg@cs.helsinki.fi>
]

14/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add the vmalloc memory allocation/freeing hooks
Date: Mon, 15 Mar 2010 10:12:07 +0800

commit 89219d37a2377c44fde7bff0bf0623453c05329a upstream

This patch adds the callbacks to kmemleak_(alloc|free) functions from
vmalloc/vfree.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

15/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Add modules support
Date: Mon, 15 Mar 2010 10:12:08 +0800

commit 4f2294b6dc88d99295230d97fef2c9863cec44c3 upstream

This patch handles the kmemleak operations needed for modules loading so
that memory allocations from inside a module are properly tracked.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

16/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Ignore the aperture memory hole on x86_64
Date: Mon, 15 Mar 2010 10:12:09 +0800

commit acde31dc467797ccae3a55b791a77af446cce018 upstream

This block is allocated with alloc_bootmem() and scanned by kmemleak but
the kernel direct mapping may no longer exist. This patch tells kmemleak
to ignore this memory hole. The dma32_bootmem_ptr in
dma32_reserve_bootmem() is also ignored.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Ingo Molnar <mingo@elte.hu>
]

17/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Remove some of the kmemleak false positives
Date: Mon, 15 Mar 2010 10:12:10 +0800

commit 2e1483c995bbd0fa6cbd055ad76088a520799ba4 upstream

There are allocations for which the main pointer cannot be found but
they are not memory leaks. This patch fixes some of them. For more
information on false positives, see Documentation/kmemleak.txt.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

18/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Do not use off-slab management with SLAB_NOLEAKTRACE
Date: Mon, 15 Mar 2010 10:12:11 +0800

commit e7cb55b946a2182c347047dc903c6ed0daef100c upstream

With the slab allocator, if off-slab management is enabled for the
kmem_caches used by kmemleak, it leads to recursive calls into
kmemleak_alloc(). Off-slab management can be triggered by other config
options increasing the slab size, e.g. DEBUG_PAGEALLOC.

Reported-by: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>
Reviewed-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Christoph Lameter <cl@linux-foundation.org>
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

19/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Simplify the kmemleak_scan_area() function prototype
Date: Mon, 15 Mar 2010 10:12:12 +0800

commit c017b4be3e84176cab10eca5e6c4faeb8cfc6f3e upstream

This function was taking non-necessary arguments which can be determined
by kmemleak. The patch also modifies the calling sites.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Cc: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Christoph Lameter <cl@linux-foundation.org>
Cc: Rusty Russell <rusty@rustcorp.com.au>
]

20/22 [
Author: Catalin Marinas
Email: catalin.marinas@arm.com
Subject: kmemleak: Trace the kmalloc_large* functions in slub
Date: Mon, 15 Mar 2010 10:12:13 +0800

commit e4f7c0b44a8ac8935f223195af9ea637d0c08091 upstream

The kmalloc_large() and kmalloc_large_node() functions were missed when
adding the kmemleak hooks to the slub allocator. However, they should be
traced to avoid false positives.

Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Cc: Christoph Lameter <cl@linux-foundation.org>
Acked-by: Pekka Enberg <penberg@cs.helsinki.fi>
]

21/22 [
Author: Randy Dunlap
Email: randy.dunlap@oracle.com
Subject: kmemleak: fix kconfig for crc32 build error
Date: Mon, 15 Mar 2010 10:12:14 +0800

commit b60e26a2f03d963f8c79ad7920d64abc4d38ecbc upstream

kmemleak uses crc32 functions so it needs to select CRC32.
Fixes build error:

kmemleak.c:(.text+0x7ce62): undefined reference to `crc32_le'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
]

22/22 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: kmemleak: remove kmemleak from vt
Date: Mon, 15 Mar 2010 10:12:15 +0800

this patch revert the following commit from vt.c:

kmemleak: Remove some of the kmemleak false positives

Because this hasn't been applied to vt.c and has been remove from
mainline kernel.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>