wrl6 scp: secure/base: enable intel-quark - quark specific patchset
1/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add core of Quark patchset.
Date: Tue, 13 Jan 2015 14:45:51 +0800

source: Intel vendor drop 1.1.0-rc2

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

2/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Implement UEFI capsule update runtime service.
Date: Tue, 13 Jan 2015 14:47:04 +0800

source: Intel vendor drop 1.1.0-rc2

This feature is important for Quark platfroms which are deployed remotely.
To update the BIOS and grub stored in flash chip, this runtime service is
helpful to avoid necessity of physical access.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

3/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add the recommended UART driver for Quark SoC.
Date: Thu, 1 Jan 2015 10:42:20 +0800

source: Intel vendor drop 1.1.0-rc2

This driver is the real replacement to 8250_pci for Quark SoC. The glue
mfd driver gives the hint regarding of enumerating 8250_dw, so the necessary
glue codes are added here.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

4/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add the glue driver for HSUART in Quark SoC.
Date: Thu, 1 Jan 2015 10:44:43 +0800

source: Intel vendor drop 1.1.0-rc2

The role of this driver is spliting the 2 UART and DMA devices in orderly
manner for their respective drivers, corresponding to 8250_dw and dw_dmac.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

5/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add SAE J1939 CAN protocol support.
Date: Thu, 1 Jan 2015 11:34:31 +0800

source: Intel vendor drop 1.1.0-rc2

SAE J1939 defines a higher layer protocol on CAN. The j1939 sockets operate
on CAN network devices (see SocketCAN). Refer to
Documentation/networking/j1939.txt for more details.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

6/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add quark platform drivers.
Date: Thu, 1 Jan 2015 13:12:24 +0800

source: Intel vendor drop 1.1.0-rc2

These drivers are dedicated for Quark SoC only. They provide the access to
register and control the platform devices and drivers for Quark SoC specific
hardware access.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

7/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Implement j1708 driver.
Date: Tue, 13 Jan 2015 15:28:12 +0800

source: Intel vendor drop 1.1.0-rc2

This driver works as SAE J1708 protocol receiver. This driver co-works with
the 8250 uart driver, the chosen uart port will be connected to this driver
once the module is loaded and J1708 device file is opened & started.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

8/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Implement custom power management for quark client USB.
Date: Fri, 2 Jan 2015 11:54:04 +0800

source: Intel vendor drop 1.1.0-rc2

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

9/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable VLAN support for stmmac ethernet driver.
Date: Tue, 13 Jan 2015 15:34:54 +0800

source: Intel vendor drop 1.1.0-rc2

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

10/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable Quark SCH GPIO.
Date: Mon, 5 Jan 2015 09:54:33 +0800

source: Intel quark BSP release 1.1.0-rc2

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

11/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable ADC 7298, 1x8s102 and max78m6610 drivers.
Date: Tue, 13 Jan 2015 15:46:33 +0800

source: Intel quark BSP release 1.1.0-rc2

Signed-off-by: Dan O'Donovan <dan.odonovan@emutex.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

12/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable sensor lis331dlh.
Date: Mon, 29 Dec 2014 15:17:56 +0800

source: Intel quark BSP release 1.1.0-rc2

Signed-off-by: Dan O'Donovan <dan.odonovan@emutex.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

13/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable GPIO chip pca953x for Quark.
Date: Mon, 5 Jan 2015 11:17:59 +0800

source: Intel vendor drop 1.1.0-rc2

This patchset adds the PCAL953X model support and enhances GPIO drive types
including pull-up, pull-down, strong and high-z.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

14/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable i2c_dw driver for quark.
Date: Mon, 5 Jan 2015 13:02:37 +0800

source: Intel vendor drop 1.1.0-rc2

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

15/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add mfd drivers for I/O expander.
Date: Mon, 5 Jan 2015 09:26:00 +0800

source: Intel vendor drop 1.1.0-rc2

The MFD drivers for I/O expander target to introduce more I/O interfaces
like I2C, PWM and GPIO used on the Galileo and Galileo Gen2 boards for
maker.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

16/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix j1939 build error caused by vendor's patchset.
Date: Wed, 24 Dec 2014 16:01:48 +0800

Fix the following build errors:

expected 'rtnl_doit_func' but argument is of type 'int (*)(struct sk_buff *, struct nlmsghdr *, void *)'

The 3rd parameter is removed since 3.10 kernel.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

17/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Keep read and write operation in j1939_proc_priv.
Date: Wed, 24 Dec 2014 17:00:51 +0800

Due to the API change of proc interface, create a private j1939 data structure
to hold the necessary callbacks.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

18/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix quark thermal driver dependency.
Date: Thu, 6 Mar 2014 12:28:31 +0800

Otherwise the driver cannot be configured to be module.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

19/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix slcan.c and intel_qrk_j1708.c build errors introduced by vendor's patchset.
Date: Thu, 1 Jan 2015 13:49:47 +0800

The fix resolves the following build errors:

error: request for member 'ifindex' in something not a structure or union
   can_skb_prv(skb)->ifindex = sl->dev->ifindex;

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

20/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Export st_sensors_read_axis_data and st_sensors_write_data_with_mask.
Date: Sun, 4 Jan 2015 10:10:21 +0800

iio driver lis331dlh introduced by Intel vendor drop 1.1.0-rc2 requires
these functions to be exported to skip st_sensors_set_enable() and reading
new data what sensor core currently provides. These behaviors should be
not allowed but we just keep it here for a temporary solution and change
it then when a formal release fixes this.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

21/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix undefined iio realted macros.
Date: Sun, 4 Jan 2015 11:07:41 +0800

This fix resolves the similar build errors for 3 iio drivers, e.g:

error: 'IIO_CHAN_INFO_RAW_SEPARATE_BIT' undeclared here (not in a function)
    .info_mask = IIO_CHAN_INFO_RAW_SEPARATE_BIT  \
                 ^

IIO_CHAN_INFO_RAW_SEPARATE_BIT and IIO_CHAN_INFO_SCALE_SEPARATE_BIT are not
defined and used any more since 3.10. Instead, the single bitfield
"info_mask" now is splited into info_mask_separate and
info_mask_shared_by_type separately.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

22/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix the layout of flash partition.
Date: Mon, 5 Jan 2015 15:42:57 +0800

The setting of partition table should align to layout.conf defined by
spi-layout-tools.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

23/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Fix ioremap for board data.
Date: Mon, 5 Jan 2015 16:01:00 +0800

The failure of ioremap() -> no cln-plat -> cannot get platform id item
within mfh -> intel_cln_plat_get_id() returns CLANTON_PLAT_UNDEFINED ->
stmmac driver cannot be initialized properly.

To fix this issue from root, be aware of using a proper value of mapped
area determined by the maximum size of MFH and platform data area,
which cannot conflict with other MFH items.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

24/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: quark: fix kernel bug when releasing debugfs.
Date: Tue, 7 Jan 2014 11:29:28 +0800

debugfs for stmmac driver is limited to be registered/unregistered one time
only because the registration/unregistration of debugfs for stmmac
driver is called along with adding/removing each interface. For
a multiple interface system, this counter should ensure the unregistration
of debugfs is called one time. However, current code breaks this
rule, triggering the following kernel bug when stoping the 2nd NIC
if debugfs is enabled:

kernel BUG at /home/windriver/prj_0.80_2/bitbake_build/tmp/work/intel_quark-wrs-linux/linux-windriver-3.4-r0/linux/fs/dcache.c:536!
invalid opcode: 0000 [#1]
Modules linked in: hwmon industrialio_triggered_buffer spi_pxa2xx_pci mfd_core lpc_sch thermal_sys evdev stmmac intel_cln_gip button uio i2c_core processor kfifo_buf gpio_sch spidev cdc_acm spi_pxa2xx cy8c9540a at24 ad7298 industrialio udc_core pch_udc i2c_dev led_class g_serial slhc crc_ccitt mtd rfkill crypto_algapi m25p80 crypto_hash ppp_async btusb hidp usbhid cfg80211 af_packet hid ppp_generic rfcomm mac80211 iwlwifi bluetooth ipv6

Pid: 1861, comm: ifconfig Not tainted 3.4.43-WR5.0.1.9_standard #1 Intel Corp. Clanton Peak
EIP: 0060:[<c10cfa92>] EFLAGS: 00210246 CPU: 0
EIP is at dput+0x212/0x220
EAX: 00000000 EBX: cddd6b40 ECX: c178a640 EDX: ced73c60
ESI: 00000000 EDI: cdf1e460 EBP: cec1bdd0 ESP: cec1bdbc
DS: 007b ES: 007b FS: 0000 GS: 0033 SS: 0068
CR0: 8005003b CR2: 088e1404 CR3: 0ecec000 CR4: 00100010
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: ffff0ff0 DR7: 00000400
Process ifconfig (pid: 1861, ti=cec1a000 task=ced73c60 task.ti=cec1a000)
Stack:
cec1bdd0 cddd6b90 cddd6b40 00000000 cdf1e460 cec1bde4 c11a584d cdf1e460
cddd6b40 c10064b0 cec1bdf4 c11a5a05 cedd8000 00002000 cec1be20 e076e5ed
0ede0000 00000000 c0183860 0ede0000 c0183860 cede0000 cedd8000 cec1be44
Call Trace:
[<c11a584d>] __debugfs_remove+0x7d/0xb0
[<c10064b0>] ? dma_generic_alloc_coherent+0xb0/0xb0
[<c11a5a05>] debugfs_remove+0x35/0x80
[<e076e5ed>] stmmac_release+0x29d/0x310 [stmmac]
[<c12d1121>] __dev_close_many+0x71/0xc0
[<c102f9f9>] ? local_bh_enable_ip+0x59/0xc0
[<c12d1198>] __dev_close+0x28/0x40
[<c12d5a1c>] __dev_change_flags+0x7c/0x150
[<c12dfb3f>] ? rtnl_lock+0xf/0x20
[<c12d5b8c>] dev_change_flags+0x1c/0x60
[<c13265bc>] devinet_ioctl+0x52c/0x6e0
[<c12d6110>] ? dev_ioctl+0x1b0/0x5e0
[<c13269d5>] inet_ioctl+0x85/0xb0
[<c12c0a4b>] sock_ioctl+0x6b/0x2a0
[<c1371db2>] ? _raw_spin_unlock_irq+0x22/0x30
[<c12c09e0>] ? sock_fasync+0x80/0x80
[<c10cb8d2>] do_vfs_ioctl+0x82/0x570
[<c1370a52>] ? __schedule+0x182/0x4a0
[<c1022277>] ? do_page_fault+0x1c7/0x3f0
[<c105fd0c>] ? trace_hardirqs_on_caller+0xec/0x170
[<c108379d>] ? call_rcu_sched+0xd/0x10
[<c104905e>] ? __put_cred+0x2e/0x40
[<c10baf0a>] ? sys_faccessat+0x10a/0x180
[<c10cbe27>] sys_ioctl+0x67/0x80
[<c13720f5>] syscall_call+0x7/0xb
Code: 00 00 89 93 84 00 00 00 89 b0 ec 00 00 00 8b 43 74 83 05 c4 83 4e c1 01 83 80 f4 00 00 00 01 b8 20 84 4e c1 e8 90 23 2a 00 eb 9d <0f> 0b 8d b6 00 00 00 00 8d bf 00 00 00 00 55 89 e5 57 56 53 83
EIP: [<c10cfa92>] dput+0x212/0x220 SS:ESP 0068:cec1bdbc
---[ end trace a82d74e253b2368d ]---

This patch confirms doing correct resource cleanup on unloading driver.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

25/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add glue driver for TPM slb9645tt chip used on Cross Hill.
Date: Tue, 22 Apr 2014 16:00:53 +0800

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

26/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Tidy up galileo platform driver.
Date: Mon, 5 Jan 2015 16:52:57 +0800

This platform driver has strong relationship with gpio-sch and gip
drivers. To make sure the dependecies around them, refresh the
register flow to conditionally active the path to get the resource.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

27/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Add the dependency to UIO.
Date: Tue, 6 Jan 2015 09:37:56 +0800

GIP and GPIO_SCH have dependency on UIO. Otherwise, a build error
will happen:

ERROR: "uio_unregister_device" [drivers/mfd/intel_qrk_gip.ko] undefined!

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

28/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: net: stmmac: fix a circular locking dependency
Date: Tue, 6 Jan 2015 09:44:18 +0800

netif_tx_lock spinlock as A, the tx_lock of stmmac's private
structure as B. In ndo_start_xmit process, A->B. While in function
stmmac_tx_clean, changed to B->A. In fact, it is not necessary
to hold the tx_lock for all the function stmmac_tx_clean.
Shrink its scope to avoid the conflict.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

29/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Enable watchdog driver for Quark SoC
Date: Tue, 6 Jan 2015 09:59:10 +0800

ie6xx_wdt driver uses the same register and configuration/logic
as the watchdog inside Quark SoC.
See www.intel.com for:
Intel ATOM E6XX Document Number: 324208-005US (Chapter 11.10)
Intel Quark SoC Document Number: 329676-001US (Chapter 21.14)

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

30/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Disable F00F bug workaround.
Date: Tue, 13 Jan 2015 16:30:58 +0800

Quark SoC doesn't have this bug any more, thus remove Quark SoC from the
dependency.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

31/31 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: spi-pxa2xx: enable MSI support and fix detection failure.
Date: Wed, 14 Jan 2015 10:06:17 +0800

Use PCI function as port_id to identify SPI master instead for Quark
SoC specific.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>