Revise "fix numa can't work correctly on BSP hp_bl460c of kernel-4.3"
CQID: WIND00312360

Breakage for these boards:
emer_atca7101-cgl
emer_atca7101-standard
intel_atom_eg20t_pch-preempt_rt
intel_atom_eg20t_pch-standard
intel_atom_n4xx_d5xx_82801hm-preempt_rt
intel_atom_n4xx_d5xx_82801hm-standard
intel_atom_z530-preempt_rt
intel_atom_z530-standard
kbc_km2m806-standard

arch/x86/kernel/acpi/boot.c: In function 'acpi_register_lapic':
arch/x86/kernel/acpi/boot.c:156: error: 'MAX_LOCAL_APIC' undeclared
(first use in this function)
arch/x86/kernel/acpi/boot.c:156: error: (Each undeclared identifier is
reported only once
arch/x86/kernel/acpi/boot.c:156: error: for each function it appears
in.)

[drop apicid checking with MAX_LOCAL_APIC part, since X86_32 doesn't
 have this definition yet..]

Signed-off-by: Wang Hui <hui.wang@windriver.com>
Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>