driver: fpga: revert redundant driver for fpga bridge feature
Issue: LIN8-3697

1/1 [
Author: Limeng
Email: Meng.Li@windriver.com
Subject: driver: fpga: revert redundant driver for fpga bridge feature
Date: Tue, 31 May 2016 10:38:09 +0800

In wrlinux kernel tree, there is a commit d4afb5121536(ARM: socfpga:
fpga bridge driver support) that introduces 2 driver files
(altera-fpga2sdram.c and altera-hps2fpga.c) to support fpga bridge
feature. But commit 84d4bfacd363(FogBugz #129257: fpga bridge driver)
has supported this feature. Although the 2 commits implement fpga
bridge driver in different directory, they are the same functionality.
Therefore, revert the later one to avoid below error info during kernel
boots up.
Error: Driver 'altera_hps2fpga_bridge' is already registered,
aborting...

Signed-off-by: Meng Li <Meng.Li@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>