mpt2sas: fix for unused variable 'event_data' warning
Issue: LIN6-10097

1/5 [
Author: Liwei Song
Email: liwei.song@windriver.com
Subject: backport the missing config for rtl8168
Date: Sun, 16 Aug 2015 11:06:27 +0800

the driver from:
http://www.realtek.com.tw

since commit cec8bd9f8c59beb0a84582fc1165f1bc49b853b0
the dirver was not completely backport, missing config definition,
include :CONFIG_R8168_NAPI, CONFIG_R8168_VLAN.
without this the dirver will give a compile warning. so redo it.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

2/5 [
Author: Liwei Song
Email: liwei.song@windriver.com
Subject: fix the compile error led by __vlan_hwaccel_put_tag
Date: Sun, 16 Aug 2015 11:11:31 +0800

fix the follwing compile error:
r8168_n.c:2062:3: error: too few arguments to function ‘__vlan_hwaccel_put_tag’

since enable CONFIG_R8168_NAPI and CONFIG_R8168_VLAN it will import this error.
without this two config enable, r8168 will not use __vlan_hwaccel_put_tag().
this is due to the __vlan_hwaccel_put_tag in wr has three args, but the old r8168
just has two, so add the third args just like the new r8168 driver did.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

3/5 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: phy: generic: fix a compiler warning
Date: Fri, 15 Nov 2013 10:35:12 +0200

commit 37cfbc42887fbd4ff0f4c520c9f3fdea9e6f2a82 upstream.

Just because it annoys me.

Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

4/5 [
Author: Stephen Warren
Email: swarren@nvidia.com
Subject: spi: fix SPI_BIT_MASK so it always fits into 32-bits
Date: Thu, 1 Aug 2013 16:08:57 -0600

commit b6aa23ccaea1548cfb404b41129717f13443bccf upstream.

On a 64-bit platform, ~0UL fills 64-bits, which causes SPI_BIT_MASK(32)
not to fit into 32 bits. This causes a warning when the result is assigned
to a 32-bit variable. Use ~0U instead to prevent this. This fixes:

drivers/spi/spi-gpio.c: In function 'spi_gpio_probe':
drivers/spi/spi-gpio.c:446:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Stephen Warren <swarren@nvidia.com>
Signed-off-by: Mark Brown <broonie@linaro.org>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

5/5 [
Author: "Reddy, Sreekanth"
Email: Sreekanth.Reddy@lsi.com
Subject: mpt2sas: fix for unused variable 'event_data' warning
Date: Tue, 26 Feb 2013 17:36:12 +0530

commit c3a634bf78242177fba9c85deb709e7b63ed0ef1 upstream.

If CONFIG_SCSI_MPT2SAS_LOGGING is undefined, then these warnings are emitted

drivers/scsi/mpt2sas/mpt2sas_scsih.c: In function '_scsih_sas_broadcast_primitive_event'
drivers/scsi/mpt2sas/mpt2sas_scsih.c:5810:40: warning: unused variable 'event_data'

Use pr_info() function instead of dewtprintk().

Signed-off-by: Sreekanth Reddy <Sreekanth.Reddy@lsi.com>
Signed-off-by: James Bottomley <JBottomley@Parallels.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>