update serial 8250
Rally: US43591

1/10 [
Author: "Chew, Chiau Ee"
Email: chiau.ee.chew@intel.com
Subject: dma: dw: Add suspend and resume handling for PCI mode DW_DMAC.
Date: Sat, 15 Mar 2014 02:02:39 +0800

commit 4501fe61b286e35be5b372a4f1ffcf5881ceeaed upstream

This is to disable/enable DW_DMAC hw during late suspend/early resume.
Since DMA is providing service to other clients (eg: SPI, HSUART),
we need to ensure DMA suspends after the clients and resume
before the clients are active.

Signed-off-by: Chew, Chiau Ee <chiau.ee.chew@intel.com>
Acked-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
Signed-off-by: Vinod Koul <vinod.koul@intel.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

2/10 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: Revert "serial/8250: Add support for HSUART controllers on Intel Baytrail platform"
Date: Mon, 11 Aug 2014 17:07:30 +0800

This reverts commit 25913af51446485123e40aa5c66da48f7dc64a0a.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

3/10 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: serial: 8250_pci: add support for Intel BayTrail
Date: Fri, 27 Sep 2013 10:52:59 +0300

commit b15e5691cc98b5e17db8ba8a433a4ac78efbf590 upstream

Intel BayTrail has two HS-UARTs with 64 byte fifo, support
for DMA and support for 16750 compatible Auto Flow Control.

Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

4/10 [
Author: Aaron Sierra
Email: asierra@xes-inc.com
Subject: serial: 8250_pci: more BayTrail error-free bauds
Date: Mon, 3 Mar 2014 19:54:29 -0600

commit 50825c57ab80ea44cae6bdcd79ead61e3e4e4e4c upstream

Support the following additional baud rates with 0% error:
	500000, 1500000, 2500000, 3500000

Signed-off-by: Aaron Sierra <asierra@xes-inc.com>
Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

5/10 [
Author: Aaron Sierra
Email: asierra@xes-inc.com
Subject: serial: 8250_pci: change BayTrail default uartclk
Date: Mon, 3 Mar 2014 19:54:36 -0600

commit 41d3f09913a930369a26616eedc02339d0455498 upstream

The Intel BayTrail HSUART power-on default reference clock is 44.2368 MHz,
but 73.728 MHz provides 0% error for additional "conventional" baud rates
above 460800 (e.g. 576000, 921600, and 1152000).

Signed-off-by: Aaron Sierra <asierra@xes-inc.com>
Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

6/10 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: serial: 8250: don't change the fifo trigger level when using dma
Date: Thu, 5 Sep 2013 17:34:52 +0300

commit 2797f6fb6727d8ac5127f88aee1fd059db0be24b upstream

DMA engines usually expect the fifo trigger level to be
aligned with the burst size. It should not be changed even
with small baud rates. This will fix an issue with
Designware DMA engine where the data can not be transferred
over UART with lower baud rates then 2400.

Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

7/10 [
Author: Lans Zhang
Email: jia.zhang@windriver.com
Subject: 8250_dw: Support all baudrates on baytrail
Date: Mon, 11 Aug 2014 17:22:07 +0800

commit c439c33d85e252d3b2b454ab7ba38b62d6e0a830 upstream

In the same manner as 8250_pci, 8250_dw needs some
baytrail specific quirks to be used. The reference
clock needs to be adjusted before divided in order
to have the minimum error rate on the baudrate.

The specific byt set termios function is stored in
the driver_data field of the acpi device id via the
dw8250_acpi_desc structure.

Remove the uartclk field which is no longer delivered
as driver data.

Signed-off-by: Loic Poulain <loic.poulain@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

8/10 [
Author: Alan Stern
Email: stern@rowland.harvard.edu
Subject: usb: gadget: don't fail when DMA isn't present
Date: Fri, 12 Jul 2013 11:06:21 -0400

commit 908b961326b2ecfbf494c9b2f206847d925f269d upstream

When CONFIG_HAS_DMA isn't enabled, the UDC core gets build errors:

drivers/built-in.o: In function `dma_set_coherent_mask':
include/linux/dma-mapping.h:93: undefined reference to `dma_supported'
include/linux/dma-mapping.h:93: undefined reference to `dma_supported'
drivers/built-in.o: In function `usb_gadget_unmap_request':
drivers/usb/gadget/udc-core.c:91: undefined reference to `dma_unmap_sg'
drivers/usb/gadget/udc-core.c:96: undefined reference to `dma_unmap_single'
drivers/built-in.o: In function `usb_gadget_map_request':
drivers/usb/gadget/udc-core.c:62: undefined reference to `dma_map_sg'
drivers/usb/gadget/udc-core.c:71: undefined reference to `dma_map_single'
drivers/usb/gadget/udc-core.c:74: undefined reference to `dma_mapping_error'

Prevent this by protecting the DMA API routines with preprocessor tests.

Signed-off-by: Alan Stern <stern@rowland.harvard.edu>
CC: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Alexander Shishkin <alexander.shishkin@linux.intel.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

9/10 [
Author: Felipe Balbi
Email: balbi@ti.com
Subject: usb: gadget: udc-core: move sysfs_notify() to a workqueue
Date: Wed, 17 Jul 2013 11:09:49 +0300

commit 5702f75375aa9ecf8ad3431aef3fe6ce8c8dbd15 upstream

usb_gadget_set_state() will call sysfs_notify()
which might sleep. Some users might want to call
usb_gadget_set_state() from the very IRQ handler
which actually changes the gadget state.

Instead of having every UDC driver add their own
workqueue for such a simple notification, we're
adding it generically to our struct usb_gadget,
so the details are hidden from all UDC drivers.

Acked-by: Alan Stern <stern@rowland.harvard.edu>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

10/10 [
Author: Adrian Hunter
Email: adrian.hunter@intel.com
Subject: mmc: sdhci: Allow for irq being shared
Date: Tue, 11 Mar 2014 10:09:36 +0200

commit 655bca7616bf6076d30b14d1478bca6807d49c45 upstream

If the SDHCI irq is shared with another device then the interrupt
handler can get called while SDHCI is runtime suspended.  That is
harmless but the warning message is not useful so remove it.  Also
returning IRQ_NONE is more appropriate.

Signed-off-by: Adrian Hunter <adrian.hunter@intel.com>
Signed-off-by: Chris Ball <chris@printf.net>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>