yocto/emgd: emgd 1.10 driver
1/3 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: yocto/emgd: emgd 1.10 driver
Date: Sun, 19 Feb 2012 16:12:30 -0600

The starting-point code that subsequent patches will modify.  This is
a straight copy of the code in the emgd 1.10 emgd driver, specifically
IEMGD_HEAD_Linux/common/drm/emgd_drm.tgz from
LIN_EMGD_1_10_RC_2209.tgz, the 'Linux Tar Ball' release downloaded
from http://edc.intel.com/Software/Downloads/EMGD/.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

2/3 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: yocto/emgd: initial build fixups
Date: Sun, 19 Feb 2012 16:16:38 -0600

Add emgd config option (DRM_EGD) and modify Makefiles for in-tree
builds.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

3/3 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: yocto/emgd: linux 3.2-related build fixups
Date: Sun, 19 Feb 2012 18:40:15 -0600

Fix build errors caused by changes to kernel interfaces introduced by
linux 3.2 such as:

error: 'THIS_MODULE' undeclared here (not in a function)

due to a missing THIS_MODULE definition which can be found in linux/export.h.

It also fixes a ream of errors like:

error: expected ')' before string constant

due to missing MODULE_PARM_DESC definition which can be found in
linux/moduleparam.h, included by linux/module.h, needed also for
MODULE_AUTHOR, etc.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>