fsl_imx6: Delete default y and add depends for HDMI configure
CQID: WIND00344719

drivers/mfd/mxc-hdmi-core.c:34:28: fatal error: asm/mach-types.h: No such file or directory
drivers/mfd/mxc-hdmi-core.c:36:24: fatal error: mach/clock.h: No such file or directory
drivers/mfd/mxc-hdmi-core.c:37:27: fatal error: mach/mxc_hdmi.h: No such file or directory
drivers/mmc/host/sdhci-esdhc.h:88:12: error: dereferencing pointer to incomplete type

"All the error is caused by the default y option of
CONFIG_MFD_MXC_HDMI", so make sure it is disabled by default for all
boards except imx6.

So add this patch to disable CONFIG_MFD_MXC_HDMI and add
CONFIG_MFD_MXC_HDMI=y for imx6 BSP.

1/1 [
Author: Zhong Hongbo
Email: hongbo.zhong@windriver.com
Subject: fsl_imx6: Delete default y and add depends for HDMI configure
Date: Tue, 8 Jan 2013 10:51:54 +0800

The HDMI driver be provided IMX6 serial chip.

Signed-off-by: Zhong Hongbo <hongbo.zhong@windriver.com>
]

Signed-off-by: Zhong Hongbo <hongbo.zhong@windriver.com>
Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>