SoundWire: fixes two compile error
Issue: LIN9-8466

1/1 [
Author: Wenlin Kang
Email: wenlin.kang@windriver.com
Subject: SoundWire: fixes two compile error
Date: Wed, 8 May 2019 14:06:31 +0800

This issue was introduced by commit b816e8ac3d6d3a497f2034dcd8dbbdc1340e6833
(SoundWire: Add support to register slaves on enumeration), it used function
kthread_init_work() and kthread_queue_work(), but the two only was exist
after upstream commit 3989144f863a(kthread: kthread worker API cleanup),
so change them to previous name.

This patch fixes the following error:

| drivers/sdw/sdw.c: In function 'sdw_register_master':
| drivers/sdw/sdw.c:1705:2: error: implicit declaration of function 'kthread_init_worker' [-Werror=implicit-function-declaration]
|   kthread_init_worker(&sdw_bus->kworker);
|   ^~~~~~~~~~~~~~~~~~~
| drivers/sdw/sdw.c:1714:2: error: implicit declaration of function 'kthread_init_work' [-Werror=implicit-function-declaration]
|   kthread_init_work(&sdw_bus->kwork, handle_slave_status);
|   ^~~~~~~~~~~~~~~~~
| drivers/sdw/sdw.c: In function 'sdw_master_update_slv_status':
| drivers/sdw/sdw.c:1774:2: error: implicit declaration of function 'kthread_queue_work' [-Werror=implicit-function-declaration]
|   kthread_queue_work(&bus->kworker, &bus->kwork);
|   ^~~~~~~~~~~~~~~~~~
| drivers/sdw/sdw.c: In function 'sdw_mstr_deprep_after_clk_start':
| drivers/sdw/sdw.c:3324:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
|    if (slave->driver && slave->driver->post_clk_stop_prep)
|    ^~
| drivers/sdw/sdw.c:3332:4: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
|     if (ret)
|     ^~

Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>
]
Signed-off-by: Yue Tao <Yue.Tao@windriver.com>