NXP: Integrate can patches
1/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: can: flexcan: add missing renamed feature into quirks
Date: Sun, 9 Oct 2016 15:08:53 +0800

Reference the commit f377bff02357(can: flexcan: rename feature into quirks).
The "feature" of struct flexcan_devtype_data has been renamed
to "quirks", here add the missed ones.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: can: flexcan: add missing renamed "cantxfg" to "mb"
Date: Sun, 9 Oct 2016 15:17:17 +0800

Reference the commit 1ba763d1d4bd (can: flexcan: give member of flexcan_priv
holding mailboxes a sensible name), the "cantxfg" of struct flexcan_regs has
been renamed to "mb", here add the missing ones.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

3/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: can: flexcan: add missing renamed base to regs
Date: Sun, 9 Oct 2016 15:30:07 +0800

Reference the commit 89af8746dea9(can: flexcan: use pointer to struct regs
instead of void pointer for mmio address space), the "base" of struct
flexcan_priv has been renamed to "regs", here add the missed ones.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

4/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: can: flexcan: fix the typo and missing variables
Date: Sun, 9 Oct 2016 15:59:20 +0800

To fix a typo and below errors:
drivers/net/can/flexcan.c:1338:3: error: 'core_is_little' undeclared (first use in this function)
|    core_is_little = false;
|    ^~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>