uptime: correct syntax error for CONFIG_UPTIME_LIMIT_KERNEL_REBOOT
Issue: LIN8-2308, LIN8-2321

1/3 [
Author: Mario Kleiner
Email: mario.kleiner.de@gmail.com
Subject: drm/qxl: Fix qxl_noop_get_vblank_counter()
Date: Mon, 4 May 2015 06:29:47 +0200

commit 337eb43c8d0000fef80b88e43fee7752a84afab2 upstream

This breaks under the vblank timestamp cleanup patch
by Daniel Vetter. Also it is pointless to return anything
but zero (or any other constant) if the function doesn't
actually query a hw vblank counter. The bogus return of
the current drm vblank counter via direct readout or via
drm_vblank_count() is found in many of the new kms drivers,
but it does exactly nothing different from returning any
arbitrary constant - it's a no operation.

Let's simply return 0 - Easy and fast.

Signed-off-by: Mario Kleiner <mario.kleiner.de@gmail.com>
Cc: Dave Airlie <airlied@redhat.com>
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
]

2/3 [
Author: Mauro Carvalho Chehab
Email: mchehab@osg.samsung.com
Subject: ov2659: Don't depend on subdev API
Date: Thu, 14 May 2015 19:27:45 -0300

commit fa8cb6444c3236d2bad7460bdfdb2685f82b7ee4 upstream

The subdev API is optional. No driver should depend on it.

Avoid compilation breakages if subdev API is not selected:

drivers/media/i2c/ov2659.c: In function ‘ov2659_get_fmt’:
drivers/media/i2c/ov2659.c:1054:3: error: implicit declaration of function ‘v4l2_subdev_get_try_format’ [-Werror=implicit-function-declaration]
   mf = v4l2_subdev_get_try_format(sd, cfg, 0);
   ^
drivers/media/i2c/ov2659.c:1054:6: warning: assignment makes pointer from integer without a cast
   mf = v4l2_subdev_get_try_format(sd, cfg, 0);
      ^
drivers/media/i2c/ov2659.c: In function ‘ov2659_set_fmt’:
drivers/media/i2c/ov2659.c:1129:6: warning: assignment makes pointer from integer without a cast
   mf = v4l2_subdev_get_try_format(sd, cfg, fmt->pad);
      ^
drivers/media/i2c/ov2659.c: In function ‘ov2659_open’:
drivers/media/i2c/ov2659.c:1264:38: error: ‘struct v4l2_subdev_fh’ has no member named ‘pad’
     v4l2_subdev_get_try_format(sd, fh->pad, 0);
                                      ^

Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>
Tested-by: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
]

3/3 [
Author: Jianchuan Wang
Email: jianchuan.wang@windriver.com
Subject: uptime: correct syntax error for CONFIG_UPTIME_LIMIT_KERNEL_REBOOT
Date: Wed, 13 Jan 2016 03:05:58 +0000

Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>