virtio-scsi.h: Add virtio_scsi_cmd_req_pi + VIRTIO_SCSI_F_T10_PI bits
1/3 [
Author: Nicholas Bellinger
Email: nab@linux-iscsi.org
Subject: virtio-scsi.h: Add virtio_scsi_cmd_req_pi + VIRTIO_SCSI_F_T10_PI bits
Date: Sun, 16 Mar 2014 14:51:35 -0700

commit 1b49dcf3d7c765ad18ca7167a0e441824eb1f7af upstream

This patch adds a virtio_scsi_cmd_req_pi header as recommened by
Paolo that contains pi_bytesout + pi_bytesin elements used for
signaling when protection information buffers (in bytes) are
expected to preceed the data payload buffers.

Also add new VIRTIO_SCSI_F_T10_PI feature bit to be used to signal
host support.

Cc: Paolo Bonzini <pbonzini@redhat.com>
Cc: Martin K. Petersen <martin.petersen@oracle.com>
Cc: Christoph Hellwig <hch@lst.de>
Cc: Hannes Reinecke <hare@suse.de>
Cc: Sagi Grimberg <sagig@dev.mellanox.co.il>
Cc: H. Peter Anvin <hpa@zytor.com>
Acked-by: Rusty Russell <rusty@rustcorp.com.au>
Acked-by: Michael S. Tsirkin <mst@redhat.com>
Signed-off-by: Nicholas Bellinger <nab@linux-iscsi.org>
[PG: fixes compile fail on missing VIRTIO_SCSI_F_T10_PI flag.]
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

2/3 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: vhost: fix compile fail due to reallocated acked_features field.
Date: Sat, 27 Sep 2014 11:13:53 -0400

The cherry pick of commit ea16c51433510f7f758382dec5b933fc0797f244
("vhost: move acked_features to VQs") didn't account for an extra
instance of that field in the older kernel, resulting in this:

drivers/vhost/scsi.c: In function ‘vhost_scsi_handle_vq’:
drivers/vhost/scsi.c:1038:14: error: ‘struct vhost_dev’ has no member named ‘acked_features’
   if (vs->dev.acked_features & VIRTIO_SCSI_F_T10_PI) {
              ^

Point it at the new location in the vq instead of in the dev.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

3/3 [
Author: Sagi Grimberg
Email: sagig@mellanox.com
Subject: Target/dif: Introduce protection-passthough-only mode
Date: Wed, 19 Feb 2014 17:50:17 +0200

commit b5b8e2989e3406798dbb88fbb4eaafbbf1a56f6a upstream.

Some transports (iSCSI/iSER/SRP/FC) support hardware INSERT/STRIP
capabilities while other transports like loopback/vhost-scsi need
perform this is software.

This patch allows fabrics using SCF_PASSTHROUGH_SG_TO_MEM_NOALLOC
to signal the early LUN scan handling case where PROTECT CDB bits
are set, but no fabric buffer has been provided.

For transports which use generic new command these buffers have yet
to be allocated.

Also this way, target may support protection information
against legacy initiators (writes are inserted and reads
are stripped).

(Only set prot_pto for loopback during early special case - nab)

Signed-off-by: Sagi Grimberg <sagig@mellanox.com>
Signed-off-by: Nicholas Bellinger <nab@linux-iscsi.org>
[PG: fixes compile fail from missing prot_pto field.]
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>