rt: fsl QMAN:Add QMAN_FQ_FLAG_FQSCB_NEED_SLP flag to qman_fq
1/3 [
Author: yhe
Email: yongli.he@windriver.com
Subject: fsl QMAN:Add QMAN_FQ_FLAG_FQSCB_NEED_SLP flag to qman_fq
Date: Wed, 19 Dec 2012 14:51:55 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context
at linux/kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 1430, name: modprobe
Call Trace:
[eae33db0] [c0007b10] show_stack+0x44/0x160 (unreliable)
[eae33de0] [c0034bb4] __might_sleep+0xe4/0x108
[eae33df0] [c0639d2c] rt_spin_lock+0x38/0xb4
[eae33e00] [c003a0cc] __wake_up+0x24/0x58
[eae33e20] [f955eee8] cb_fqs+0x54/0x70 [qman_tester]
[eae33e30] [c05637b8] qman_retire_fq+0x324/0x438
[eae33ea0] [f955f2f4] qman_test_high+0x1cc/0x2d8 [qman_tester]
[eae33ee0] [f955e018] test_init+0x14/0x2c [qman_tester]
[eae33ef0] [c0001d44] do_one_initcall+0x3c/0x1e0
[eae33f20] [c0085bb0] sys_init_module+0xf8/0x21c
[eae33f40] [c0010fc4] ret_from_syscall+0x0/0x4
    Exception: c00 at 0xff63564
    LR = 0x10003380

This is caused by the fqs callback function of qman_test_high
case involved a sleepable spinlock introduced by wake_up(), and the
callback is invoked from fqs_retire_fqs(), which implements a context
disabled preempt & irq.

The atomic context is used to protect key structure for qman driver.
While the callback of qman_test_high didn't touch such resource. So it
is free to invoke the callback outside the atomic context.

As result, the patch adds QMAN_FQ_FLAG_FQSCB_NEED_SLP  flag to qman_fq
structure. If the fqs callback function involves sleepable routine,
driver needs set the correspond bit when creating fq.

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

2/3 [
Author: Yongli He
Email: yongli.he@windriver.com
Subject: QMAN: QMAN preempt_rt call trace
Date: Thu, 16 Aug 2012 14:52:23 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 0, name: swapper
Call Trace:
[c000000000ae7540] [c00000000000a4a8] .show_stack+0x68/0x1b0 (unreliable)
[c000000000ae75f0] [c000000000039030] .__might_sleep+0x130/0x170
[c000000000ae7680] [c0000000007aec3c] .rt_spin_lock+0x3c/0xd0
[c000000000ae7700] [c0000000006a299c] .qman_create_fq+0xcc/0x830
[c000000000ae7800] [80000000002a90d4] .init_handler+0x84/0x180 [qman_tester]
[c000000000ae78d0] [c0000000000912c8] .generic_smp_call_function_single_interrupt+0x138/0x1d0
[c000000000ae7990] [c000000000023d94] .smp_message_recv+0x84/0x1b0
[c000000000ae7a20] [c00000000001bd64] .doorbell_exception+0x1a4/0x1c0
[c000000000ae7ad0] [c000000000017410] exc_doorbell_book3e+0x134/0x138
 --- Exception: 2071 at .book3e_idle+0x28/0x6c
    LR = .book3e_idle+0x28/0x6c
[c000000000ae7dc0] [c00000000000cb8c] .cpu_idle+0x10c/0x220 (unreliable)
[c000000000ae7e70] [c000000000001494] .rest_init+0xd4/0xc40
[c000000000ae7ef0] [c00000000095fcec] .start_kernel+0x460/0x480
[c000000000ae7f90] [c000000000000468] .start_here_common+0x1c/0x34

This is caused by lock fq_hash_table_lock in atomic context. atomic
context should be preserved so change spin lock to raw type.

Signed-off-by: Yongli He <yongli.he@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

3/3 [
Author: Bin Jiang
Email: bin.jiang@windriver.com
Subject: fsl QMAN: locking FQ introduces call trace in RT
Date: Tue, 29 Oct 2013 16:56:42 +0800

On preempt-rt kernel, during caam running, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context at kernel/rtmutex.c:659
in_atomic(): 1, irqs_disabled(): 1, pid: 1782, name: sh
Preemption disabled at:[<          (null)>]           (null)

CPU: 5 PID: 1782 Comm: sh Tainted: G        W    3.10.10-rt3-WR6.0.0.0_preempt-rt #1
Call Trace:
[c0000000f7a66280] [c00000000000b260] .show_stack+0x170/0x290 (unreliable)
[c0000000f7a66370] [c000000000942fe8] .dump_stack+0x28/0x3c
[c0000000f7a663e0] [c0000000000a60e0] .__might_sleep+0x160/0x1d0
[c0000000f7a66470] [c000000000936130] .rt_spin_lock+0x30/0x90
[c0000000f7a664f0] [c00000000078381c] .qman_init_fq+0x44c/0x840
[c0000000f7a665a0] [c00000000074e968] .create_caam_req_fq+0x158/0x220
[c0000000f7a66680] [c00000000074ebec] .caam_drv_ctx_init+0x1bc/0x3f0
[c0000000f7a66720] [c00000000075c0d4] .get_drv_ctx+0xd4/0x110
[c0000000f7a667d0] [c00000000075d114] .aead_givencrypt+0x84/0xad0
[c0000000f7a668e0] [80000000001703f8] .esp_output+0x3d8/0x6ac [esp4]
[c0000000f7a66a00] [c0000000008a0f78] .xfrm_output_resume+0x1e8/0x4b0
[c0000000f7a66aa0] [c000000000891e6c] .xfrm4_output_finish+0x4c/0xb0

CAAM creates session REQ FQ and requires to lock FQ. The above call trace
is caused by lock FQ in a context disabled preempt & irq.
Mostly FQLOCK is a dummy lock and it's only useful for CAAM and PME to
handle FQ. Most operations between the lock and unlock are to assign
values. So change spin lock to raw type and won't introduce a latency
spike.

Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>