BSP: NEW TI 66AK2Hxx (Cortex-A15) [aka: Keystone2, Hawking EVM)
CQID: WIND00388030

1/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: 7451/1: arch timer: implement read_current_timer and get_cycles
Date: Mon, 15 Jul 2013 16:26:59 +0800

Commit 923df96b9f31b7d08d8438ff9677326d9537accf upstream

This patch implements read_current_timer using the architected timers
when they are selected via CONFIG_ARM_ARCH_TIMER. If they are detected
not to be usable at runtime, we return -ENXIO to the caller.

Furthermore, if read_current_timer is exported then we can implement
get_cycles in terms of it for use as both an entropy source and for
implementing __udelay and friends.

Tested-by: Shinya Kuribayashi <shinya.kuribayashi.px@renesas.com>
Reviewed-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

2/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: 7452/1: delay: allow timer-based delay implementation to be selected
Date: Mon, 15 Jul 2013 16:53:40 +0800

Commit d0a533b18235d36206b9b422efadb7cee444dfdb upstream

This patch allows a timer-based delay implementation to be selected by
switching the delay routines over to use get_cycles, which is
implemented in terms of read_current_timer. This further allows us to
skip the loop calibration and have a consistent delay function in the
face of core frequency scaling.

To avoid the pain of dealing with memory-mapped counters, this
implementation uses the co-processor interface to the architected timers
when they are available. The previous loop-based implementation is
kept around for CPUs without the architected timers and we retain both
the maximum delay (2ms) and the corresponding conversion factors for
determining the number of loops required for a given interval. Since the
indirection of the timer routines will only work when called from C,
the sa1100 sleep routines are modified to branch to the loop-based delay
functions directly.

Tested-by: Shinya Kuribayashi <shinya.kuribayashi.px@renesas.com>
Reviewed-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

3/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: 7538/1: delay: add registration mechanism for delay timer sources
Date: Mon, 15 Jul 2013 17:21:34 +0800

Commit 56942fec06efa0e17df0f4c3b438332c923b9014 upstream

The current timer-based delay loop relies on the architected timer to
initiate the switch away from the polling-based implementation. This is
unfortunate for platforms without the architected timers but with a
suitable delay source (that is, constant frequency, always powered-up
and ticking as long as the CPUs are online).

This patch introduces a registration mechanism for the delay timer
(which provides an unconditional read_current_timer implementation) and
updates the architected timer code to use the new interface.

Reviewed-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Jonathan Austin <jonathan.austin@arm.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

4/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: export default read_current_timer
Date: Mon, 15 Jul 2013 17:24:42 +0800

Commit f3accb122f2c758494a6db3b9e9a8cd62aafcf83 upstream

read_current_timer is used by get_cycles since "ARM: 7538/1: delay:
add registration mechanism for delay timer sources", and get_cycles
can be used by device drivers in loadable modules, so it has to
be exported.

Without this patch, building imote2_defconfig fails with

ERROR: "read_current_timer" [crypto/tcrypt.ko] undefined!

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Stephen Boyd <sboyd@codeaurora.org>
Cc: Jonathan Austin <jonathan.austin@arm.com>
Cc: Will Deacon <will.deacon@arm.com>
Cc: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

5/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: add mechanism for late code patching
Date: Tue, 16 Jul 2013 11:12:03 +0800

Commit 9e8fba771f3bc6ecf5989b11262c4b96438be68a from arago tree
git://arago-project.org/git/projects/linux-keystone.git releases/03.00.00.11/master

The original phys_to_virt/virt_to_phys patching implementation relied on early
patching prior to MMU initialization.  On PAE systems running out of >4G
address space, this would have entailed an additional round of patching after
switching over to the high address space.

The approach implemented here conceptually extends the original PHYS_OFFSET
patching implementation with the introduction of "early" patch stubs.  Early
patch code is required to be functional out of the box, even before the patch
is applied.  This is implemented by inserting functional (but inefficient)
load code into the .runtime.patch.code init section.  Having functional code
out of the box then allows us to defer the init time patch application until
later in the init sequence.

In addition to fitting better with our need for physical address-space
switch-over, this implementation should be somewhat more extensible by virtue
of its more readable (and hackable) C implementation.  This should prove
useful for other similar init time specialization needs, especially in light
of our multi-platform kernel initiative.

This code has been boot tested in both ARM and Thumb-2 modes on an ARMv7
(Cortex-A8) device.

Note: the obtuse use of stringified symbols in patch_stub() and
early_patch_stub() is intentional.  Theoretically this should have been
accomplished with formal operands passed into the asm block, but this requires
the use of the 'c' modifier for instantiating the long (e.g. .long %c0).
However, the 'c' modifier has been found to ICE certain versions of GCC, and
therefore we resort to stringified symbols here.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Reviewed-by: Nicolas Pitre <nico@linaro.org>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

6/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: mm: use pteval_t to represent page protection values
Date: Tue, 16 Jul 2013 13:19:59 +0800

Commit 864aa04cd02979c2c755cb28b5f4fe56039171c0 upstream

When updating the page protection map after calculating the user_pgprot
value, the base protection map is temporarily stored in an unsigned long
type, causing truncation of the protection bits when LPAE is enabled.
This effectively means that calls to mprotect() will corrupt the upper
page attributes, clearing the XN bit unconditionally.

This patch uses pteval_t to store the intermediate protection values,
preserving the upper bits for 64-bit descriptors.

Cc: stable@vger.kernel.org
Acked-by: Nicolas Pitre <nico@linaro.org>
Acked-by: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

7/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use phys_addr_t in alloc_init_pud()
Date: Tue, 16 Jul 2013 13:23:28 +0800

Commit 20d6956d8cd2452cec0889ff040f18afc03c2e6b upstream

This patch fixes the alloc_init_pud() function to use phys_addr_t instead of
unsigned long when passing in the phys argument.

This is an extension to commit 97092e0c56830457af0639f6bd904537a150ea4a (ARM:
pgtable: use phys_addr_t for physical addresses), which applied similar changes
elsewhere in the ARM memory management code.

Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Acked-by: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

8/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: mm: use physical addresses in highmem sanity checks
Date: Tue, 16 Jul 2013 13:30:35 +0800

Commit 82f667046ec895552caf2f7a4c6841c530bfc215 upstream

This patch modifies the highmem sanity checking code to use physical addresses
instead.  This change eliminates the wrap-around problems associated with the
original virtual address based checks, and this simplifies the code a bit.

The one constraint imposed here is that low physical memory must be mapped in
a monotonically increasing fashion if there are multiple banks of memory,
i.e., x < y must => pa(x) < pa(y).

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

9/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: mm: cleanup checks for membank overlap with vmalloc area
Date: Tue, 16 Jul 2013 13:33:33 +0800

Commit adf2e9fda34c1cfff2ee4e47078b1e142adb2c30 upstream

On Keystone platforms, physical memory is entirely outside the 32-bit
addressible range.  Therefore, the (bank->start > ULONG_MAX) check below marks
the entire system memory as highmem, and this causes unpleasentness all over.

This patch eliminates the extra bank start check (against ULONG_MAX) by
checking bank->start against the physical address corresponding to vmalloc_min
instead.

In the process, this patch also cleans up parts of the highmem sanity check
code by removing what has now become a redundant check for banks that entirely
overlap with the vmalloc range.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

10/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: mm: clean up membank size limit checks
Date: Tue, 16 Jul 2013 13:37:15 +0800

Commit 28d4bf7a2929c5e525171d249e12662e21130ec3 upstream

This patch cleans up the highmem sanity check code by simplifying the range
checks with a pre-calculated size_limit.  This patch should otherwise have no
functional impact on behavior.

This patch also removes a redundant (bank->start < vmalloc_limit) check, since
this is already covered by the !highmem condition.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

11/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use phys_addr_t in switch_mm()
Date: Tue, 16 Jul 2013 14:23:26 +0800

Commit 13f659b0f363114282679d06094337c5efa12fa8 upstream

This patch modifies the switch_mm() processor functions to use phys_addr_t.
On LPAE systems, we now honor the upper 32-bits of the physical address that
is being passed in, and program these into TTBR as expected.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Reviewed-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
[will: fixed up conflict in 3-level switch_mm with big-endian changes]
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

12/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: factor out T1SZ and TTBR1 computations
Date: Tue, 16 Jul 2013 14:28:21 +0800

Commit a7fbc0d62a4d46e642af889e7288fede5078bc46 upstream

This patch moves the TTBR1 offset calculation and the T1SZ calculation out
of the TTB setup assembly code.  This should not affect functionality in
any way, but improves code readability as well as readability of subsequent
patches in this series.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

13/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: accomodate >32-bit addresses for page table base
Date: Tue, 16 Jul 2013 14:32:59 +0800

Commit 4756dcbfd37819a8359d3c69a22be2ee41666d0f upstream

This patch redefines the early boot time use of the R4 register to steal a few
low order bits (ARCH_PGD_SHIFT bits) on LPAE systems.  This allows for up to
38-bit physical addresses.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

14/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use 64-bit accessors for TTBR registers
Date: Tue, 16 Jul 2013 14:57:46 +0800

Commit 1fc84ae84b5153e32a4b6ace507f9663e10b0cb2 upstream

This patch adds TTBR accessor macros, and modifies cpu_get_pgd() and
the LPAE version of cpu_set_reserved_ttbr0() to use these instead.

In the process, we also fix these functions to correctly handle cases
where the physical address lies beyond the 4G limit of 32-bit addressing.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

15/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use phys_addr_t in free_memmap()
Date: Tue, 16 Jul 2013 15:17:16 +0800

Commit 56bc628666b39dc8cb395c7686d8c032efd731f4 upstream

The free_memmap() was mistakenly using unsigned long type to represent
physical addresses.  This breaks on PAE systems where memory could be placed
above the 32-bit addressible limit.

This patch fixes this function to properly use phys_addr_t instead.

Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

16/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use phys_addr_t for initrd location
Date: Tue, 16 Jul 2013 15:20:01 +0800

Commit de22cc6e33449d8d6fb339619e32138ea4fcc2a4 upstream

This patch fixes the initrd setup code to use phys_addr_t instead of assuming
32-bit addressing.  Without this we cannot boot on systems where initrd is
located above the 4G physical address limit.

Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Acked-by: Nicolas Pitre <nico@linaro.org>
Acked-by: Catalin Marinas <catalin.marinas@arm.com>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

17/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: /dev/mem: use phys_addr_t for physical addresses
Date: Tue, 16 Jul 2013 15:25:31 +0800

Commit 7e6735c3578e76c270a2797225a4214176ba13ef upstream

This patch fixes the /dev/mem driver to use phys_addr_t for physical
addresses.  This is required on PAE systems, especially those that run
entirely out of >4G physical memory space.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

18/18 [
Author: Guoqing Jiang
Email: Guoqing.Jiang@windriver.com
Subject: ARM: LPAE: use signed arithmetic for mask definitions
Date: Tue, 16 Jul 2013 15:32:07 +0800

Commit 926edcc747e2efb3c9add7ed4dbc4e7a3a959d02 upstream

This patch applies to PAGE_MASK, PMD_MASK, and PGDIR_MASK, where forcing
unsigned long math truncates the mask at the 32-bits.  This clearly does bad
things on PAE systems.

This patch fixes this problem by defining these masks as signed quantities.
We then rely on sign extension to do the right thing.

Signed-off-by: Cyril Chemparathy <cyril@ti.com>
Signed-off-by: Vitaly Andrianov <vitalya@ti.com>
Reviewed-by: Nicolas Pitre <nico@linaro.org>
Reviewed-by: Catalin Marinas <catalin.marinas@arm.com>
Tested-by: Santosh Shilimkar <santosh.shilimkar@ti.com>
Tested-by: Subash Patel <subash.rp@samsung.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Guoqing Jiang <Guoqing.Jiang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>