BSP xilinx_zynq add support of zc702 rev 1.1
JIRAID: US29351

1/7 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: net: xilinx_emacps: upgrade ethernet driver to 3.10
Date: Thu, 27 Feb 2014 15:56:24 +0800

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/852ddaa8975b9e2d22d10c1a0fed6cd7010db3e4

Because the original driver is not stable and mature, upgrade the driver
to 3.10. Copy the corresponding file from above commit.

And fix following compiling error:
error: 'struct net_local' has no member named 'compare'

Also update the dtb file to make ethernet driver work properly.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

2/7 [
Author: Punnaiah Choudary Kalluri
Email: punnaia@xilinx.com
Subject: net: xilinx_emacps: Fix wrong udp checksum offload calculation
Date: Thu, 17 Oct 2013 09:57:07 +0530

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/af2c4ebb7ac56cc5a55cbe55db05470d6e91cbe2

When the UDP checksum is offloaded, if the usb header checksum field is
non zero then the udp checksum calculated by the hw is wrong. So, the
driver should ensure that the checksum field should be zero.

Signed-off-by: Punnaiah Choudary Kalluri <punnaia@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

3/7 [
Author: Punnaiah Choudary Kalluri
Email: punnaiah.choudary.kalluri@xilinx.com
Subject: net: xilinx_emacps: Fix race condition occurs during link up/down
Date: Thu, 24 Oct 2013 13:04:53 +0530

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/49028589bcd9c7d2657b3b6fec82d216a9c9f5c6

Enable the NAPI before enabling the interrupts and Rx engine.

Signed-off-by: Punnaiah Choudary Kalluri <punnaia@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

4/7 [
Author: Punnaiah Choudary Kalluri
Email: punnaiah.choudary.kalluri@xilinx.com
Subject: net: xilinx_emacps: Apply the spinlock to the required critical section
Date: Tue, 3 Dec 2013 20:21:02 +0530

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/b4e45a514b7cb5e4a3bfa42d1fccc8d7ca8e28e7

Applied the spinlock to the required critical sections in xemacps_tx_poll
and xemacps_start_xmit function. Removed the barrier instructions that exist
just before the spinlock calls and the places where the usage of barrier
instrcution is not relevant.

Signed-off-by: Punnaiah Choudary Kalluri <punnaia@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

5/7 [
Author: Punnaiah Choudary Kalluri
Email: punnaiah.choudary.kalluri@xilinx.com
Subject: net: xilinx_emacps: Simplified the cleanup logic for fragmented packets
Date: Tue, 3 Dec 2013 20:21:03 +0530

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/26f6ade0bfeccda228e29698433a4a1df1e23d1f

The following changes simplify the fragmented packet and buffer descriptor
cleanup process by eliminating the redundant while loop

Signed-off-by: Punnaiah Choudary Kalluri <punnaia@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

6/7 [
Author: Punnaiah Choudary Kalluri
Email: punnaiah.choudary.kalluri@xilinx.com
Subject: net: xilinx_emacps: Disable napi when xemacps_mii_probe fails
Date: Tue, 10 Dec 2013 11:02:40 +0530

The patch based on commit:
https://github.com/Xilinx/linux-xlnx/commit/379b01ab003aa8e2306d56ce6e2b7bcf140867fe

In xemacps_open(), call napi_disable() when the xemacps_mii_probe() fails.
This change is needed to undo the napi_enable() which called before the
xemacps_mii_probe().

This fix is needed because of below commit
"net: xilinx_emacps: Fix race condition occurs during link up/down"
(sha1: 49028589bcd9c7d2657b3b6fec82d216a9c9f5c6)

Reported-by: Soren Brinkmann <soren.brinkmann@xilinx.com>
Signed-off-by: Punnaiah Choudary Kalluri <punnaia@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

7/7 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: net: xilinx_emacps: Enable reception of ethernet frames greater than 1536 bytes
Date: Thu, 27 Feb 2014 17:36:48 +0800

All Ethernet frames greater than 1518 bytes get discarded which consequently
caused the low throughput. This is the case when the maximum
MTU of 1500 is used and the payload gets encapsulated in an VLAN frame.

Signed-off-by: Thomas Fekl <thomas.fekl@alcatel-lucent.com>
Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>