lttng: Move nmi_return pv_ops out of lguest_pages
CQID: WIND00342541

1/1 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: lttng: Move nmi_return pv_ops out of lguest_pages
Date: Thu, 28 Jun 2012 12:51:11 -0700

Fix below compile error when lguest is enabled:
error: invalid use of undefined type 'struct pv_cpu_ops'

And, move both x86_32 and x86_64 nmi_return pv_ops to common
asm-offsets.c since they have the same definition.

Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>