ARM: oprofile: move arm_backtrace out of #ifdef CONFIG_HW_PERF_EVENTS
CQID: WIND00310627

1/1 [
Author: Hui Wang
Email: Hui.Wang@windriver.com
Subject: ARM: oprofile: move arm_backtrace out of #ifdef CONFIG_HW_PERF_EVENTS
Date: Tue, 11 Oct 2011 09:46:10 +0800

arm_backtrace() function is both needed for oprofile running in
hardware performance event mode and timer mode. To make this available
to both modes we move arm_backtrace() and other sub functions needed
by arm_backtrace() out of #ifdef CONFIG_HW_PERF_EVENTS. Otherwise when
we enable oprofile in the linux kernel on an ARM platform which
doesn't support hardware performance event, we will meet a build error
like this:

common.c: In function 'oprofile_arch_init':
common.c:437: error: 'arm_backtrace' undeclared (first ...)
common.c:437: error: (Each undeclared identifier is reported only once

Based on the upstream commit: d14dd7e2

Signed-off-by: Hui Wang <Hui.Wang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>