arm64: barriers: fix smp_load_acquire to work with const arguments
Issue: LIN7-9071

1/2 [
Author: Andre Przywara
Email: andre.przywara@arm.com
Subject: arm64: add missing data types in smp_load_acquire/smp_store_release
Date: Mon, 20 Apr 2015 11:14:19 +0100

commit  878a84d5a8a18a4ab241d40cebb791d6aedf5605 upstream

Commit 8053871d0f7f ("smp: Fix smp_call_function_single_async()
locking") introduced a call to smp_load_acquire() with a u16 argument,
but we only cared about u32 and u64 types in that function so far.
This resulted in a compiler warning fortunately, pointing at an
uninitialized use. Due to the implementation structure the compiler
misses that bug in the smp_store_release(), though.
Add the u16 and u8 variants using ldarh/stlrh and ldarb/stlrb,
respectively. Together with the compiletime_assert_atomic_type() check
this should cover all cases now.

Acked-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Andre Przywara <andre.przywara@arm.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Liu Haitao <haitao.liu@windriver.com>
]

2/2 [
Author: Will Deacon
Email: will.deacon@arm.com
Subject: arm64: barriers: fix smp_load_acquire to work with const arguments
Date: Wed, 18 Nov 2015 10:13:08 +0000

commit  c139aa60c1007429335131167a0ca181e38c5668 upstream

"""
    This error is introduced by commit  "fe02c883d5a3880d32d9465aecc2e8bf75f12d04"
    When build image for arm64, it will cause the following error.
    This issue has been solved in community. So we just integrate this patch
    into our system.
"""

A newly introduced function in include/net/sock.h passes a const
argument to smp_load_acquire:

  static inline int sk_state_load(const struct sock *sk)
  {
	return smp_load_acquire(&sk->sk_state);
  }

This cause an allmodconfig build failure, since our underlying
load-acquire implementation does not handle const types correctly:

  include/net/sock.h: In function 'sk_state_load':
  ./arch/arm64/include/asm/barrier.h:71:3: error: read-only variable '___p1' used as 'asm' output
     asm volatile ("ldarb %w0, %1"    \

This patch fixes the problem by reusing the trick in READ_ONCE that
loads via a non-const member of an anonymous union. This has the
advantage of allowing us to use smp_load_acquire on packed structures
(e.g. arch_spinlock_t) as well as primitive types.

Cc: Arnd Bergmann <arnd@arndb.de>
Cc: David Daney <david.daney@cavium.com>
Cc: Eric Dumazet <eric.dumazet@gmail.com>
Reported-by: Arnd Bergmann <arnd@arndb.de>
Reported-by: David Daney <david.daney@cavium.com>
Signed-off-by: Will Deacon <will.deacon@arm.com>
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Liu Haitao <haitao.liu@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>