lttng: Use task_lock and not rcu to protect nsproxy for lttng
Issue: LIN5-19341

1/1 [
Author: Li Wang
Email: li.wang@windriver.com
Subject: lttng: Use task_lock and not rcu to protect nsproxy for lttng
Date: Fri, 29 Aug 2014 16:14:09 +0800

commit 728dba3a [namespaces: Use task_lock and not rcu to protect nsproxy]
removes the rcu lock from nsproxy.

This causes the following lttng build failure:

linux/drivers/staging/lttng2/lttng-statedump-impl.c:
In function 'lttng_statedump_process_ns':
linux/drivers/staging/lttng2/lttng-statedump-impl.c:288:2:
error: implicit declaration of function 'task_nsproxy' [-Werror=implicit-function-declaration]

So we convert lttng2 to the new locking scheme to fix the error.

Signed-off-by: Li Wang <li.wang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>