fsl/uio: change UIO_FSL_SRAM kernel option from bool to tristate
Rally: US82698

1/4 [
Author: Yongli He
Email: yongli.he@windriver.com
Subject: QMAN: QMAN preempt_rt call trace
Date: Thu, 16 Aug 2012 14:52:23 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 0, name: swapper
Call Trace:
[c000000000ae7540] [c00000000000a4a8] .show_stack+0x68/0x1b0 (unreliable)
[c000000000ae75f0] [c000000000039030] .__might_sleep+0x130/0x170
[c000000000ae7680] [c0000000007aec3c] .rt_spin_lock+0x3c/0xd0
[c000000000ae7700] [c0000000006a299c] .qman_create_fq+0xcc/0x830
[c000000000ae7800] [80000000002a90d4] .init_handler+0x84/0x180 [qman_tester]
[c000000000ae78d0] [c0000000000912c8] .generic_smp_call_function_single_interrupt+0x138/0x1d0
[c000000000ae7990] [c000000000023d94] .smp_message_recv+0x84/0x1b0
[c000000000ae7a20] [c00000000001bd64] .doorbell_exception+0x1a4/0x1c0
[c000000000ae7ad0] [c000000000017410] exc_doorbell_book3e+0x134/0x138
 --- Exception: 2071 at .book3e_idle+0x28/0x6c
    LR = .book3e_idle+0x28/0x6c
[c000000000ae7dc0] [c00000000000cb8c] .cpu_idle+0x10c/0x220 (unreliable)
[c000000000ae7e70] [c000000000001494] .rest_init+0xd4/0xc40
[c000000000ae7ef0] [c00000000095fcec] .start_kernel+0x460/0x480
[c000000000ae7f90] [c000000000000468] .start_here_common+0x1c/0x34

This is caused by lock fq_hash_table_lock in atomic context. atomic
context should be preserved so change spin lock to raw type.

Signed-off-by: Yongli He <yongli.he@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

2/4 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: fsl_fman: add A007273 support for T2080/T1024
Date: Fri, 20 Nov 2015 07:37:16 +0000

Workaround for A007273 has 3 steps: first re-enable all disabled MAC clocks
through the DCFG_CCSR_DEVDISR2 register, then issuing an FMAN soft reset, at
 last re-disable the MAC clocks after the FMAN soft reset is done. When access
DCFG_CCSR_DEVDISR2 register, we need to call function "Fm_GetCcsrGutsReg" to
get DCFG_CCSR_DEVDISR2's virtual address base. But now T2080/T1024 can't get
virual address base because they are not in match table. It will cause that
on T2080/T1024 boards only reset but no save/restore operations for
DCFG_CCSR_DEVDISR2, the workaround become invalid. So add T2080/T1024 into
match tables.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

3/4 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: fsl/Rman: change rman kernel option from bool to tristate
Date: Thu, 3 Dec 2015 09:09:41 +0000

Because rman depends on UIO subsystem, when UIO is built as
kernel module, rman should be changed to module state too.
So change rman kernel option from bool to tristate or it will
occurr building error as below when CONFIG_UIO=m:

drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `fsl_rman_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:337: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `rman_ib_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:169: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `rman_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:144: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `fsl_rman_ib_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

4/4 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: fsl/uio: change UIO_FSL_SRAM kernel option from bool to tristate
Date: Thu, 3 Dec 2015 09:51:56 +0000

Because UIO_FSL_SRAM depends on UIO subsystem, when UIO is built as
kernel module, L2CACHE should be changed to module state too.
So change L2CACHE kernel option from bool to tristate.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>