net: ethernet: xilinx: bug fix for missing phydev var
Issue: LIN9-6366

1/1 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: net: ethernet: xilinx: bug fix for missing phydev var
Date: Fri, 16 Feb 2018 21:06:51 +0200

Fixes the following compilation error when CONFIG_XILINX_AXI_EMAC is
enabled:
...
drivers/net/ethernet/xilinx/xilinx_axienet_main.c:1513:6: error:
phydev' undeclared (first use in this function)
|   if (phydev)
...

This fix is specific to the Windriver xilinx-zynq kernel (the compilation
issue was introduced by commit 0031e853a0496a96fc30c080c63862961ecced34).

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>