fsl-t2xxx: Fix compile errors when disabling CONFIG_SMP
Issue: LIN6-9856

1/2 [
Author: Li Wang
Email: li.wang@windriver.com
Subject: powerpc/rcpm: fix compile error with non-SMP mode
Date: Thu, 27 Aug 2015 11:01:58 +0800

the patch back port from:
wrl7 commit a8e71da8a4e351d09511776e50781551c36920bb

Add asm/smp.h, and only compile the cluster related code
when CPU hotplug is enabled.

Change-Id: I264ff297ca1ee29bf8c477b09bce98eeb27140ee
Signed-off-by: Chenhui Zhao <chenhui.zhao@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/23752
Reviewed-by: Yang Li <LeoLi@freescale.com>
Reviewed-by: Zhuoyu Zhang <Zhuoyu.Zhang@freescale.com>
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Matthew Weigel <Matthew.Weigel@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Li Wang <li.wang@windriver.com>
]

2/2 [
Author: Li Wang
Email: li.wang@windriver.com
Subject: fsl-t2xxx: Fix compile errors when disabling CONFIG_SMP
Date: Thu, 27 Aug 2015 11:03:43 +0800

the patch back port from:
wrl7 commit 2f38d3c92a586eb1e8ab579ff77f82c22ddb0cf9

There are some compile errors when disabling CONFIG_SMP
- boot_cpuid isn't declared in the ics.c,it hints:

    | arch/powerpc/platforms/wsp/ics.c: In function 'wsp_ics_set_default_server':
    | arch/powerpc/platforms/wsp/ics.c:655:23: error: 'boot_cpuid' undeclared (first use in this function)
    |   np = of_get_cpu_node(boot_cpuid, NULL);
    |                        ^
    | arch/powerpc/platforms/wsp/ics.c:655:23: note: each undeclared identifier is reported only once for each function it appears in
    | arch/powerpc/platforms/wsp/ics.c:658:2: error: implicit declaration of function 'get_hard_smp_processor_id' [-Werror=implicit-function-declaration]
    |   hwid = get_hard_smp_processor_id(boot_cpuid);

- nr_cpu_ids isn't defined in the exceptions-64e.S/head_64.S, it hints:

    | arch/powerpc/kernel/head_64.S:231: undefined reference to `nr_cpu_ids'

Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>
Signed-off-by: Li Wang <li.wang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>