stm-spear13xx: new bsp on standard branch
CQID: WIND00325677

1/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add spear13xx plat files to new diretory arch/arm/plat-spear13xx
Date: Mon, 6 Aug 2012 18:01:32 +0800

Copy spear13xx plat files to a new directory arch/arm/plat-spear13xx/
from arch/arm/plat-spear/ of st git tree:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Note: this also corresponds to the commits bf976b51..966ae210
      on arch/arm/plat-spear/ at st git tree.

And remove unrelated files: pl080.c, pm.c and sleep.S. Also modify
Makefile to remove compiling of the files.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

2/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add mach-spear13xx to arch/arm/
Date: Tue, 22 May 2012 18:08:57 +0800

Copy arch/arm/mach-spear13xx directory directly from st git tree based on
following commit:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Note: this also corresponds to the commits 151c5a0b..966ae210
      on arch/arm/mach-spear13xx/ at st git tree.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

3/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: remove unused machine files in arch/arm/mach-spear13xx
Date: Tue, 22 May 2012 18:11:21 +0800

There are some machines unsupported for spear13xx BSP, so remove
them.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

4/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add machine definitions in mach-types.
Date: Tue, 22 May 2012 18:17:23 +0800

Add spear1310_evb, spear1310_reva_evb and spear1340_evb definitions
in mach-types.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

5/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: update Kconfig and Makefile to support spear13xx machines
Date: Tue, 22 May 2012 17:51:58 +0800

Update Kconfig and Makefile to include plat-spear13xx
and mach-spear13xx directories to build.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

6/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: copy stmmac driver from st git tree
Date: Tue, 29 May 2012 16:09:22 +0800

Copy stmmac driver from st git tree:

git://git.stlinux.com/spear/linux-2.6.git tag lsp-3.2.5
commit 6dfa4a5b lsp-3.2.5: Marking release lsp-3.2.5

Note:
1. This also corresponds to the commits 47dd7a54..55ceaf0c
on drivers/net/stmmac/ at st git tree.

2. The stmmac driver from next-3.3, and mainline 3.4 triggers a loop
interrupt and error message [dwmac_dma_interrupt: unexpected status 086e0000].
So the driver is imported from the lsp-3.2.5 tag to avoid this issue.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

7/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: modify stmmac_main.c to avoid compile error
Date: Thu, 23 Aug 2012 17:03:49 +0800

According to following upstream commits to modify stmmac_main.c:

 - commit f722380d stmmac: convert to SKB paged frag API.
   Change from dma_map_page to skb_frag_dma_map.

 - commit afc4b13d net: remove use of ndo_set_multicast_list in drivers
   Replace it by ndo_set_rx_mode.

 - commit 7890a5b9 vlan: kill ndo_vlan_rx_register
   So remove ndo_vlan_rx_register from stmmac driver.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

8/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: modify stmmac_ethtool.c to avoid compile error
Date: Thu, 23 Aug 2012 17:08:41 +0800

According to following upstream commit to modify stmmac_ethtool.c:

 - commit bc5787c6 net: remove legacy ethtool ops
   remove discrete offload setting callback handling.

 - And add include file: linux/interrupt.h

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

9/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: modify mach files to make stmmac driver work fine
Date: Thu, 23 Aug 2012 17:20:22 +0800

Modify spear13xx mach files based on st git tree:

git://git.stlinux.com/spear/linux-2.6.git tag lsp-3.2.5
commit 6dfa4a5b lsp-3.2.5: Marking release lsp-3.2.5

changes according to above git tree:

 - add plat_stmmacphy_data platform data.
 - replace value of plat_stmmacenet_data with the value in above git tree.
 - replace plat_stmmacenet_data with plat_stmmacphy_data

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

10/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add DB9000 LCD driver
Date: Tue, 29 May 2012 16:10:04 +0800

Copy DB9000 LCD driver from st git tree:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Note:
1. This also corresponds to the commits d99ce66f..0bb8e759
on drivers/video/db9000fb.c at st git tree.

2. This also corresponds to the commits 5752f257..d1699012
on include/video/db9000fb.h at st git tree.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

11/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add spear sound driver
Date: Thu, 21 Jun 2012 13:48:15 +0800

Copy spear sound driver from st git tree:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Note:
1. This also corresponds to the commits d0f68e43..9e8da9ac
on sound/soc/spear/ at st git tree.

2. This also corresponds to the commits d0f68e43..bd49b8e4
on sound/soc/codecs/sta529.[ch] at st git tree.

3. This also corresponds to the commits 4b5349e5..d0f68e43
on sound/soc/codecs/spdif_receiver.c at st git tree.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

12/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: ata/ahci_platform: Add support for enabling/disabling clock.
Date: Thu, 28 Jun 2012 16:54:18 +0800

Imported from git://git.stlinux.com/spear/linux-2.6.git
commit 9e5f1a4f8d6146bb99be94fdddeef1ee84e894e1

On many architectures, drivers are supposed to enable/disable functional clock
of device. This patch adds support for clock enabling/disabling in
ahci_platform.c.

Signed-off-by: Viresh Kumar <viresh.kumar@st.com>
Integrated-by: Liming Wang <liming.wang@windriver.com>
]

13/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: copy fsmc nand driver from st tree.
Date: Mon, 2 Jul 2012 15:20:03 +0800

Copy fsmc nand driver from st git tree:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Note: this also corresponds to the commits 6c009ab8..17836d58
      on the changed files at st git tree.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

14/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: get rid of NO_IRQ initializers
Date: Tue, 3 Jul 2012 10:51:10 +0800

commit 8395e9dd ARM: amba: spear: get rid of NO_IRQ initializers

NO_IRQ has been dropped from kernel, so remove all NO_IRQ from code.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

15/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: convert to twd_local_timer_register() interface
Date: Tue, 3 Jul 2012 11:12:04 +0800

commit 81e46f7b ARM: smp_twd: add runtime registration support

Converts localtimer to common smp_twd runtime interface.

So convert to twd_local_timer_register() interface for the spear13xx
platforms and in the meantime remove the old compile-time support.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

16/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: fix missing include file system_misc.h
Date: Tue, 3 Jul 2012 11:13:04 +0800

To fix following compile error:
...
In function 'spear_pm_prepare':
error: implicit declaration of function 'disable_hlt'
error: implicit declaration of function 'enable_hlt'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

17/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: replace include file system.h with cp15.h
Date: Tue, 3 Jul 2012 15:55:34 +0800

commit 15d07dc ARM: move CP15 definitions to separate header file

Replaces system.h with cp15.h, so replace the include file.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

18/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: fix missing include file jiffies.h
Date: Tue, 3 Jul 2012 16:00:21 +0800

To fix following compile error:
...
In function 'boot_secondary':
error: 'jiffies' undeclared (first use in this function)
error: implicit declaration of function 'time_before'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

19/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add common include files io.h for IOMEM definition
Date: Tue, 3 Jul 2012 16:14:05 +0800

The following commit moves IOMEM definition to a common include files:
commit 6f6f6a7 ARM: create a common IOMEM definition

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

20/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add missing definition for spear_smi
Date: Tue, 3 Jul 2012 16:21:15 +0800

To fix following compile error:
...
In function 'spear1310_reva_evb_init':
arch/arm/mach-spear13xx/spear1310_reva_evb.c:529:2:
  error: implicit declaration of function 'smi_init_board_info'
...

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

21/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add missing include files
Date: Tue, 3 Jul 2012 16:23:05 +0800

Copy missing include files from st git tree:

git://git.stlinux.com/spear/linux-2.6.git next-3.3
commit a642f8da Input: stmpe-ts: Add runtime power management support

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

22/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: selecting NEED_MACH_IO_H to restore io.h
Date: Thu, 5 Jul 2012 15:27:00 +0800

commit c334bc15 ARM: make mach/io.h include optional

Removes mach/io.h inclusion by default for all machine. But spear13xx
needs it to define pcie io resource, otherwise it breaks the boot of
the kernel.

Now selecting NEED_MACH_IO_H to restore mach/io.h.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

23/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: kill off __mem_pci
Date: Thu, 5 Jul 2012 15:31:21 +0800

commit 5621caac ARM: kill off __mem_pci

Removes all __mem_pci defines of arm, so also delete it for spear.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

24/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add PCIE option in Kconfig
Date: Thu, 5 Jul 2012 15:36:48 +0800

git://git.stlinux.com/spear/linux-2.6.git
commit 2367df7d ST SPEAr: Added PCIE host controller base driver support.

Adds suppport for Synopsys designware PCIE version 3.30a. Here add
PCIE option to select PCIE features for spear13xx.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

25/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: remove IOMEM definition
Date: Mon, 6 Aug 2012 19:20:11 +0800

commit 6f6f6a70 ARM: create a common IOMEM definition

Creates a common IOMEM definition for all arm machine, so remove
IOMEM of SPEAr13xx.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

26/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add one memory bank to meminfo in machines' fixup
Date: Thu, 5 Jul 2012 17:53:04 +0800

DB9000 needs to reserve memory for framebuffer, but in fixup, meminfo has
no memory bank info yet. So add memory bank info before reserving the memory.

With this patch, we can't pass more than 1008M number to mem argument in the
bootargs.

In st git tree, there is one commit to work around this issue:
commit 0d083ab7 ARM init workaround: move fixup call after parse_cmdline

This commit modifies common code arch/arm/kernel/setup.c to postpone
calling fixup, but this is not compatible with multi board support, so
following the approach of other boards that use explicit memory bank
info in the fixup is used here.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

27/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: add pmu platform data into initialization
Date: Thu, 19 Jul 2012 12:14:13 +0800

Oprofile needs pmu to collect data, so add pmu platform data
to ensure pmu initialization when the kernel boots.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

28/28 [
Author: Liming Wang
Email: liming.wang@windriver.com
Subject: SPEAr: enable FSMC nand flash for spear1310 reva evb
Date: Thu, 19 Jul 2012 18:11:24 +0800

FSMC can't both support nand and nor flash
at the same time. By default spear1310 reva evb board
supports FSMC nor flash and enables 16bits for FSMC.

But in spear1310 reva evb board, there is one x8 FSMC NAND flash,
so remove 16bits support for FSMC and enable FSMC nand flash
support in this board.

Signed-off-by: Liming Wang <liming.wang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>