fsl-t2xxx: add dce driver
1/20 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: fsl_dce: Initial DCE device driver support
Date: Thu, 11 Sep 2014 13:52:16 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add FSL DCE device creation and access to device configuration.
This device does compression and decompression.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I6d951fe045f7638530a810c91e5dc21f29549bb1
Reviewed-on: http://git.am.freescale.net:8181/4294
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Thorpe Geoff-R01361 <Geoff.Thorpe@freescale.com>
Reviewed-by: Rivera Jose-B46482 <German.Rivera@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

2/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: Add support for stateless compression/decompression
Date: Tue, 27 Aug 2013 12:05:08 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

The fsl_dce device does compression and decompression of
various formats (deflate, zlib, gzip).
The flib directory contains the base layer object required
to access the dce device. The fsl_dce_flow object contains the
minimum set of interfaces required to send and receive frames
to/from the dce via QMan.

The fsl_dce_chunk object is an extension of the fsl_dce_flow object.
This object is used to compress or decompress single frames (chunks)
at a time.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: Ia1f671b4610fb70d50353385a3d87dde0584741a
Reviewed-on: http://git.am.freescale.net:8181/4295
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Thorpe Geoff-R01361 <Geoff.Thorpe@freescale.com>
Reviewed-by: Rivera Jose-B46482 <German.Rivera@freescale.com>
]

3/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: add stream based (de)compression
Date: Thu, 22 Aug 2013 12:48:45 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

The fsl_dce_stream object enables the user to do stream based (de)compression.
As opposed to chunk based compression where all the data in a single frame is
sent to the DCE device, stream based (de)compression permits the user to send
mulitple frames and receive the corresponding resuls in multiple frames.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I83065d4681c512d595724b4f92a731de8a032867
Reviewed-on: http://git.am.freescale.net:8181/4297
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Thorpe Geoff-R01361 <Geoff.Thorpe@freescale.com>
Reviewed-by: Wang Haiying-R54964 <Haiying.Wang@freescale.com>
Reviewed-by: Rivera Jose-B46482 <German.Rivera@freescale.com>
]

4/20 [
Author: Emil Medve
Email: Emilian.Medve@Freescale.com
Subject: fsl_dce: Include missing OF header files
Date: Mon, 6 Jan 2014 12:42:22 -0600

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

drivers/staging/fsl_dce/dce_driver.c: In function ‘fsl_dce_probe’:
drivers/staging/fsl_dce/dce_driver.c:154:2: error: implicit declaration of function ‘of_iomap’ [-Werror=implicit-function-declaration]
  topregs = of_iomap(nprop, 0);
  ^
drivers/staging/fsl_dce/dce_driver.c:164:2: error: implicit declaration of function ‘of_irq_to_resource’ [-Werror=implicit-function-declaration]
  ctrlpriv->err_irq = of_irq_to_resource(nprop, 0, NULL);
		    ^
drivers/staging/fsl_dce/dce_driver.c:164:2: error: implicit declaration of function ‘of_irq_to_resource’ [-Werror=implicit-function-declaration]
  ctrlpriv->err_irq = of_irq_to_resource(nprop, 0, NULL);
  ^
drivers/staging/fsl_dce/dce_debugfs.c: In function ‘init_ccsrmempeek’:
drivers/staging/fsl_dce/dce_debugfs.c:77:2: error: implicit declaration of function ‘of_get_address’ [-Werror=implicit-function-declaration]
  regaddr_p = of_get_address(dn, 0, &dce_ccsr_size, NULL);
  ^
drivers/staging/fsl_dce/dce_debugfs.c:82:2: error: implicit declaration of function ‘of_translate_address’ [-Werror=implicit-function-declaration]
  dce_ccsr_start = of_translate_address(dn, regaddr_p);
  ^

Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: Ia8f4acb61349ae8a5edb87f5767784b328993d46
Reviewed-on: http://git.am.freescale.net:8181/7721
Reviewed-by: Haiying Wang <Haiying.Wang@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
Tested-by: Emilian Medve <Emilian.Medve@freescale.com>
]

5/20 [
Author: Emil Medve
Email: Emilian.Medve@Freescale.com
Subject: fsl_dce: Update the kfifo API usage
Date: Tue, 7 Jan 2014 13:57:23 -0600

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

As per '498d319 kfifo API type safety'

drivers/staging/fsl_dce/flib/dce_flow.c: In function ‘_pre_commit_cb’:
drivers/staging/fsl_dce/flib/dce_flow.c:404:2: error: invalid initializer
  if (unlikely(kfifo_put(&fifo_arg->flow->fifo, fifo_arg->token) == 0))
  ^

Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: Ifa1795cd44f18c4246ef3a65d4f3cf99e902f888
Reviewed-on: http://git.am.freescale.net:8181/7729
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
]

6/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: Add test module
Date: Tue, 27 Aug 2013 11:59:01 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add modules to self test fsl DCE hardware accelerator.
1) dce_chunk_comp_def_cf_tester.ko
	This module tests the chunk based (de)compression using deflate and compound frames.
2) dce_simple_perf_tester.ko
	This module can be used to measure dce performance throughput.
	The associated README file describes the usage.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: Ifb4ac8af57254190cf3e2be0bbe26d85626f7470
Reviewed-on: http://git.am.freescale.net:8181/4296
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Wang Haiying-R54964 <Haiying.Wang@freescale.com>
Reviewed-by: Rivera Jose-B46482 <German.Rivera@freescale.com>
]

7/20 [
Author: Emil Medve
Email: Emilian.Medve@Freescale.com
Subject: fsl_dce: Fix tester(s) build warnings
Date: Thu, 16 Jan 2014 03:36:59 -0600

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

drivers/staging/fsl_dce/tests/common/test_frame_helpers.c: In function ‘print_dce_data_list’:
drivers/staging/fsl_dce/tests/common/test_frame_helpers.c:272:4: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
    pr_info("    cpumem = %p, size = %lu\n",
    ^
drivers/staging/fsl_dce/tests/common/test_frame_helpers.c:283:3: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
   pr_info("    cpumem = %p, size = %lu\n",
   ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c: In function ‘copy_bman_output_to_buffer’:
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:388:4: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t’ [-Wformat=]
    pr_info("total frame length != calulated length (%lu)"
    ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:398:4: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t’ [-Wformat=]
    pr_info("sg length != frame output length (%lu) (%u)\n",
    ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c: In function ‘write_file’:
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:522:3: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
   pr_info("Error %d, data_len %lu\n", rc, data_len);
   ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c: In function ‘dce_loopback_shutdown’:
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:694:77: warning: comparison of distinct pointer types lacks a cast [enabled by default]
  do_div(dce_freq, 2);
  ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:694:2: warning: right shift count >= width of type [enabled by default]
  do_div(dce_freq, 2);
  ^
drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:694:2: warning: passing argument 1 of ‘__div64_32’ from incompatible pointer type [enabled by default]
In file included from arch/powerpc/include/asm/div64.h:1:0,
                 from include/linux/kernel.h:111,
                 from drivers/staging/fsl_dce/tests/performance_simple/dce_perf_simple.c:33:
include/asm-generic/div64.h:35:17: note: expected ‘uint64_t *’ but argument is of type ‘uint32_t *’
 extern uint32_t __div64_32(uint64_t *dividend, uint32_t divisor);
                 ^

Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: If682239365c0d59bf01d7fc712cbfc410de0854c
Reviewed-on: http://git.am.freescale.net:8181/8003
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
]

8/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: A apis to dce stream object
Date: Fri, 4 Oct 2013 14:04:19 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add an API to get the length of the internal objects fifo.
Add invalidate stream context record api.
Missing flags parameter to process API.
Add checking for REV1 limitations.
Set default object fifo depth to 256.
Add private header file.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I0149ab9309ad41d920c21192cb9f0aa3bfb9256a
Reviewed-on: http://git.am.freescale.net:8181/11626
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

9/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: dce: common test code update
Date: Fri, 4 Oct 2013 14:25:47 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add api to display multi buffer scatter gather data.
Distinguish between allocated dce data and amount of data copied to it.
Add attribute to gzip request structure to enable adding them to a list.
Add request structure to invalidate a stream context record.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>

Conflicts:

	drivers/staging/fsl_dce/tests/common/test_frame_helpers.c

Change-Id: I59fa85503f4de953c2b48042942d3670f9e41a17
Reviewed-on: http://git.am.freescale.net:8181/11628
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

10/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: add stateful performance test
Date: Fri, 4 Oct 2013 16:57:57 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add test that demonstrates fsl dce stateful performance metrics.
This is similar to the stateless test except that multiple chunks
are sent on a stream instead on one big chunk.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I222981506f013febf6ae1f95ba610507c8dd0a49
Reviewed-on: http://git.am.freescale.net:8181/11630
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

11/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: Add documentation to apis
Date: Mon, 28 Apr 2014 15:16:30 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add documentation to dce APIs

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: Ib71b500d0d59a64645bdd39d071712d418a5fcb8
Reviewed-on: http://git.am.freescale.net:8181/11729
Reviewed-by: Haiying Wang <Haiying.Wang@freescale.com>
Reviewed-by: Roy Pledge <roy.pledge@freescale.com>
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

12/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: dce flib: force order of operations on value
Date: Thu, 26 Sep 2013 10:51:50 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Expression such as ?: for "value" require value be placed in
parenthesis in order to be evaluated first.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I1598785559685acaf30ba970c4603b03b79f4386
Reviewed-on: http://git.am.freescale.net:8181/11629
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Roy Pledge <roy.pledge@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

13/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: Fix broken dce tests
Date: Fri, 9 May 2014 13:45:32 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

The dce test code was broken when focus was placed on bman usage.
Fixed test code when using pre-built buffers.
Added verbosity level to test cases.
Change kernel help api name to explicitly name output buffer as this is
consistent with bman api.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: I62aae72b5075718180729fe49b62524eea9d28fa
Reviewed-on: http://git.am.freescale.net:8181/12099
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Geoff Thorpe <Geoff.Thorpe@freescale.com>
Reviewed-by: Richard Schmitt <richard.schmitt@freescale.com>
]

14/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: fsl_dce: add error check in test
Date: Thu, 15 May 2014 17:37:08 -0400

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

If there was a error during the process operation the output of zero bytes
was still being allocated. This causes a trace to occur in vmalloc.
Skip allocating and copying output on error.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: Ie4f0462902a15aae44a20a7de2478a6488da0e1d
Reviewed-on: http://git.am.freescale.net:8181/12426
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Roy Pledge <roy.pledge@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

15/20 [
Author: Jiang Lu
Email: lu.jiang@windriver.com
Subject: fsl_dce: fix calltrace for performance_simple test module
Date: Wed, 13 Aug 2014 16:37:12 +0800

Replace smp_processor_id() with raw_smp_processor_id() to fix following
calltrace:

BUG: using smp_processor_id() in preemptible [00000000] code: insmod/648
caller is .dce_loopback_init+0x2a4/0x10a0 [dce_simple_perf_tester]
CPU: 7 PID: 648 Comm: insmod Tainted: G         C   3.10.38-ltsi-WR6.0.0.0_standard #36
Call Trace:
[c00000000685f800] [c00000000000acc0] .show_stack+0x170/0x290 (unreliable)
[c00000000685f8f0] [c000000000a5dc64] .dump_stack+0x28/0x3c
[c00000000685f960] [c0000000004e278c] .debug_smp_processor_id+0x11c/0x130
[c00000000685f9f0] [8000000000385474] .dce_loopback_init+0x2a4/0x10a0 [dce_simple_perf_tester]
[c00000000685fb10] [c000000000001bc4] .do_one_initcall+0x164/0x1c0
[c00000000685fbc0] [c0000000000e065c] .load_module+0x18bc/0x23a0
[c00000000685fd40] [c0000000000e1300] .SyS_finit_module+0xa0/0xd0
[c00000000685fe30] [c000000000000618] syscall_exit+0x0/0x8c

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

16/20 [
Author: Jeffrey Ladouceur
Email: Jeffrey.Ladouceur@freescale.com
Subject: dce: validate input to test module
Date: Mon, 3 Nov 2014 16:42:42 -0500

The dce_simple_perf_tester module needs to validate input parameter.

Signed-off-by: Jeffrey Ladouceur <Jeffrey.Ladouceur@freescale.com>
Change-Id: Ie0dddfb8e23532895e6ec2276f201e3b555fed62
Reviewed-on: http://git.am.freescale.net:8181/22952
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Haiying Wang <Haiying.Wang@freescale.com>
Reviewed-by: Roy Pledge <roy.pledge@freescale.com>
Reviewed-by: Richard Schmitt <richard.schmitt@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

17/20 [
Author: Mahammad Ismayilzada
Email: mahammad.ismayilzada@freescale.com
Subject: dce: Typo correction
Date: Wed, 20 May 2015 15:00:35 -0400

slab_scr_128b should be checked for NULL.

Signed-off-by: Mahammad Ismayilzada <mahammad.ismayilzada@freescale.com>
Change-Id: I51f5b7c96fbee9a0f1baf2340ff97b23caed434e
Reviewed-on: http://git.am.freescale.net:8181/36649
Reviewed-by: Haiying Wang <Haiying.Wang@freescale.com>
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Roy Pledge <roy.pledge@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

18/20 [
Author: Wang Quanyang
Email: quanyang.wang@windriver.com
Subject: fsl_dce: convert cpumask_scnprintf to %*pb[l]
Date: Sat, 10 Oct 2015 02:18:37 -0400

According to upstream commit 46385326cc15
("bitmap, cpumask, nodemask: remove dedicated formatting functions"),
use '%*pb[l]' instead of function "cpumask_scnprintf".

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

19/20 [
Author: Wang Quanyang
Email: quanyang.wang@windriver.com
Subject: fsl_dce: use read_iter instead of aio_read
Date: Sat, 10 Oct 2015 02:18:55 -0400

According to upstream commit 8436318205b9 ("->aio_read and ->aio_write removed"),
use read_iter instead of aio_write.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

20/20 [
Author: Wang Quanyang
Email: quanyang.wang@windriver.com
Subject: mtd/spi: support en25s64 spi-nor device
Date: Thu, 8 Oct 2015 10:12:52 +0000

In upstream commit a5b7616c55e1
("mtd: m25p80,spi-nor: Fix module aliases for m25p80"),
the id_table in spi_driver struct has changed from "spi_nor_ids"
to "m25p_ids". So need add "en25s64" to the new id_table.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]