arch/mips: fix building failure when gcc6 is used
1/1 [
Author: Roy Li
Email: rongqing.li@windriver.com
Subject: arch/mips: fix building failure when gcc6 is used
Date: Wed, 29 Jun 2016 13:10:11 +0800

1. fix indentation to kill the warning of misleading-indentation
in setup.c and cvmx-help-pki.c

arch/mips/cavium-octeon/setup.c:1048:3: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
   if (size)

arch/mips/cavium-octeon/executive/cvmx-helper-pki.c: In function 'cvmx_helper_pki_init_port':
arch/mips/cavium-octeon/executive/cvmx-helper-pki.c:1058:4: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
  } else
    ^~~~
2. remove the static variable to kill the warning as error of
unused-const-variable

mips/cavium-octeon/executive/cvmx-helper.c:369:31: error: 'iface_ops_srio' defined but not used [-Werror=unused-const-variable=]
 static const struct iface_ops iface_ops_srio = {

Signed-off-by: Roy Li <rongqing.li@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>