pch_uart: Use DMI interface for board detection
1/8 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_uart: Use DMI interface for board detection
Date: Fri, 12 Jul 2013 17:58:05 -0700

Use the DMI interface rather than manually matching DMI strings.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
Cc: Michael Brunner <mibru@gmx.de>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

2/8 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: serial: pch_uart: Remove __initdata annotation from dmi_table
Date: Mon, 29 Jul 2013 09:58:14 -0700

The dmi_table is best accessed from the probe function, which is not
an __init function. Drop the __initdata annotation from the dmi_table
to avoid the section mismatch compiler warnings:

WARNING: drivers/tty/serial/pch_uart.o(.text+0x4871): Section mismatch
in reference from the function pch_uart_init_port() to the variable
.init.data:pch_uart_dmi_table

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: Jiri Slaby <jslaby@suse.cz>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

3/8 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: serial: pch_uart: Fix signed-ness and casting of uartclk related fields
Date: Mon, 29 Jul 2013 15:15:07 -0700

Storing one struct per known board would be overkill. Pre-cast the
driver_data pointer to an unsigned long to avoid the pointer to int
compiler warning:

drivers/tty/serial/pch_uart.c:431:10: warning: cast from pointer to
integer of different size [-Wpointer-to-int-cast]

Unify the signed-ness of the baud and uartclk types throughout the
driver.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: Jiri Slaby <jslaby@suse.cz>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

4/8 [
Author: Luis Henriques
Email: luis.henriques@canonical.com
Subject: serial: pch_uart: fix compilation warning
Date: Wed, 14 Aug 2013 23:18:37 +0100

Function wait_for_xmitr is invoked only on functions that either depend
on CONFIG_CONSOLE_POLL or CONFIG_SERIAL_PCH_UART_CONSOLE.

This patch fixes the following warning:

drivers/tty/serial/pch_uart.c:1504:13: warning: ‘wait_for_xmitr’ defined but not used [-Wunused-function]

Signed-off-by: Luis Henriques <luis.henriques@canonical.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

5/8 [
Author: Andy Shevchenko
Email: andriy.shevchenko@linux.intel.com
Subject: pch_gbe: convert pr_* to netdev_*
Date: Fri, 28 Jun 2013 14:02:53 +0300

We may use nice macros to prefix our messages with proper device name.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
]

6/8 [
Author: Andy Shevchenko
Email: andriy.shevchenko@linux.intel.com
Subject: pch_gbe: use managed functions pcim_* and devm_*
Date: Fri, 28 Jun 2013 14:02:54 +0300

This makes the error handling much more simpler than open-coding everything and
in addition makes the probe function smaller an tidier.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
]

7/8 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_gbe: Use PCH_GBE_PHY_REGS_LEN instead of 32
Date: Sat, 18 May 2013 14:45:55 -0700

Avoid using magic numbers when we have perfectly good defines just lying
around.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
Cc: "David S. Miller" <davem@davemloft.net>
Cc: "H. Peter Anvin" <hpa@zytor.com>
Cc: Peter Waskiewicz <peter.p.waskiewicz.jr@intel.com>
Cc: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Cc: netdev@vger.kernel.org
]

8/8 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_gbe: Add MinnowBoard support
Date: Sat, 18 May 2013 14:46:00 -0700

The MinnowBoard uses an AR803x PHY with the PCH GBE which requires
special handling. Use the MinnowBoard PCI Subsystem ID to detect this
and add a pci_device_id.driver_data structure and functions to handle
platform setup.

The AR803x does not implement the RGMII 2ns TX clock delay in the trace
routing nor via strapping. Add a detection method for the board and the
PHY and enable the TX clock delay via the registers.

This PHY will hibernate without link for 10 seconds. Ensure the PHY is
awake for probe and then disable hibernation. A future improvement would
be to convert pch_gbe to using PHYLIB and making sure we can wake the
PHY at the necessary times rather than permanently disabling it.

Backported to 3.10 from commit f1a26fdf5944ff950888ae0017e546690353f85f

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
Cc: "David S. Miller" <davem@davemloft.net>
Cc: "H. Peter Anvin" <hpa@zytor.com>
Cc: Peter Waskiewicz <peter.p.waskiewicz.jr@intel.com>
Cc: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Cc: Joe Perches <joe@perches.com>
Cc: netdev@vger.kernel.org
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>