cav-octeon3 : fix bug about watchdog and perf tool building
Rally: US72761

1/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: perf tools: Add missing macro definition for UNW_MIPS_PC
Date: Sun, 3 Jan 2016 20:28:48 +0800

Add definition for UNW_MIPS_PC, or else it will occurr compile error when
build perf tool as below:

CC bitbake_build/tmp/work/cav_octeon3-wrs-linux/perf/1.0-r8/perf-1.0/arch/mips/util/unwind.o
| arch/mips/util/unwind.c: In function 'unwind__arch_reg_id':
| arch/mips/util/unwind.c:14:7: error: 'UNW_MIPS_PC' undeclared (first use in this function)
|   case UNW_MIPS_PC:
|        ^
| arch/mips/util/unwind.c:14:7: note: each undeclared identifier is reported only once for each function it appears in
| make: *** bitbake_build/tmp/work/cav_octeon3-wrs-linux/perf/1.0-r8/perf-1.0/arch/mips/util/unwind.o] Error 1

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: watchdog: octeon-wdt: Use PERCPU hander for percpu watchdog interrupts.
Date: Sun, 3 Jan 2016 20:16:45 +0800

The octeon_wdt_poke_irq for each core must be set IRQF_PERCPU to
make sure that it can't be immigrated to other cores.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>