qman:fix a calltrace introduced by qman
1/3 [
Author: Jiang Lu
Email: lu.jiang@windriver.com
Subject: qman:fix a calltrace introduced by qman
Date: Tue, 23 Jul 2013 15:35:22 +0800

Fix following calltrace:

BUG: using smp_processor_id() in preemptible [00000000] code: simple_crypto/1292
caller is qm_get_unused_portal+0x88/0xe8
Call Trace:
[ea243d40] [c0008118] show_stack+0x10c/0x1c0 (unreliable)
[ea243d90] [c0736668] dump_stack+0x24/0x34
[ea243da0] [c03a3850] debug_smp_processor_id+0xd8/0xfc
[ea243dc0] [c05f8ab8] qm_get_unused_portal+0x88/0xe8
[ea243de0] [c05fd79c] usdpaa_release+0x5e0/0x694
[ea243e40] [c014f058] fput+0xcc/0x25c
[ea243e60] [c014a830] filp_close+0x84/0xb4
[ea243e80] [c0039cb4] put_files_struct+0xf8/0x128
[ea243ea0] [c003b024] exit_files+0x50/0x64
[ea243ec0] [c003b508] do_exit+0x15c/0x80c
[ea243f10] [c003bea8] do_group_exit+0x54/0xb4
[ea243f30] [c003bf28] __wake_up_parent+0x0/0x40
[ea243f40] [c000f7bc] ret_from_syscall+0x0/0x3c

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

2/3 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: crypto: Convert to new AEAD interface
Date: Mon, 31 Oct 2016 15:23:30 +0800

This patch converts testmgr and cryptlib to the new AEAD interface,
it is to fix the below error:

crypto/testmgr.c:1090:3: error: implicit declaration of function 'aead_request_set_assoc' [-Werror=implicit-function-declaration]
    aead_request_set_assoc(req, asg, template[i].alen);
    ^

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

3/3 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: clk: added the missed consumer APIs for discovering possible parent clocks
Date: Mon, 10 Oct 2016 13:32:30 +0800

Commit 5c2286fb5ae (clk: Add consumer APIs for discovering possible parent
clocks) added the clk_get_num_parents() for 4.1 kernel, but for 4.8 kernel
the function clk_get_parent_by_index() is needed also, so added it.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>