btrfs: fix min csum item size warnings in 32bit
CQID: WIND00446129
JIRAID: LIN5-3237

1/1 [
Author: Zach Brown
Email: zab@zabbo.net
Subject: btrfs: fix min csum item size warnings in 32bit
Date: Tue, 17 Dec 2013 14:42:37 +0800

commit:221b831835421f9451182611fa25fa60f440662f upstream

commit 7ca4be45a0255ac8f08c05491c6add2dd87dd4f8 limited csum items to
PAGE_CACHE_SIZE.  It used min() with incompatible types in 32bit which
generates warnings:

fs/btrfs/file-item.c: In function ‘btrfs_csum_file_blocks’:
fs/btrfs/file-item.c:717: warning: comparison of distinct pointer types lacks a cast

This uses min_t(u32,) to fix the warnings.  u32 seemed reasonable
because btrfs_root->leafsize is u32 and PAGE_CACHE_SIZE is unsigned
long.

Signed-off-by: Zach Brown <zab@zabbo.net>
Signed-off-by: baogen shang <baogen.shang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>