ppc-mc/fsl_p4080ds: two fixes for boot problems
Both of these are squashed with:
  wrhv-powerpc-introduce-powerpc-specifics-of-WR-guest.patch

CQID: WIND00295566

1/2 [
Author: Tiejun Chen
Email: tiejun.chen@windriver.com
Subject: ppc-mc/fsl_p4080ds: add board config in arch/powerpc/boot/Makefile
Date: Wed, 24 Aug 2011 15:21:26 +0800

We have to pass 'CONFIG_WRHV_P4080DS' as 'BOOTCFLAGS' to arch/powerpc/boot
to avoid missing one necessary initialization dedicate to fsl_p4080ds guest
OS.

Signed-off-by: Tiejun Chen <tiejun.chen@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>

CQID: WIND00295607

2/2 [
Author: Tiejun Chen
Email: tiejun.chen@windriver.com
Subject: ppc-mc/fsl_p4080ds: fix one build error
Date: Wed, 24 Aug 2011 17:10:28 +0800

When disable CONFIG_FSL_PQ_MDIO there is one build error:

......
  LD      init/built-in.o
  LD      .tmp_vmlinux1
arch/powerpc/kernel/built-in.o:(.sdata+0x58): undefined reference to `native_fsl_pq_mdio_write'
arch/powerpc/kernel/built-in.o:(.sdata+0x5c): undefined reference to `native_fsl_pq_mdio_read'
/buildarea/tchen0/workplace/fsl_p4080-gs/build/linux/Makefile:823: *** [.tmp_vmlinux1] Error 1
remake[3]: *** [sub-make] Error 2
remake[2]: *** [all] Error 2
remake[1]: *** [linux.wrhvImage.wrhv_p4080ds0] Error 2
make: *** [linux.wrhvImage.wrhv_p4080ds0] Error 2

So we should weak these two native references defined in device driver file, drivers/net/fsl_pq_mdio.c.

Signed-off-by: Tiejun Chen <tiejun.chen@windriver.com>
]

Refreshes for:
  wrhv-e500-enable-ASID-for-powerpc-GOS.patch
  wrhv-virtio-implement-duart-and-virtual-serial-for-G.patch

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>