fixed ERROR while compiling bsp of axxiaarm with DEBUG_LL enabled
Issue: LIN8-2705

1/1 [
Author: Qi Hou
Email: qi.hou@windriver.com
Subject: fixed ERROR while compiling bsp of axxiaarm with DEBUG_LL enabled.
Date: Tue, 23 Feb 2016 10:58:20 +0800

When ERROR, the output likes below:
axxiaarm/kernel-source/arch/arm/mach-axxia/include/mach/debug-macro.S:21:38:
fatal error: asm/hardware/debug-pl01x.S: No such file or directory ...

fixed this compiling error by correcting the include of PL01X debug.

The PL01X debug file named "debug-pl01x.S" has been moved from arch/arm/include/asm/hardware/
to arch/arm/include/debug/ and been renamed as pl01x.S, but the include of it in
arch/arm/kernel/debug.S in code of bsp of axxiaarm hasn't be amended.
So here, I just corrected including path of it to "#include <debug/pl01x.S>".
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>