fix some qman-test issues
Issue: LIN8-4326

1/2 [
Author: yhe
Email: yongli.he@windriver.com
Subject: fsl QMAN:Add QMAN_FQ_FLAG_FQSCB_NEED_SLP flag to qman_fq
Date: Wed, 19 Dec 2012 14:51:55 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context
at linux/kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 1430, name: modprobe
Call Trace:
[eae33db0] [c0007b10] show_stack+0x44/0x160 (unreliable)
[eae33de0] [c0034bb4] __might_sleep+0xe4/0x108
[eae33df0] [c0639d2c] rt_spin_lock+0x38/0xb4
[eae33e00] [c003a0cc] __wake_up+0x24/0x58
[eae33e20] [f955eee8] cb_fqs+0x54/0x70 [qman_tester]
[eae33e30] [c05637b8] qman_retire_fq+0x324/0x438
[eae33ea0] [f955f2f4] qman_test_high+0x1cc/0x2d8 [qman_tester]
[eae33ee0] [f955e018] test_init+0x14/0x2c [qman_tester]
[eae33ef0] [c0001d44] do_one_initcall+0x3c/0x1e0
[eae33f20] [c0085bb0] sys_init_module+0xf8/0x21c
[eae33f40] [c0010fc4] ret_from_syscall+0x0/0x4
    Exception: c00 at 0xff63564
    LR = 0x10003380

This is caused by the fqs callback function of qman_test_high
case involved a sleepable spinlock introduced by wake_up(), and the
callback is invoked from fqs_retire_fqs(), which implements a context
disabled preempt & irq.

The atomic context is used to protect key structure for qman driver.
While the callback of qman_test_high didn't touch such resource. So it
is free to invoke the callback outside the atomic context.

As result, the patch adds QMAN_FQ_FLAG_FQSCB_NEED_SLP  flag to qman_fq
structure. If the fqs callback function involves sleepable routine,
driver needs set the correspond bit when creating fq.

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

2/2 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: fsl_qbman: replace get_cpu_var with this_cpu_ptr
Date: Fri, 29 Jul 2016 15:38:23 +0800

create_per_cpu_handlers() and destroy_per_cpu_handlers() have been bound
to a special CPU through on_all_cpus(), so we don't need to disable preempt
in these two functions. Else we would get some atomic warnings like below:

BUG: sleeping function called from invalid context at kernel/locking/rtmutex.c:917
in_atomic(): 1, irqs_disabled(): 0, pid: 1112, name: hotpotato0
Preemption disabled at:[<          (null)>]           (null)

CPU: 0 PID: 1112 Comm: hotpotato0 Tainted: G         C
Call Trace:
[c0000005d4b5fa70] [c000000000b70bc8] .dump_stack+0xb4/0xfc (unreliable)
[c0000005d4b5fb00] [c00000000009ee10] .___might_sleep+0x170/0x200
[c0000005d4b5fb90] [c000000000b6c010] .rt_spin_lock+0x30/0xa0
[c0000005d4b5fc10] [800000000073f324] .create_per_cpu_handlers+0x84/0x1d0 [qman_tester]
[c0000005d4b5fcb0] [800000000073f9e8] .bstrap_fn+0x48/0x90 [qman_tester]
[c0000005d4b5fd30] [c0000000000934e8] .kthread+0x108/0x130
[c0000005d4b5fe30] [c0000000000009b0] .ret_from_kernel_thread+0x58/0xa8

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>