r1801e/stm-spear: drop this unused machine
NOCQID

1/1 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: r1801e/stm-spear: drop this unused machine
Date: Wed, 6 Feb 2013 11:01:39 -0500

The upstream ltsi commit "ARM: Update mach-types" drops r1801e machine
type.  While we prefer not to do that, we also are not using
MACH_R1801E.  Rather than deviate from the upstream, we'll drop r1801e
from the stm-spear patch series.

The following compile error occurred when ltsi removed r1801e:
arch/arm/plat-spear13xx/include/plat/hardware.h:29:2: error: implicit declaration of function 'machine_is_r1801e'

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>