compiler.h: Undef before redefining __attribute_const__
1/1 [
Author: Khem Raj
Email: raj.khem@gmail.com
Subject: compiler.h: Undef before redefining __attribute_const__
Date: Thu, 5 Jan 2012 11:42:35 -0800

This is required to avoid warnings like
util/include/linux/compiler.h:8:0: error: "__attribute_const__" redefined [-Werror]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>