refresh import-of-RMI-XLP-svn-branch.patch
These hunks are now introduced by the kgdb series on standard/base
branch.

Treegen did not detect or fail on all of these duplicate hunks.
Instead build had an error:
  arch/mips/kernel/kgdb.c:602:2: error: duplicate case value
     case 's': {
     ^
  arch/mips/kernel/kgdb.c:555:2: error: previously used here
     case 's': {
     ^

See also these kgdb patches where those hunks are introduced:
  kgdb-mips-Add-in-kernel-software-single-stepping.patch
  mips-kdb-Add-software-single-stepping-support.patch

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>