fsl-p10xx: fix the kernel build warnings
Issue: LIN7-4821

1/7 [
Author: Zhao Qiang
Email: B45475@freescale.com
Subject: powerpc/ucc_geth: deal with a compile warning
Date: Tue, 1 Jul 2014 09:21:34 +0800

commit 8844a00626c78c30e8cd757f2a048038f4983c53 upstream

deal with a compile warning: comparison between
'enum qe_fltr_largest_external_tbl_lookup_key_size'
and 'enum qe_fltr_tbl_lookup_key_size'

the code:
	"if (ug_info->largestexternallookupkeysize ==
	     QE_FLTR_TABLE_LOOKUP_KEY_SIZE_8_BYTES)"
is warned because different enum, so modify it.

	"enum qe_fltr_largest_external_tbl_lookup_key_size
	             largestexternallookupkeysize;

	enum qe_fltr_tbl_lookup_key_size {
		 QE_FLTR_TABLE_LOOKUP_KEY_SIZE_8_BYTES
			 = 0x3f,         /* LookupKey parsed by the Generate LookupKey
					    CMD is truncated to 8 bytes */
		 QE_FLTR_TABLE_LOOKUP_KEY_SIZE_16_BYTES
			 = 0x5f,         /* LookupKey parsed by the Generate LookupKey
					    CMD is truncated to 16 bytes */
	 };

	 /* QE FLTR extended filtering Largest External Table Lookup Key Size */
	 enum qe_fltr_largest_external_tbl_lookup_key_size {
		 QE_FLTR_LARGEST_EXTERNAL_TABLE_LOOKUP_KEY_SIZE_NONE
			 = 0x0,/* not used */
		 QE_FLTR_LARGEST_EXTERNAL_TABLE_LOOKUP_KEY_SIZE_8_BYTES
			 = QE_FLTR_TABLE_LOOKUP_KEY_SIZE_8_BYTES,        /* 8 bytes */
		 QE_FLTR_LARGEST_EXTERNAL_TABLE_LOOKUP_KEY_SIZE_16_BYTES
			 = QE_FLTR_TABLE_LOOKUP_KEY_SIZE_16_BYTES,       /* 16 bytes */
	 };"

Signed-off-by: Zhao Qiang <B45475@freescale.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
]

2/7 [
Author: Chen Gang
Email: gang.chen.5i5j@gmail.com
Subject: PM / hibernate: use unsigned local variables in swsusp_show_speed()
Date: Fri, 25 Apr 2014 08:44:59 +0800

commit 4881f603d7b82df2bc15efd2a272f973a3bf8df1 upstream

do_div() needs 'u64' type, or it reports warning. And negative number
is meaningless for "speed", so change all signed to unsigned within
swsusp_show_speed().

The related warning (with allmodconfig for unicore32):

    CC      kernel/power/hibernate.o
  kernel/power/hibernate.c: In function ‘swsusp_show_speed’:
  kernel/power/hibernate.c:237: warning: comparison of distinct pointer types lacks a cast

Signed-off-by: Chen Gang <gang.chen.5i5j@gmail.com>
[rjw: Subject]
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
]

3/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: net: ucc_geth: use %pa for the resource_size_t printing
Date: Tue, 13 Oct 2015 10:33:32 +0800

This fixes the following build warning:
  drivers/net/ethernet/freescale/ucc_geth.c: In function 'ucc_geth_probe':
  drivers/net/ethernet/freescale/ucc_geth.c:3852:3: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'resource_size_t' [-Wformat=]
     pr_info("UCC%1d at 0x%8x (irq = %d)\n",

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

4/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: tdm: replace the deprecated idr helper functions
Date: Tue, 13 Oct 2015 10:57:57 +0800

Fixes the following build warnings:
  drivers/tdm/tdm-core.c: In function 'tdm_add_adapter':
  drivers/tdm/tdm-core.c:204:2: warning: 'idr_pre_get' is deprecated (declared at include/linux/idr.h:155) [-Wdeprecated-declarations]
    if (idr_pre_get(&tdm_adapter_idr, GFP_KERNEL) == 0)
    ^
  drivers/tdm/tdm-core.c:208:2: warning: 'idr_get_new' is deprecated (declared at include/linux/idr.h:185) [-Wdeprecated-declarations]
    res = idr_get_new(&tdm_adapter_idr, adapter, &id);

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

5/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: tdm: remove the unused variable and function
Date: Tue, 13 Oct 2015 11:10:45 +0800

Fixed the following build warnings:
  drivers/tdm/device/tdm_fsl.c: In function 'tdm_fsl_reg_init':
  drivers/tdm/device/tdm_fsl.c:418:14: warning: unused variable 'base' [-Wunused-variable]
    phys_addr_t base = get_immrbase();
                ^
  drivers/tdm/device/tdm_fsl.c: At top level:
  drivers/tdm/device/tdm_fsl.c:202:20: warning: 'tdm_err_isr' defined but not used [-Wunused-function]
   static irqreturn_t tdm_err_isr(int irq, void *p)

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

6/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: tdm: line_ctrl: include the missing of_address.h header file
Date: Tue, 13 Oct 2015 11:14:34 +0800

Fixes the following build errors:
  drivers/tdm/line_ctrl/slic_maxim.c: In function 'slic_change_cs':
  drivers/tdm/line_ctrl/slic_maxim.c:255:2: error: implicit declaration of function 'of_iomap' [-Werror=implicit-function-declaration]
    cpld_base = of_iomap(cpld_node, 0);
    ^
  drivers/tdm/line_ctrl/slic_maxim.c:255:12: warning: assignment makes pointer from integer without a cast
    cpld_base = of_iomap(cpld_node, 0);
              ^
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

7/7 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: tdm: slic_zarlink: remove the unused variables
Date: Tue, 13 Oct 2015 11:20:37 +0800

Fixes the following build warnings:
  drivers/tdm/line_ctrl/slic_zarlink.c: In function 'configure_spi_pdata':
  drivers/tdm/line_ctrl/slic_zarlink.c:573:22: warning: unused variable 'np' [-Wunused-variable]
    struct device_node *np = spi->dev.of_node;
                        ^
  drivers/tdm/line_ctrl/slic_zarlink.c:572:13: warning: unused variable 'iprop' [-Wunused-variable]
    const u32 *iprop;
               ^
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>