console/font: Refactor font support code selection logic
Issue: LIN6-8780

1/2 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: console/font: Refactor font support code selection logic
Date: Mon, 24 Nov 2014 17:48:47 +0800

Commit d1e183c8dd38bfdd07e38a79577fe78124e63ab1 from upstream.

The current Makefile rules to build font support are messy and buggy.
Replace them by Kconfig rules:
  - Introduce CONFIG_FONT_SUPPORT, which controls the building of all font
    code,
  - Select CONFIG_FONT_SUPPORT for all drivers that use fonts,
  - Select CONFIG_FONT_8x16 for all drivers that default to the VGA8x16
    font,
  - Drop the bogus console dependency for CONFIG_VIDEO_VIVI,
  - Always process drivers/video/console/Makefile, as some drivers need
    fonts even if CONFIG_VT is not set.

This fixes (if CONFIG_SOLO6X10=y and there are no built-in console
drivers):

drivers/built-in.o: In function `solo_osd_print':
drivers/staging/media/solo6x10/solo6x10-enc.c:144: undefined reference to `.find_font'

This fixes (if CONFIG_VT=n):

drivers/built-in.o: In function `vivi_init':
vivi.c:(.init.text+0x1a3da): undefined reference to `find_font'

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Hans Verkuil <hans.verkuil@cisco.com> [original part]
Acked-by: Randy Dunlap <rdunlap@infradead.org> [drivers/video/Makefile]
Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

2/2 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: Revert "staging/solo6x10: depend on CONFIG_FONTS"
Date: Tue, 25 Nov 2014 10:24:12 +0800

Commit 866f321339988293a5bb3ec6634c2c9d8396bf54 from upstream.

This reverts commit 8c090cfbf980581454ae4caae731574fedd7dce8.

CONFIG_FONTS is not about enabling font support, but about enabling
manual selection of built-in fonts.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>