intelras: fixes for parameter mismatch and missing external_refcount
Compile errors were:
mm/migrate.c:793: error: 'struct anon_vma' has no member named
'external_refcount'
mm/migrate.c:800: error: too many arguments to function
'move_to_new_page'
mm/migrate.c:805: error: 'struct anon_vma' has no member named
'external_refcount'

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>