drm: add the base source of the Poulsbo (psb) 2D X11 driver
1/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm: add the base source of the Poulsbo (psb) 2D X11 driver
Date: Fri, 29 Jul 2011 23:17:39 -0500

The complete source of the base (unpatched) psb-kernel-source Poky
package, moved into the kernel tree so it can be build as a
first-class citizen instead of as an external module.  Subsequent
patches will remove the unnecessary parts.

The code here is all the code contained in this tarball:

https://launchpad.net/~gma500/+archive/ppa/+files/
	psb-kernel-source_4.42.0-0ubuntu2~1010um5.tar.gz

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

2/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: remove the package Makefile and replace it with the kernel Makefile
Date: Fri, 29 Jul 2011 23:21:50 -0500

The default Makefile is meant for building the modules externally.
Replace it with the normal kernel Makefile (Makefile.kernel).

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

3/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm: apply psb-kernel-source package's build.patch
Date: Fri, 29 Jul 2011 23:26:46 -0500

Build mods required for compilation.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

4/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm: intel_ldvs.c: add missing arg to backlight_device_register() call
Date: Fri, 29 Jul 2011 23:31:03 -0500

backlight_device_register() added a backlight_props param - give it
another arg to keep it happy.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

5/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: emenlow: switch to psb
Date: Fri, 29 Jul 2011 23:32:44 -0500

Use drm-psb instead of drm for emenlow.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

6/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm: Fix psb ioctl assignment
Date: Fri, 29 Jul 2011 23:35:27 -0500

Replace drm_ioctl with drm_unlocked_ioctl.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

7/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: remove BKL remnants
Date: Sat, 30 Jul 2011 21:53:51 -0500

replace lock/unlock_kernel with the drm_global_mutex from 3.0.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

8/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: update spinlock initializers
Date: Sat, 30 Jul 2011 23:53:19 -0500

Update SPIN_LOCK_UNLOCKED users to __ form.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

9/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: remove call to agp_flush_chipset
Date: Sun, 31 Jul 2011 00:45:23 -0500

agp_flush_chipset was removed because intel drm calls the chipset
functions directly, and psb doesn't implement a chipset_flush()
function anyway.  Leave drm_agp_flush_chipset exported for modules
that might be expecting it to be there though.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

10/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: remove includes of nonexistent i2c-id.h
Date: Sun, 31 Jul 2011 08:09:15 -0500

i2c-id.h is gone, don't include it.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

11/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: remove assigment to deprecated i2c_adapter.id
Date: Sun, 31 Jul 2011 16:58:53 -0500

i2c_adapter.id has been removed and it's not used by anything, so
remove it.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

12/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: use console_lock/unlock()
Date: Sun, 31 Jul 2011 18:39:38 -0500

The acquire/release_console_sem() functions were renamed to
console_lock/unlock(), so change the calls.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

13/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: add DRM_UNLOCKED flag
Date: Tue, 20 Sep 2011 13:17:42 -0500

Add DRM_UNLOCKED to allow us to call handlers that do their own
locking without the global lock.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

14/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: mark unlocked ioctls
Date: Tue, 20 Sep 2011 14:18:41 -0500

Mark the ioctls that already do their own locking DRM_UNLOCKED.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

15/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: initialize backlight type
Date: Tue, 20 Sep 2011 15:17:39 -0500

If unset, props.type gets the value 0, which is no longer maps to a
valid type value, so initialize it explicitly.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

16/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: fix ioremap calls
Date: Tue, 20 Sep 2011 15:23:04 -0500

Mapping the opregion non-cacheable fails, so use acpi_os_ioremap
instead.

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

17/17 [
Author: Tom Zanussi
Email: tom.zanussi@intel.com
Subject: drm-psb: change udelay to mdelay in intel_wait_for_vblank()
Date: Tue, 13 Mar 2012 16:34:13 -0500

This fixes the compile error>

ERROR: "__bad_udelay" [drivers/gpu/drm-psb/psb.ko] undefined!

This is the same fix as in gma500:

  commit 243dd2809a5edd2e0e3e62781083aa44049af37d
  Author: Stephen Rothwell <sfr@canb.auug.org.au>
  Date:   Mon Jul 25 15:18:44 2011 +1000

    gma500: udelay(20000) it too long again

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>