watchdog: add watchdog driver for Intel Quark
1/9 [
Author: Alexander Stein
Email: alexander.stein@systec-electronic.com
Subject: watchdog: Add watchdog driver for Intel Atom E6XX
Date: Thu, 10 May 2012 16:37:43 +0200

Add driver for the watchdog timer built into the
Intel Atom E6XX (TunnelCreek) processor.

commit 101ce87b3bdd5352edceb5a079e765685c13dbc3 upstream

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

2/9 [
Author: Randy Dunlap
Email: rdunlap@xenotime.net
Subject: watchdog: ie6xx_wdt.c: fix printk format warning
Date: Fri, 11 May 2012 18:33:31 -0700

Fix printk format warning; use cast to u64 since resource_size_t can
be either u32 or u64.

drivers/watchdog/ie6xx_wdt.c:261:4: warning: format '%x' expects type 'unsigned int', but argument 3 has type 'resource_size_t'

commit 744f6f4d3db2e9f153c9381b169aaee5c6ad4187 upstream

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

3/9 [
Author: Randy Dunlap
Email: rdunlap@xenotime.net
Subject: watchdog: ie6xx_wdt needs io.h
Date: Mon, 14 May 2012 13:14:29 -0700

Fix build error by including <linux/io.h>:

drivers/watchdog/ie6xx_wdt.c:97:2: error: implicit declaration of function 'outb'
drivers/watchdog/ie6xx_wdt.c:133:2: error: implicit declaration of function 'outl'
drivers/watchdog/ie6xx_wdt.c:161:2: error: implicit declaration of function 'inb'
drivers/watchdog/ie6xx_wdt.c:199:3: error: implicit declaration of function 'inl'
drivers/watchdog/ie6xx_wdt.c:203:3: error: implicit declaration of function 'inw'

commit 491d9e2a5f0e845a91ef53065afb4805a668d80d upstream

Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

4/9 [
Author: Gerard Snitselaar
Email: dev@snitselaar.org
Subject: watchdog: ie6xx_wdt: section mismatch in ie6xx_wdt_probe()
Date: Wed, 4 Jul 2012 09:32:11 -0700

ie6xx_wdt_probe() calls ie6xx_wdt_debugfs_exit() as part of
it's error cleanup path, and ie6xx_wdt_debugfs_exit() is
currently annotated __devexit.

commit 0402450f45673d3c03340cb1e679bf2a1fc0abee upstream

Signed-off-by: Gerard Snitselaar <dev@snitselaar.org>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

5/9 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: watchdog: remove use of __devexit_p
Date: Mon, 19 Nov 2012 13:21:12 -0500

CONFIG_HOTPLUG is going away as an option so __devexit_p is no longer
needed.

part of commit 82268714bdf06bc06135efb707a9de590ab2d294 upstream

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Wim Van Sebroeck <wim@iguana.be>
Cc: Wan ZongShun <mcuos.com@gmail.com>
Cc: Ben Dooks <ben-linux@fluff.org>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[ME: kept only parts applicable to ie6xx_wdt driver]
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

6/9 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: watchdog: remove use of __devinit
Date: Mon, 19 Nov 2012 13:21:41 -0500

CONFIG_HOTPLUG is going away as an option so __devinit is no longer
needed.

part of commit 2d991a164a61858012651e13c59521975504e260 upstream

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Wim Van Sebroeck <wim@iguana.be>
Cc: Wan ZongShun <mcuos.com@gmail.com>
Cc: Ben Dooks <ben-linux@fluff.org>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[ME: kept only parts applicable to ie6xx_wdt driver]
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

7/9 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: watchdog: remove use of __devexit
Date: Mon, 19 Nov 2012 13:26:24 -0500

CONFIG_HOTPLUG is going away as an option so __devexit is no
longer needed.

part of commit 4b12b896c27c3b54592816606679f5b02f638930 upstream

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Wim Van Sebroeck <wim@iguana.be>
Cc: Wan ZongShun <mcuos.com@gmail.com>
Cc: Ben Dooks <ben-linux@fluff.org>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[ME: kept only parts applicable to ie6xx_wdt driver]
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

8/9 [
Author: Jean Delvare
Email: jdelvare@suse.de
Subject: watchdog: Get rid of MODULE_ALIAS_MISCDEV statements
Date: Mon, 21 Oct 2013 17:38:49 +0200

I just can't find any value in MODULE_ALIAS_MISCDEV(WATCHDOG_MINOR)
and MODULE_ALIAS_MISCDEV(TEMP_MINOR) statements.

Either the device is enumerated and the driver already has a module
alias (e.g. PCI, USB etc.) that will get the right driver loaded
automatically.

Or the device is not enumerated and loading its driver will lead to
more or less intrusive hardware poking. Such hardware poking should be
limited to a bare minimum, so the user should really decide which
drivers should be tried and in what order. Trying them all in
arbitrary order can't do any good.

On top of that, loading that many drivers at once bloats the kernel
log. Also many drivers will stay loaded afterward, bloating the output
of "lsmod" and wasting memory. Some modules (cs5535_mfgpt which gets
loaded as a dependency) can't even be unloaded!

If defining char-major-10-130 is needed then it should happen in
user-space.

part of commit 487722cf2d66126338217896642bd5eec832c34b upstream

Signed-off-by: Jean Delvare <jdelvare@suse.de>
Acked-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
Cc: Stephen Warren <swarren@wwwdotorg.org>
Cc: Mike Frysinger <vapier.adi@gmail.com>
Cc: Wan ZongShun <mcuos.com@gmail.com>
Cc: Ben Dooks <ben-linux@fluff.org>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Cc: Zwane Mwaikambo <zwane@arm.linux.org.uk>
Cc: Jim Cromie <jim.cromie@gmail.com>
[ME: kept only parts applicable to ie6xx_wdt driver]
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

9/9 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: watchdog: Drop unnecessary include of miscdevice.h
Date: Tue, 19 Nov 2013 13:26:17 -0800

After commit 487722cf2 (watchdog: Get rid of MODULE_ALIAS_MISCDEV
statements) the affected drivers no longer need to include miscdevice.h.
Only exception is rt2880_wdt.c which never needed it.

part of commit 9539210e17dc09ea1472076c297d461c7507a5bb upstrean

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Reviewed-by: Jean Delvare <jdelvare@suse.de>
Signed-off-by: Wim Van Sebroeck <wim@iguana.be>
[ME: kept only parts applicable to ie6xx_wdt driver]
Signed-off-by: Mihai Ene <mihai.ene@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>