LTT & LTTNG2: integration fix
CQID: WIND00360558

1/1 [
Author: Paul Barrette
Email: paul.barrette@windriver.com
Subject: LTTNG2: fix compilation issue for 64bit targets.
Date: Wed, 11 Jul 2012 15:37:01 -0400

vsyscall_64.c calls _trace_clock_is_sync even if
CONFIG_HAVE_TRACE_CLOCK is not defined.  The result is:

linux/arch/x86/kernel/vsyscall_64.c:124: undefined reference to
`_trace_clock_is_sync'

cf: arch/x86/kernel/Makefile:
	obj-$(CONFIG_X86_64)	+= vsyscall_64.o
	....
	obj-$(CONFIG_HAVE_TRACE_CLOCK)	+= trace-clock.o

Added the appropriate ifdefs to make sure _trace_clock_is_sync is not
referenced.  This fix is only required for 64bit compilations.

Signed-off-by: Paul Barrette <paul.barrette@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>