fsl-t2xxx: usb gadget driver update
1/14 [
Author: Suresh Gupta
Email: suresh.gupta@freescale.com
Subject: fsl/usb: Add FSL USB Gadget entry in platform device id table
Date: Sun, 14 Apr 2013 19:54:53 +0530

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add FSL USB Gadget entry in platform device id table

Signed-off-by: Suresh Gupta <suresh.gupta@freescale.com>
Change-Id: Iacef40798e9c0fe4e73da8ff871db9051fb30da3
Reviewed-on: http://git.am.freescale.net:8181/1302
Reviewed-by: Mehresh Ramneek-B31383 <ramneek.mehresh@freescale.com>
Reviewed-by: Li Yang-R58472 <LeoLi@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

2/14 [
Author: Suresh Gupta
Email: suresh.gupta@freescale.com
Subject: fsl/usb: Turn on cache snooping hardware for 64-bit Kernel
Date: Sun, 14 Apr 2013 20:25:46 +0530

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Turn on cache snooping hardware for 64-bit Kernel

Signed-off-by: Suresh Gupta <suresh.gupta@freescale.com>
Change-Id: I1f59eb6a53fd420cda87873bec0ec82094a022de
Reviewed-on: http://git.am.freescale.net:8181/1320
Reviewed-by: Mehresh Ramneek-B31383 <ramneek.mehresh@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

3/14 [
Author: Suresh Gupta
Email: suresh.gupta@freescale.com
Subject: fsl/usb: Add NULL entry in platform_device_id
Date: Fri, 26 Apr 2013 13:02:38 +0530

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Gadget compilation breaks without terminated NULL entry in platform_device_id

Signed-off-by: Suresh Gupta <suresh.gupta@freescale.com>
Change-Id: I5821f0bf73a3cdfdb7988079ac97237e9a3f5f8b
Reviewed-on: http://git.am.freescale.net:8181/2124
Reviewed-by: Li Yang-R58472 <LeoLi@freescale.com>
Reviewed-by: Mehresh Ramneek-B31383 <ramneek.mehresh@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
]

4/14 [
Author: Suresh Gupta
Email: suresh.gupta@freescale.com
Subject: USB: Gadget: fsl: Set dma_ops for FSL USB Gadget Device
Date: Fri, 28 Feb 2014 23:00:48 +0530

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Signed-off-by: Suresh Gupta <suresh.gupta@freescale.com>
Change-Id: Ia9191415666afc968e6b29259730eafc8d0e0bdb
Reviewed-on: http://git.am.freescale.net:8181/9366
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

5/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers/usb : Port USB EHCI Gadget driver for LS102XA
Date: Mon, 2 Jun 2014 18:38:47 +0530

Change raw read/write accessors to ioread/writebe32 for big endian registers

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I75e181fc235f40aba7aa0d9db8f18c0783b04f82
Reviewed-on: http://git.am.freescale.net:8181/21818
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Zhengxiong Jin <Jason.Jin@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

6/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers/usb : Remove compilation error for usb EHCI gadget
Date: Mon, 2 Jun 2014 16:50:27 +0530

Remove compilation errors from USB EHCI gadget driver

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: Ie0ad80495ab16fe8537e544113dde806c790ff05
Reviewed-on: http://git.am.freescale.net:8181/21819
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Zhengxiong Jin <Jason.Jin@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

7/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers: usb: Introduce FSL_USB2_PHY_UTMI_DUAL for usb gadget
Date: Tue, 9 Dec 2014 18:51:34 +0530

Introduce FSL_USB2_PHY_UTMI_DUAL in gadget driver for setting
phy in SOCs with utmi dual phy

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I2c53b89d9916bd17b5be8b5d9e32454943172d55
Reviewed-on: http://git.am.freescale.net:8181/25528
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Suresh Gupta <suresh.gupta@freescale.com>
Reviewed-by: Matthew Weigel <Matthew.Weigel@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

8/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers: usb: fsl: Turn on cache snooping hardware in usb gadget
Date: Tue, 9 Dec 2014 19:00:32 +0530

Turn on cache snooping hardware in usb gadget for PPC 64-bit Kernel

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: Iaa4049a6bde66038a99f8d716a983c7c41ae4594
Reviewed-on: http://git.am.freescale.net:8181/25529
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Suresh Gupta <suresh.gupta@freescale.com>
Reviewed-by: Matthew Weigel <Matthew.Weigel@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

9/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers:usb:fsl: Check memory resource before releasing it
Date: Mon, 11 May 2015 13:15:18 +0530

Check memory resource existence before releasing it to avoid NULL
pointer dereference

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I1f34b13e1669a3271250205c788e74b3228477e8
Reviewed-on: http://git.am.freescale.net:8181/36193
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

10/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers:usb:fsl: Remove unused variable
Date: Mon, 11 May 2015 13:19:09 +0530

Remove unused variable td_complete

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I5e16b5ff77577db19ddd5f231603aba78bbaaa6d
Reviewed-on: http://git.am.freescale.net:8181/36195
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

11/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers:usb:fsl: Correct endpoint name checking
Date: Mon, 11 May 2015 17:21:27 +0530

Endpoint name being statically defined cannot be NULL
hence checking name's first two character with "ep" for
endpoint validity

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I1fc6b71fce4807fdc18a96db0182c15dd9e3c649
Reviewed-on: http://git.am.freescale.net:8181/36196
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

12/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers:usb:fsl: Compile out USB clk functions
Date: Mon, 11 May 2015 17:48:31 +0530

Compile out USB clk functions for PPC platforms as there is no usb clk
specific initialization on any of these platforms

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I766a30c6584b56d7105f7c080440ba5acb3f62a8
Reviewed-on: http://git.am.freescale.net:8181/36197
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

13/14 [
Author: Nikhil Badola
Email: nikhil.badola@freescale.com
Subject: drivers: usb: gadget: Correct NULL pointer checking in fsl gadget
Date: Tue, 9 Jun 2015 16:47:17 +0530

Correct NULL pointer checking for endpoint descriptor
before it gets dereferenced

Signed-off-by: Nikhil Badola <nikhil.badola@freescale.com>
Change-Id: I449d00d49f2ae842aa256907021b95b7885ccaf5
Reviewed-on: http://git.am.freescale.net:8181/37641
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Ramneek Mehresh <ramneek.mehresh@freescale.com>
Reviewed-by: Honghua Yin <Hong-Hua.Yin@freescale.com>
[Yang: Original patch taken from
QorIQ-SDK-V1.8-SOURCE-20150619-yocto.iso]
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

14/14 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drivers: usb: gadget: Avoid dereferencing a NULL pointer for fsl gadget driver
Date: Sat, 17 Oct 2015 07:15:24 +0000

In upstream commit 304f7e5e1d08 ("usb: gadget: Refactor request completion"),
usb subsystem use "usb_gadget_giveback_request" instead of "req->req.complete".
In usb_gadget_giveback_request, will reference complete function by calling
"req->complete(ep, req)".But in fsl_udc driver, when ep0_prime_status enqueue
a fsl_req request, the function req->req.complete will be assign to NULL. So
should add a pointer check to avoid NULL pointer reference, or it will occurr
calltrace as below:

Unable to handle kernel paging request for data at address 0x00000000
Faulting instruction address: 0x800000000043f02c
Oops: Kernel access of bad area, sig: 11 [#1]
PREEMPT SMP NR_CPUS=8 CoreNet Generic
Modules linked in: g_mass_storage usb_f_mass_storage libcomposite configfs fsl_usb2_udc udc_core
CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.1.10-WR8.0.0.0_standard #4
task: c000000075300000 ti: c00000007ffa8000 task.ti: c0000000752fc000
NIP: 800000000043f02c LR: 80000000004aad5c CTR: 800000000043f000
REGS: c00000007ffab7c0 TRAP: 0300   Not tainted  (4.1.10-WR8.0.0.0_standard)
MSR: 0000000080029000 <CE,EE,ME>  CR: 24042224  XER: 00000000
DEAR: 0000000000000000 ESR: 0000000000000000 SOFTE: 0
GPR00: 80000000004aad5c c00000007ffaba40 8000000000449808 c000000077539800
GPR04: c0000000789ca300 0000000000000000 0000000000008000 0000000000000000
GPR08: 0000000000000000 0000000000000000 c00000007ffa8000 80000000004adf78
GPR12: 800000000043f000 c00000000fffc6c0 c0000000769bb040 80000000004af410
GPR16: c00000007756f000 0000000000000001 c0000000775397e8 0000000000000001
GPR20: 0000000000000000 0000000000000040 0000000000000001 0000000000010001
GPR24: 0000000000000000 c00000007756f260 0000000000000080 c00000007756f000
GPR28: c000000077539800 c0000000789ca300 c0000000769bb040 0000000000000001
NIP [800000000043f02c] .usb_gadget_giveback_request+0x2c/0x50 [udc_core]
LR [80000000004aad5c] .done+0x114/0x17c [fsl_usb2_udc]
Call Trace:
[c00000007ffaba40] [c000000000a8bc24] ._raw_spin_unlock+0x44/0xd0 (unreliable)
[c00000007ffabac0] [80000000004aad5c] .done+0x114/0x17c [fsl_usb2_udc]
[c00000007ffabb60] [80000000004acf98] .fsl_udc_irq+0x38c/0xfb4 [fsl_usb2_udc]
[c00000007ffabc70] [c0000000000af50c] .handle_irq_event_percpu+0xbc/0x378
[c00000007ffabd70] [c0000000000af828] .handle_irq_event+0x60/0xa0
[c00000007ffabe00] [c0000000000b3ca0] .handle_fasteoi_irq+0x108/0x2c8
[c00000007ffabe90] [c0000000000ae7b8] .generic_handle_irq+0x54/0x78
[c00000007ffabf10] [c000000000006968] .__do_irq+0x9c/0x218
[c00000007ffabf90] [c000000000016018] .call_do_irq+0x14/0x24
[c0000000752ff980] [c000000000006bac] .do_IRQ+0xc8/0x150
[c0000000752ffa30] [c00000000001a93c] exc_0x500_common+0xfc/0x100

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>