powerpc/fsl-e500mc: fix a compiling error
CQID: WIND00325693

1/1 [
Author: Tiejun Chen
Email: tiejun.chen@windriver.com
Subject: powerpc/fsl-e500mc: fix a compiling error
Date: Mon, 10 Dec 2012 12:05:38 +0800

[
This should be squashed into my previous commit in our tree:

commit 1c12f8f3b72b56c31e195dada8a16a5e6a4574e6

    book3e/kexec/kdump: introduce a kexec kernel flag
]

|   CC      arch/powerpc/platforms/85xx/p4080_ds_mdio.o
| arch/powerpc/platforms/85xx/smp.c: In function 'smp_85xx_kick_cpu':
| arch/powerpc/platforms/85xx/smp.c:177:17: error: unused variable 'ptr' [-Werror=unused-variable]
| cc1: all warnings being treated as errors
| make[4]: *** [arch/powerpc/platforms/85xx/smp.o] Error 1
| make[4]: *** Waiting for unfinished jobs....
| make[3]: *** [arch/powerpc/platforms/85xx] Error 2
| make[2]: *** [arch/powerpc/platforms] Error 2
| make[1]: *** [sub-make] Error 2
| make: *** [all] Error 2
| ERROR: oe_runmake failed

That variable should only be valid for !PPC32.

Signed-off-by: Tiejun Chen <tiejun.chen@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>