dpio/qbman_portal: simplify logical expression
Issue: LIN8-3867, LIN8-3869

1/8 [
Author: Krzysztof Kozlowski
Email: k.kozlowski.k@gmail.com
Subject: i2c: constify platform_device_id
Date: Sat, 2 May 2015 00:54:25 +0900

commit e9a02a3d89b9d16eafc540d1dc78476a3bb5d4eb upstream

The platform_device_id is not modified by these drivers and core uses it
as const.

Signed-off-by: Krzysztof Kozlowski <k.kozlowski.k@gmail.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/8 [
Author: Gao Pan
Email: b54642@freescale.com
Subject: i2c: imx: implement bus recovery
Date: Fri, 23 Oct 2015 20:28:54 +0800

commit 1c4b6c3bcf30d0804db0d0647d8ebeb862c6f7e5 upstream

Implement bus recovery methods for i2c-imx so we can recover from
situations where SCL/SDA are stuck low.

Once i2c bus SCL/SDA are stuck low during transfer, config the i2c
pinctrl to gpio mode by calling pinctrl sleep set function, and then
use GPIO to emulate the i2c protocol to send nine dummy clock to recover
i2c device. After recovery, set i2c pinctrl to default group setting.

Signed-off-by: Fugang Duan <B38611@freescale.com>
Signed-off-by: Gao Pan <b54642@freescale.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

3/8 [
Author: Fabio Estevam
Email: fabio.estevam@freescale.com
Subject: i2c: imx: Use -ENXIO as error in the NACK case
Date: Thu, 22 Oct 2015 14:41:20 -0200

commit 4c0657ae432398f729c1d402bab935505a5255b5 upstream

According to Documentation/i2c/fault-codes the response to a bus NACK
should be -ENXIO, so fix the error code.

Signed-off-by: Fabio Estevam <fabio.estevam@freescale.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

4/8 [
Author: Hou Zhiqiang
Email: Zhiqiang.Hou@freescale.com
Subject: i2c: imx: fix a compiling error
Date: Tue, 17 Nov 2015 17:53:18 +0800

commit 8bb6fd585d419d906fb3c228db47fbc4e4272a00 upstream

drivers/i2c/busses/i2c-imx.c:978:2: error: implicit declaration of
function ‘pinctrl_select_state’ [-Werror=implicit-function-declaration]
  pinctrl_select_state(i2c_imx->pinctrl, i2c_imx->pinctrl_pins_gpio);
  ^

Signed-off-by: Hou Zhiqiang <Zhiqiang.Hou@freescale.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

5/8 [
Author: Gao Pan
Email: b54642@freescale.com
Subject: i2c: imx: init bus recovery info before adding i2c adapter
Date: Wed, 9 Dec 2015 11:08:22 +0800

commit a5f650182bcf956b2b0341575e8bff01e402224f upstream

During driver probe, i2c_imx_init_recovery_info() must come before
i2c_add_numbered_adapter(), because the get/set_scl() functions
are assigned in i2c_register_adapter() under the conditon that bus
recover_info are initialized. Otherwise, get/set_scl() function
pointers never get assigned.

In such case, when i2c_generic_gpio_recovery() is used for bus recovery,
there will be kernel crash because bri->set_scl is NULL.

The solution to this bug is moving i2c_imx_init_recovery_info() before
i2c_register_adapter().

Signed-off-by: Gao Pan <b54642@freescale.com>
Signed-off-by: Fugang Duan <B38611@freescale.com>
Acked-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Cc: stable@kernel.org
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

6/8 [
Author: Gao Pan
Email: b54642@freescale.com
Subject: i2c: imx: add runtime pm support to improve the performance
Date: Fri, 11 Dec 2015 10:24:09 +0800

commit 588eb93ea49f672cb3ff55d0a5c34df3e1afa7ec upstream

In our former i2c driver, i2c clk is enabled and disabled in
xfer function, which contributes to power saving. However,
the clk enable process brings a busy wait delay until the core
is stable. As a result, the performance is sacrificed.

To weigh the power consumption and i2c bus performance, runtime
pm is the good solution for it. The clk is enabled when a i2c
transfer starts, and disabled after a specifically defined delay.

If CONFIG_PM is disabled the net result of this patch is that the
clock is never disabled.

Without the patch the test case (many eeprom reads) executes with approx:
real 1m7.735s
user 0m0.488s
sys 0m20.040s

With the patch the same test case (many eeprom reads) executes with approx:
real 0m54.241s
user 0m0.440s
sys 0m5.920s

Signed-off-by: Fugang Duan <B38611@freescale.com>
Signed-off-by: Gao Pan <b54642@freescale.com>
Acked-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
[wsa: sorted includes]
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

7/8 [
Author: Oleksij Rempel
Email: linux@rempel-privat.de
Subject: i2c: imx: reduce load by using usleep_range instead of udelay
Date: Tue, 26 Apr 2016 08:27:46 +0200

commit 2b899f34e1db9adef8716d07e872a800dfa60790 upstream

Documentation/timers/timers-howto.txt recommends to use
usleep_range on delays > 10usec. According to my test results
with Neonode zForce touchscreen driver, usleep_range indeed
reduces CPU load.

Stats collected with "./perf record -a -g -F 1000 sleep 10"

i2c-imx with udelay(50):
34.19% 0.00% irq/220-Neonode [kernel.kallsyms] [k] irq_thread
    ---irq_thread
       |--33.75%--irq_thread_fn
       |    |--19.27%--0x7f08a878
       |    |     i2c_master_recv
       |    |     i2c_transfer
       |    |     __i2c_transfer
       |    |     i2c_imx_xfer
       |    |     |--11.71%--i2c_imx_trx_complete
       |    |     |--5.70%--i2c_imx_start <<<<----------------
       |    |     |     |--5.38%--__timer_const_udelay
       |    |     |     |      __timer_delay
       |    |     |     |      --5.07%--read_current_timer

i2c-imx with usleep_range(50,100)
29.08% 0.00% irq/220-Neonode  [kernel.kallsyms] [k] irq_thread
    ---irq_thread
       |--28.89%--irq_thread_fn
       |    |--17.21%--0x7f08a878
       |    |     i2c_master_recv
       |    |     |--17.14%--i2c_transfer
       |    |     |     __i2c_transfer
       |    |     |     i2c_imx_xfer
       |    |     |     |--14.29%--i2c_imx_trx_complete
       |    |     |     |--1.42%--i2c_imx_start <<<<----------
       |    |     |     |      |--0.71%--usleep_range
       |    |     |     |      |--0.53%--i2c_imx_bus_busy

Signed-off-by: Oleksij Rempel <linux@rempel-privat.de>
Signed-off-by: Dirk Behme <dirk.behme@de.bosch.com>
Reviewed-by: Vladimir Zapolskiy <vladimir_zapolskiy@mentor.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

8/8 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: dpio/qbman_portal: simplify logical expression
Date: Mon, 13 Jun 2016 14:20:22 +0800

fsl-mc/bus/dpio/qbman_portal.c:242:22: warning: logical not is only applied to
the left hand side of comparison [-Wlogical-not-parentheses]
  BUG_ON(!p->mc.check != swp_mc_can_submit);
                        ^

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>