Revert "mips/nlm_xlp_64_be: enable NAE in the 2nd kernel booted by kexec"
This reverts commit f717c2c74754763331602c3dce913864248e4405.

Jin Yanjiang says he will resend.

The error that was produced for both standard and cgl ktypes of
nlm_xlp_64_be bsp:

arch/mips/include/asm/kexec.h: In function 'crash_setup_regs':
arch/mips/include/asm/kexec.h:30: error: implicit declaration of
function 'memcpy'
--
arch/mips/include/asm/string.h: At top level:
arch/mips/include/asm/string.h:138: error: conflicting types for
'memcpy'
arch/mips/include/asm/kexec.h:30: note: previous implicit declaration of
'memcpy' was here