fsl-t2xxx: fix build failure with CONFIG_UIO=m
1/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: fsl/Rman: change rman kernel option from bool to tristate
Date: Thu, 3 Dec 2015 09:09:41 +0000

Because rman depends on UIO subsystem, when UIO is built as
kernel module, rman should be changed to module state too.
So change rman kernel option from bool to tristate or it will
occurr building error as below when CONFIG_UIO=m:

drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `fsl_rman_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:337: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `rman_ib_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:169: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `rman_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:144: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `fsl_rman_ib_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: fsl/uio: change UIO_FSL_SRAM kernel option from bool to tristate
Date: Thu, 3 Dec 2015 09:51:56 +0000

Because UIO_FSL_SRAM depends on UIO subsystem, when UIO is built as
kernel module, L2CACHE should be changed to module state too.
So change L2CACHE kernel option from bool to tristate.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>