ACPI, APEI: Fixup incorrect 16-bit access width firmware bug
Issue: OVP8-409

1/7 [
Author: Tony Luck
Email: tony.luck@intel.com
Subject: EDAC, pnd2_edac: Add new EDAC driver for Intel SoC platforms
Date: Thu, 9 Mar 2017 01:45:39 +0800

commit 5c71ad17f97e84d6d7e11a8e193d5d96890ed2ed upstream.

Initial target for this driver is the Intel Apollo Lake platform and
Denverton micro-server, they use the same internal memory controller IP
called Pondicherry2.

Memory controller registers are not in PCI config space like earlier
Intel memory controllers. For Apollo Lake platform they are accessed via
a "side-band" interface, for Denverton micro-server they are access via
PCI config space and memory map I/O. This driver is for Apollo Lake and
Denverton, but only the Denverton is fully enabled while we wait for the
sideband driver.

Apollo lake driver and initial cut at Denverton driver by Tony Luck.
Extensive cleanup, refactoring and basic verification by Qiuxu Zhuo.

Signed-off-by: Tony Luck <tony.luck@intel.com>
Signed-off-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
Cc: linux-edac <linux-edac@vger.kernel.org>
Link: http://lkml.kernel.org/r/20170308174539.14432-1-qiuxu.zhuo@intel.com
Signed-off-by: Borislav Petkov <bp@suse.de>
[adjust patch for edac_mc.h header file missing and function changed]
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

2/7 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC, pnd2_edac: Fix !EDAC_DEBUG build
Date: Sat, 18 Mar 2017 18:26:34 +0100

commit cd1be315ac9766fe83e4fb788d5d9fe032a9b877 upstream.

Provide debugfs function stubs when EDAC_DEBUG is not enabled so that we
don't fail the build:

  drivers/edac/pnd2_edac.c: In function ‘pnd2_init’:
  drivers/edac/pnd2_edac.c:1521:2: error: implicit declaration of function ‘setup_pnd2_debug’ [-Werror=implicit-function-declaration]
    setup_pnd2_debug();
    ^
  drivers/edac/pnd2_edac.c: In function ‘pnd2_exit’:
  drivers/edac/pnd2_edac.c:1529:2: error: implicit declaration of function ‘teardown_pnd2_debug’ [-Werror=implicit-function-declaration]
    teardown_pnd2_debug();
    ^

Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

3/7 [
Author: Qiuxu Zhuo
Email: qiuxu.zhuo@intel.com
Subject: EDAC, pnd2_edac: Fix reported DIMM number
Date: Sat, 25 Mar 2017 19:29:01 +0800

commit 819f60fb7db169d851186d04e571e9bca27321e8 upstream.

DIMM number passed to edac_mc_handle_error() was accidentally hardcoded
to zero. Pass in the correct daddr->dimm value.

Signed-off-by: Qiuxu Zhuo <qiuxu.zhuo@intel.com>
Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

4/7 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC: Select DEBUG_FS
Date: Sat, 18 Mar 2017 18:25:05 +0100

commit 1c5bf78114d38c2761721108a2d925bccb496027 upstream.

The debugfs.c functionality relies on DEBUG_FS so select it.

Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

5/7 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC: Carve out debugfs functionality
Date: Tue, 22 Sep 2015 11:56:04 +0200

commit 7ac8bf9bc9ba82aea763ef30671a34c6a2a39922 upstream.

... into a separate compilation unit and drop a couple of
CONFIG_EDAC_DEBUG ifdefferies. Rename edac_create_debug_nodes() to
edac_create_debugfs_nodes(), while at it.

No functionality change.

Cc: <linux-edac@vger.kernel.org>
Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

6/7 [
Author: Borislav Petkov
Email: bp@suse.de
Subject: EDAC: Add debugfs wrappers
Date: Tue, 22 Sep 2015 12:16:05 +0200

commit 4397bcb4fa1dd285a2c6d583d1f1cbc6bd423f97 upstream.

Later patches will convert EDAC users to those.

Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

7/7 [
Author: Liwei Song
Email: liwei.song@windriver.com
Subject: ACPI, APEI: Fixup incorrect 16-bit access width firmware bug
Date: Wed, 19 Jul 2017 23:05:26 -0400

This is a follow up to commit f712c71f7b2b ("ACPI, APEI: Fixup common
access width firmware bug") fix the following firmware bug:

[Firmware Bug]: APEI: Invalid bit width + offset in GAR [0xb2/16/0/1/1]

This is due to an 8-bit access width is specified for a 16-bit register,
Do bit_width check just like what the original commit have done.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>