lttng: sync up the definition of mm_compaction_migratepages with v3.14.24
Issue: LIN7-2957

1/1 [
Author: Yue Tao
Email: Yue.Tao@windriver.com
Subject: lttng: sync up the definition of mm_compaction_migratepages with v3.14.24
Date: Thu, 12 Feb 2015 13:12:15 +0800

A upstream commit f8c9301fa is backported to the stable tree
linux-3.14.24 as 41c9323cf1, in which the definition of
mm_compaction_migratepages has been changed, which cause the lttng build
failed, so sync up the definition with v3.14.24. The build failure is

/../instrumentation/events/lttng-module/../../../probes/lttng-events.h:151:6:
error: conflicting types for 'trace_mm_compaction_migratepages'
...
...
...
include/linux/tracepoint.h:168:21:
note: previous definition of 'trace_mm_compaction_migratepages' was here

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>