genirq: Export irq_set_chip_and_handler_name()
CQID: WIND00438191

1/1 [
Author: Kuninori Morimoto
Email: kuninori.morimoto.gx@renesas.com
Subject: genirq: Export irq_set_chip_and_handler_name()
Date: Thu, 10 Oct 2013 12:11:40 +0800

commit b3ae66f209e8929db62b5a5f874ab2cdcf5ef1d4	upstream

Export irq_set_chip_and_handler_name() to modules to allow them to
do things such as

	irq_set_chip_and_handler(....);

This fixes

	ERROR: "irq_set_chip_and_handler_name" \
	          [drivers/gpio/gpio-pcf857x.ko] undefined!

when gpio-pcf857x.c is being built as a module.

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Cc: Linus Walleij <linus.walleij@linaro.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Greg KH <gregkh@linuxfoundation.org>
Link: http://lkml.kernel.org/r/873948trpk.wl%25kuninori.morimoto.gx@renesas.com
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>