Sustaining merge
CQID:WIND00196927

1/1 [
Author: fgeng
Email: fei.geng@windriver.com
Subject: hrtimers: allow the hot unplugging of all cpus.
Date: Tue, 16 Mar 2010 15:43:15 +0800

Impact: fix CPU hotplug hang on Power6 testbox.

commit 94df7de0289bc2df3d6e85cd2ece52bf42682f45 upstream

On architectures that support offlining all cpus (at least powerpc/pseries),
hot-unpluging the tick_do_timer_cpu can result in a system hang.

This comes from the fact that if the cpu going down happens to be the
cpu doing the tick, then as the tick_do_timer_cpu handover happens after the
cpu is dead (via the CPU_DEAD notification), we're left without ticks,
jiffies are frozen and any task relying on timers (msleep, ...) is stuck.
That's particularly the case for the cpu looping in __cpu_die() waiting
for the dying cpu to be dead.

This patch addresses this by having the tick_do_timer_cpu handover happen
earlier during the CPU_DYING notification. For this, a new clockevent
notification type is introduced (CLOCK_EVT_NOTIFY_CPU_DYING) which is triggered
in hrtimer_cpu_notify().

Signed-off-by: Sebastien Dugue <sebastien.dugue@bull.net>
Cc: <stable@kernel.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Integrated-by: fgeng <fei.geng@windriver.com>
]

CQID:WIND00202733

1/1 [
Author: GengFei
Email: fei.geng@windriver.com
Subject: tracing/markers: make markers select tracepoints
Date: Tue, 16 Mar 2010 15:00:19 +0800

Impact: make markers select tracepoints

commit 91f73f90d97fa67effbb49e0a79c50cf26dfe324 upstream

    Sometimes it happens that KConfig dependencies are not handled
    like in the following scenario:

    - config A
       bool

    - config B
       bool
       depends on A

    - config C
       bool
       select B

    If one selects C, then it will select B without checking its
    dependency to A, if A hasn't been selected elsewhere, it will
    result in a build failure.

    This is what happens on the following build error:

     kernel/built-in.o: In function `marker_update_probe_range':
     (.text+0x52f64): undefined reference to `tracepoint_probe_register_noupdate'
     kernel/built-in.o: In function `marker_update_probe_range':
     (.text+0x52f74): undefined reference to `tracepoint_probe_unregister_noupdate'
     kernel/built-in.o: In function `marker_update_probe_range':
     (.text+0x52fb9): undefined reference to `tracepoint_probe_unregister_noupdate'
     kernel/built-in.o: In function `marker_update_probes':
     marker.c:(.text+0x530ba): undefined reference to `tracepoint_probe_update_all'

    CONFIG_KVM_TRACE will select CONFIG_MARKER, but the latter
    depends on CONFIG_TRACEPOINTS which will not be selected.

    Reported-by: Ingo Molnar <mingo@elte.hu>
    Signed-off-by: Frederic Weisbecker <fweisbec@gmail.com>
    Signed-off-by: Ingo Molnar <mingo@elte.hu>
    Intergrated-by: GengFei <fei.geng@windriver.com>
]

CQID:WIND00203671

1/1 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: Fix a bug of Comcerto100's sys_timer offset function
Date: Wed, 24 Mar 2010 15:52:22 +0800

Use the systimer_mark to check if the current-count register was reloaded since
the last timer interrupt.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

CQID:WIND00203801

1/1 [
Author: Sachin Prabhu
Email: sprabhu@redhat.com
Subject: GFS2: Skip check for mandatory locks when unlocking
Date: Mon, 22 Mar 2010 00:04:53 +0800

commit 720e7749279bde0d08684b1bb4e7a2eedeec6394 from linux-next

gfs2_lock() will skip locks on file which have mode set to 02666. This is a problem in cases where the mode of the file is changed after a process has obtained a lock on the file. Such a lock will be skipped and will result in a BUG in locks_remove_flock().

gfs2_lock() should skip the check for mandatory locks when unlocking a file.

Signed-off-by: Sachin Prabhu <sprabhu@redhat.com>
Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>
]

CQID:WIND00201141

1/1 [
Author: Gleb Natapov
Email: gleb@redhat.com
Subject: KVM: Disable move to segment registers and jump far instructions.
Date: Tue, 2 Mar 2010 23:10:15 +0800

They are executed directly by HW and need to be emulated only in
big real mode which is not supported in RHEL5 anyway. On the other
hand the emulation doesn't check segment permission properly and
correct fix is to intrusive for RHEL5.

Message-Id: <1265817504-5121-3-git-send-email-gleb@redhat.com>
CVE: CVE-2010-0419
Bugzilla: 563464
Acked-by: Avi Kivity <avi@redhat.com>
Acked-by: Marcelo Tosatti <mtosatti@redhat.com>
Acked-by: Juan Quintela <quintela@redhat.com>
Signed-off-by: Gleb Natapov <gleb@redhat.com>
]

CQID:WIND00194508

1/1 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: Fix bugs of mxc nand flash driver
Date: Wed, 30 Dec 2009 11:04:12 +0800

If only spare data was considered and no error occurred on it, no more error
correct operations needed. Modify the error byte location logic and make the
col value more safe.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>