fix build errors after config fragment cleanup
commit 4db7ff9 "kernel_cache: intel BSP cfg fragment cleanup" resulted
in the following errors:

common_pc, cgl
drivers/gpu/drm/i915/i915_dma.c: In function 'i915_switcheroo_can_switch':
drivers/gpu/drm/i915/i915_dma.c:1425: error: invalid operands to binary == (have 'atomic_t' and 'int')

intel_atom_eg20t_pch, preempt_rt
intel_atom_eg20t_pch, standard
kbc_km2m806, standard
drivers/built-in.o:(.rodata+0x8fac): undefined reference to `cfb_fillrect'
drivers/built-in.o:(.rodata+0x8fb0): undefined reference to `cfb_copyarea'
drivers/built-in.o:(.rodata+0x8fb4): undefined reference to `cfb_imageblit'

CQID: WIND00290745

1/2 [
Author: Hui Wang
Email: Hui.Wang@windriver.com
Subject: drm/emgd: select fb helper functions for emgd
Date: Wed, 21 Sep 2011 14:25:21 +0800

Intel emgd drm driver needs fb helper functions, so we modify Kconfig
to select these fb helper functions for emgd driver automatically.

Signed-off-by: donn.seeley@windriver.com
Integrated-by: Hui Wang <Hui.Wang@windriver.com>
]

This second patch is squashed with "grsec: Integrate grsecurity and PaX
to CGL kernel".

2/2 [
Author: Hui Wang
Email: Hui.Wang@windriver.com
Subject: drm: cgl: atomic access to dev->open_count for i915 and nouveau
Date: Wed, 21 Sep 2011 14:25:22 +0800

Access to dev->open_count needs to be atomic to match the changes
introduced by pax / grsec.

Signed-off-by: Hui Wang <Hui.Wang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>