ipv6: correct dccp_doff to dccph_doff
Issue: LIN8-5984

1/1 [
Author: Qi Hou
Email: qi.hou@windriver.com
Subject: ipv6: correct dccp_doff to dccph_doff
Date: Wed, 8 Mar 2017 09:59:13 +0800

In struct dccp_hdr, there is no field named "dccp_doff" but a dccph_doff.

So correct the reference to dccp_doff to dccph_doff. Or there would be a
compile error, like below:

|kernel-source/net/dccp/ipv6.c:769:40: error: 'const struct dccp_hdr' has
 no member named 'dccp_doff'
|   return __sk_receive_skb(sk, skb, 1, dh->dccp_doff * 4) ? -1 : 0;
|                                         ^

It is introduced by commit 960570cea4fc ("tcp: take care of truncations
done by sk_filter()"). According to the changes made by this commit, it
seems that this commit has made by merging two commit commits from upstream
They are commit ac6e780070e30 ("tcp: take care of truncations done by
sk_filter()") and commit 4f0c40d94461 ("dccp: limit sk_filter trim to
payload").

In commit 960570cea4fc, "dccph_doff" was mistakenly written as "dccp_doff".
To fix it, correct "dccp_doff" to "dccph_doff".

Signed-off-by: Qi Hou <qi.hou@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>