fsl-b4xxx: fix several rt call trace problems
CQID: US18950

1/3 [
Author: Yongli He
Email: yongli.he@windriver.com
Subject: QMAN: QMAN preempt_rt call trace
Date: Thu, 16 Aug 2012 14:52:23 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 0, name: swapper
Call Trace:
[c000000000ae7540] [c00000000000a4a8] .show_stack+0x68/0x1b0 (unreliable)
[c000000000ae75f0] [c000000000039030] .__might_sleep+0x130/0x170
[c000000000ae7680] [c0000000007aec3c] .rt_spin_lock+0x3c/0xd0
[c000000000ae7700] [c0000000006a299c] .qman_create_fq+0xcc/0x830
[c000000000ae7800] [80000000002a90d4] .init_handler+0x84/0x180 [qman_tester]
[c000000000ae78d0] [c0000000000912c8] .generic_smp_call_function_single_interrupt+0x138/0x1d0
[c000000000ae7990] [c000000000023d94] .smp_message_recv+0x84/0x1b0
[c000000000ae7a20] [c00000000001bd64] .doorbell_exception+0x1a4/0x1c0
[c000000000ae7ad0] [c000000000017410] exc_doorbell_book3e+0x134/0x138
 --- Exception: 2071 at .book3e_idle+0x28/0x6c
    LR = .book3e_idle+0x28/0x6c
[c000000000ae7dc0] [c00000000000cb8c] .cpu_idle+0x10c/0x220 (unreliable)
[c000000000ae7e70] [c000000000001494] .rest_init+0xd4/0xc40
[c000000000ae7ef0] [c00000000095fcec] .start_kernel+0x460/0x480
[c000000000ae7f90] [c000000000000468] .start_here_common+0x1c/0x34

This is caused by lock fq_hash_table_lock in atomic context. atomic
context should be preserved so change spin lock to raw type.

Signed-off-by: Yongli He <yongli.he@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

2/3 [
Author: Yang Wei
Email: Wei.Yang@windriver.com
Subject: driver/dpaa: Fix a call trace of dpaa on rt kernel
Date: Thu, 1 Aug 2013 13:45:19 +0800

When activating the networking interface the following call trace is thrown:
BUG: sleeping function called from invalid context at kernel/rtmutex.c:646
in_atomic(): 0, irqs_disabled(): 1, pid: 1369, name: avahi-daemon
Call Trace:
[c0000001f9756d70] [c00000000000b074] .show_stack+0xe4/0x250 (unreliable)
[c0000001f9756e40] [c0000000008de570] .dump_stack+0x20/0x30
[c0000001f9756eb0] [c0000000000868cc] .__might_sleep+0x10c/0x160
[c0000001f9756f50] [c0000000008d35b4] .rt_spin_lock+0x34/0x90
[c0000001f9756fd0] [c00000000017c17c] .__kmalloc+0x12c/0x360
[c0000001f9757090] [c000000000661cc4] .xx_Malloc+0x44/0xa0
[c0000001f9757130] [c000000000661d40] .XX_Malloc+0x20/0x30
[c0000001f97571b0] [c0000000005d4084] .DtsecAddHashMacAddress+0xe4/0x280
[c0000001f9757270] [c0000000005dcf60] .FM_MAC_AddHashMacAddr+0x60/0x170
[c0000001f9757300] [c0000000008e99e4] .set_multi+0x134/0x28c
[c0000001f97573d0] [c0000000006639d8] .dpa_set_rx_mode+0x98/0x1a0
[c0000001f9757480] [c000000000796048] .__dev_set_rx_mode+0x98/0x100
[c0000001f9757510] [c00000000079c1c4] .__dev_mc_add+0x74/0xc0
[c0000001f97575b0] [c00000000079c27c] .dev_mc_add+0x2c/0x40
[c0000001f9757630] [c00000000081c828] .igmp_group_added+0x168/0x1b0
[c0000001f97576e0] [c00000000081ca50] .ip_mc_inc_group+0x1e0/0x330
[c0000001f9757780] [c00000000081cce4] .ip_mc_join_group+0x144/0x180
[c0000001f9757820] [c0000000007e1938] .do_ip_setsockopt.isra.10+0x558/0xf20
[c0000001f9757a80] [c0000000007e24bc] .ip_setsockopt+0x5c/0x110
[c0000001f9757b20] [c00000000080bad8] .udp_setsockopt+0x58/0x80
[c0000001f9757bd0] [c000000000777910] .sock_common_setsockopt+0x60/0x80
[c0000001f9757c70] [c000000000775fbc] .SyS_setsockopt+0xdc/0x250
[c0000001f9757d50] [c0000000007770a0] .SyS_socketcall+0x340/0x4d0
[c0000001f9757e30] [c000000000000598] syscall_exit+0x0/0x2c

Since spinlocks are sleepable on rt, it is not allowed to call them with interrupts
disabled. Therefore we use local_irq_save/restore_nort() instead of
local_irq_save/restore.

Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

3/3 [
Author: yhe
Email: yongli.he@windriver.com
Subject: fsl QMAN:Add QMAN_FQ_FLAG_FQSCB_NEED_SLP flag to qman_fq
Date: Wed, 19 Dec 2012 14:51:55 +0800

On preempt-rt kernel, during qman-self testing, sleepable spinlocks
introduce call trace:

BUG: sleeping function called from invalid context
at linux/kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 1, pid: 1430, name: modprobe
Call Trace:
[eae33db0] [c0007b10] show_stack+0x44/0x160 (unreliable)
[eae33de0] [c0034bb4] __might_sleep+0xe4/0x108
[eae33df0] [c0639d2c] rt_spin_lock+0x38/0xb4
[eae33e00] [c003a0cc] __wake_up+0x24/0x58
[eae33e20] [f955eee8] cb_fqs+0x54/0x70 [qman_tester]
[eae33e30] [c05637b8] qman_retire_fq+0x324/0x438
[eae33ea0] [f955f2f4] qman_test_high+0x1cc/0x2d8 [qman_tester]
[eae33ee0] [f955e018] test_init+0x14/0x2c [qman_tester]
[eae33ef0] [c0001d44] do_one_initcall+0x3c/0x1e0
[eae33f20] [c0085bb0] sys_init_module+0xf8/0x21c
[eae33f40] [c0010fc4] ret_from_syscall+0x0/0x4
    Exception: c00 at 0xff63564
    LR = 0x10003380

This is caused by the fqs callback function of qman_test_high
case involved a sleepable spinlock introduced by wake_up(), and the
callback is invoked from fqs_retire_fqs(), which implements a context
disabled preempt & irq.

The atomic context is used to protect key structure for qman driver.
While the callback of qman_test_high didn't touch such resource. So it
is free to invoke the callback outside the atomic context.

As result, the patch adds QMAN_FQ_FLAG_FQSCB_NEED_SLP  flag to qman_fq
structure. If the fqs callback function involves sleepable routine,
driver needs set the correspond bit when creating fq.

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>