pch_uart: add missing comment about OKI ML7223
1/11 [
Author: Alexander Stein
Email: alexander.stein@systec-electronic.com
Subject: pch_uart: add missing comment about OKI ML7223
Date: Thu, 1 Mar 2012 15:58:42 -0800

commit bff52fd458a1bca06266449b0ab8a43e9a50d240 upstream.

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Reviewed-by: Jesper Juhl <jj@chaosbits.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

2/11 [
Author: Tomoya MORINAGA
Email: tomoya-linux@dsn.okisemi.com
Subject: pch_uart: Set PCIe bus number using probe parameter
Date: Thu, 1 Mar 2012 15:58:43 -0800

commit 6c4b47d243112e98811ce0da7bbb32cc3857dd1a upstream.

Currently, PCIe bus number is set as fixed value "2".
However, PCIe bus number is not always "2".
This patch sets bus number using probe() parameter.

Signed-off-by: Tomoya MORINAGA <tomoya-linux@dsn.okisemi.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

3/11 [
Author: Jiri Slaby
Email: jslaby@suse.cz
Subject: TTY: serial, fix includes in some drivers
Date: Thu, 1 Mar 2012 15:58:44 -0800

commit ee160a38eee357ed2572cf41437d5814ce53c839 upstream.

linux/tty_flip.h is included in linux/serial_core.h. But this may (and
will) change in the future. Then we would get build errors such as:
.../tty/serial/max3107.c: In function ‘put_data_to_circ_buf’:
.../tty/serial/max3107.c:149:2: error: implicit declaration of function ‘tty_insert_flip_string’

So fix all the drviers which call tty flip buffer helpers to really
include linux/tty_flip.h. And also make sure that those include
linux/tty.h when operating with struct tty_struct.

Signed-off-by: Jiri Slaby <jslaby@suse.cz>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

4/11 [
Author: Tomoya MORINAGA
Email: tomoya-linux@dsn.lapis-semi.com
Subject: pch_uart: Change company name OKI SEMICONDUCTOR to LAPIS Semiconductor
Date: Thu, 1 Mar 2012 15:58:45 -0800

commit eca9dfa846a3d0eeb865e290851f4bfe4fb34fdd upstream.

On October 1 in 2011,
OKI SEMICONDUCTOR Co., Ltd. changed the company name in to LAPIS Semiconductor Co., Ltd.

Signed-off-by: Tomoya MORINAGA <tomoya-linux@dsn.lapis-semi.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

5/11 [
Author: Alexander Stein
Email: alexander.stein@systec-electronic.com
Subject: pch_uart: Add MSI support
Date: Thu, 1 Mar 2012 15:58:46 -0800

commit e463595fd9c752fa4bf06b47df93ef9ade3c7cf0 upstream.

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

6/11 [
Author: Alexander Stein
Email: alexander.stein@systec-electronic.com
Subject: drivers/tty/serial/pch_uart.c: add console support
Date: Thu, 1 Mar 2012 15:58:47 -0800

commit e30f867d402d6dcc2d03d8dd5da3863f7c83572a upstream.

Add console support to pch_uart.  To enable append e.g.
console=ttyPCH0,115200 to your kernel command line.

This is not expected work on CM-iTC boards due to their having a different
clock.

Signed-off-by: Alexander Stein <alexander.stein@systec-electronic.com>
Cc: Alan Cox <alan@lxorguk.ukuu.org.uk>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

7/11 [
Author: Uwe Kleine-König
Email: u.kleine-koenig@pengutronix.de
Subject: serial/pch: use global div helper instead of creating a private one
Date: Thu, 1 Mar 2012 15:58:48 -0800

commit 0e2adc06843a9b5a28af4ca5f796240297907897 upstream.

Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Acked-by: Alan Cox  <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>
]

8/11 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_uart: Use uartclk instead of base_baud
Date: Thu, 1 Mar 2012 15:58:49 -0800

The term "base baud" refers to the fastest baud rate the device can communicate
at. This is clock/16. pch_uart is using base_baud as the clock itself. Rename
the variables to be semantically correct.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
CC: Tomoya MORINAGA <tomoya.rohm@gmail.com>
CC: Feng Tang <feng.tang@intel.com>
CC: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CC: Alan Cox <alan@linux.intel.com>
CC: linux-serial@vger.kernel.org
]

9/11 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_uart: Add Fish River Island II uart clock quirks
Date: Thu, 1 Mar 2012 15:58:50 -0800

Add support for the Fish River Island II (FRI2) UART clock following the CM-iTC
quirk handling mechanism. Depending on the firmware installed on the device, the
FRI2 uses a 48MHz or a 64MHz UART clock. This is detected with DMI strings.

Add similar UART clock quirk handling to the pch_console_setup() function to
enable kernel messages on boards with non-standard UART clocks.

Per Alan's suggestion, abstract out UART clock selection into
pch_uart_get_uartclk() to avoid code duplication.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
CC: Tomoya MORINAGA <tomoya.rohm@gmail.com>
CC: Feng Tang <feng.tang@intel.com>
CC: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CC: Alan Cox <alan@linux.intel.com>
CC: linux-serial@vger.kernel.org
]

10/11 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_uart: Add user_uartclk parameter
Date: Thu, 1 Mar 2012 15:58:51 -0800

For cases where boards with non-default clocks are not yet added to the kernel
or when the clock varies across hardware revisions, it is useful to be
able to specify the UART clock on the kernel command line.

Add the user_uartclk parameter and prefer it, if set, to the default and
board specific UART clock settings. Specify user_uartclock on the command-line
with "pch_uart.user_uartclk=48000000".

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
CC: Tomoya MORINAGA <tomoya.rohm@gmail.com>
CC: Feng Tang <feng.tang@intel.com>
CC: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CC: Alan Cox <alan@linux.intel.com>
CC: linux-serial@vger.kernel.org
]

11/11 [
Author: Darren Hart
Email: dvhart@linux.intel.com
Subject: pch_uart: Use existing default_baud in setup_console
Date: Thu, 1 Mar 2012 15:58:52 -0800

Rather than hardcode 9600, use the existing default_baud parameter (which
also defaults to 9600).

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
CC: Tomoya MORINAGA <tomoya.rohm@gmail.com>
CC: Feng Tang <feng.tang@intel.com>
CC: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CC: Alan Cox <alan@linux.intel.com>
CC: linux-serial@vger.kernel.org
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>