bpf: fix build error for error for lack of bpf_binary_header
Issue: LIN6-10601

1/1 [
Author: Zhang Xiao
Email: xiao.zhang@windriver.com
Subject: bpf: fix build error for error for lack of bpf_binary_header
Date: Wed, 2 Dec 2015 09:50:59 +0800

Several upstream was introduced caused this build error:
arch/x86/net/bpf_jit_comp.c: In function 'bpf_jit_free_deferred':
arch/x86/net/bpf_jit_comp.c:758:28: error: dereferencing pointer to
incomplete type
  set_memory_rw(addr, header->pages);

The set_memory_rw here is not necessary since no one set it to ro
before. Remove it.

Signed-off-by: Zhang Xiao <xiao.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>