NXP: Add LS2021 patches
1/5 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: usb: dwc3: core: add the missing unified device interface replacement
Date: Sun, 9 Oct 2016 16:02:40 +0800

Reference the commit 3d128919b7e5 (usb: dwc3: core: convert to unified device
property interface), use the unified device interface to replace the
"of_property*" APIs, here add the missed ones and to fix below build error:

drivers/usb/dwc3/core.c:989:6: error: 'node' undeclared (first use in this function)
|   if (node && of_dma_is_coherent(node)) {
|       ^~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/5 [
Author: Miao Xiaowei
Email: B49897@freescale.com
Subject: kernel: LS1021AIOT support
Date: Tue, 27 Jan 2015 13:37:31 +0800

Upstream-Status: Pending

* Add dts/driver_fix for LS1021AIOT;
* Add ThinkEco dongle's pid & vid;

Signed-off-by: Miao Xiaowei <B49897@freescale.com>
[Xulin: Original patch taken from
Freescale-Linux-SDK-for-LS1021A-IOT-Rev2-v0.4-SOURCE-20150907-yocto.iso and
dropped defconfig changes.]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

3/5 [
Author: czou
Email: cao.zou@windriver.com
Subject: ls1021: add the support of RTLswitch for fixed-link property
Date: Thu, 3 Dec 2015 16:09:44 +0800

RTLswitch phy not connected to the real MDIO bus, set the dts
fixed-link property of phy of RTLswitch, and create the fixed-link
phy in mach-ls1021.

Signed-off-by: czou <cao.zou@windriver.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

4/5 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: ls1021a-iot: update qspi device tree node info
Date: Thu, 5 May 2016 16:27:17 +0800

1) Change qspi device tree node status from "disabled" to "okay"
to enable qspi nor flash.
2) Add partitions for spi-nor flash.
3) Delete nonexistent device node "qflash1: s25fl128s@1".

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

5/5 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: ARM: ls1021a: fix incorrect merge dts patch
Date: Mon, 10 Oct 2016 11:04:30 +0800

This fixes incorrect merging dts code:
1. Duplicate qspi dts & sata node merging.
2. Use the correct dcu & uart name.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>