i915: fix stray extra bracket causing build fail.
In the fast forward tree, that was done as this separate commit:

 ------------------
commit 28101b01999c086c5d3c0399962ffef7f9d2e4f5
Author: yadi.hu@windriver.com <yadi.hu@windriver.com>
Date:   Fri Nov 14 13:39:54 2014 +0800

    Fix build error

    i915_cmd_parser.c:408:19: error: expected expression before ')' token
            ((ptrdiff_t))(batch_end - cmd));

    Signed-off-by: Hu <yadi.hu@windriver.com>

diff --git a/drivers/gpu/drm/i915/i915_cmd_parser.c b/drivers/gpu/drm/i915/i915_cmd_parser.c
index d8ce12ba8041..f8fcf628a3ea 100644
--- a/drivers/gpu/drm/i915/i915_cmd_parser.c
+++ b/drivers/gpu/drm/i915/i915_cmd_parser.c
@@ -405,7 +405,7 @@ int i915_parse_cmds(struct intel_ring_buffer *ring,
                        DRM_DEBUG_DRIVER("CMD: Command length exceeds batch length: 0x%08X length=%d batchlen=%td\n",
                                         *cmd,
                                         length,
-                                        ((ptrdiff_t))(batch_end - cmd));
+                                        (ptrdiff_t)(batch_end - cmd));
                        ret = -EINVAL;
                        break;
 ---------------

...but since it is rediculous to have a fix of a fix of a one line patch,
we just fix it in place here for any pending new trees.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>