Revert kdump mips: Add necessary items for core extraction
Rally: US51373

1/1 [
Author: Bin Jiang
Email: bin.jiang@windriver.com
Subject: Revert "kdump mips: Add necessary items for core extraction"
Date: Wed, 7 Jan 2015 05:24:01 +0000

The reverted commit introduces the following compile warning:
 arch/mips/kernel/machine_kexec.c:131:2: error: implicit declaration of
 function 'VMCOREINFO_ADDRESS' [-Werror=implicit-function-declaration]

Since the kexec and kdump is not supported for octeon3, so revert
the commit.

Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>