EPIC: Intel Baytrail Platform update
Rally: US61593

1/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: btcoexist: Add new mini driver
Date: Thu, 23 Jul 2015 06:15:25 +0000

commit aa45a673b291fd761275493bc15316d79555ed55 upstream

A new driver in the rtlwifi family for the RTL8723BE will soon be added.
The bluetooth coexistence code for this device has been split into a
separate mini driver as it will be shared with other devices.  This commit adds
the headers and sources, and modifies Kconfig and Makefile to configure
and build this driver.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

2/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: Prepare existing drivers for new driver
Date: Thu, 23 Jul 2015 06:19:50 +0000

commit 2cddad3c737a35118151ec930fb43a710b3646d2 upstream

A driver for the RTL8723BE will soon be added. This patch adds the
necessary parts to the common headers, and modifies the existing
drivers for those changes.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>

Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

3/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723ae: rtl8723-common: Create new driver for common code
Date: Thu, 23 Jul 2015 06:22:32 +0000

commit 0a168b48cdf7c22cf0250f62df4dde20adebf74b upstream

The drivers for RTL8723AE and RTL8723BE have some code in common.
This commit creates a driver for this code that will be shared, and
copies those common routines from rtl8723ae's phy code.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

4/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723ae: rtl8723-common: Copy common firmware code
Date: Thu, 23 Jul 2015 06:28:04 +0000

commit cbd0c8512f3b06c86849c554eb092862c46885d5 upstream

The drivers for RTL8723AE and RTL8723BE have some code in common.
This commit copies the common firmware routines into the shared
code.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

5/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723ae: rtl8723-common: Copy common dynamic power management code
Date: Thu, 23 Jul 2015 06:30:33 +0000

commit 57d9d9630a6b3f289ae87b1fc00e83ae44636766 upstream

The drivers for RTL8723AE and RTL8723BE have some code in common.
This commit copies the common power management routines into the shared
code.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

6/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Add new driver
Date: Thu, 23 Jul 2015 06:33:14 +0000

commit a619d1abe20cc892ddd8f6f60345b24d43971fb4 upstream

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

7/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Fix build error
Date: Thu, 23 Jul 2015 06:52:24 +0000

_ieee80211_is_robust_mgmt_frame is not defined in current
kernel, so use old ieee80211_is_robust_mgmt_frame version.

Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

8/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Fix sparse errors
Date: Tue, 28 Jul 2015 15:53:07 +0800

commit: 2903d04b5abe10393f659c5a0a4f8adec1b67b65 upstream

Sparse reports the following:

drivers/net/wireless/rtlwifi/rtl8723be/sw.c:374:14: sparse: duplicate
const

drivers/net/wireless/rtlwifi/rtl8723be/hw.c:2214:30: sparse: cast to
restricted __le32

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

9/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Fix smatch warnings
Date: Tue, 28 Jul 2015 15:56:16 +0800

commit: 7ce24ab74c04ce0ce238b5dce30e9bc3823527be upstream

Smatch reports the following:

drivers/net/wireless/rtlwifi/rtl8723be/fw.c:208
_rtl8723be_fill_h2c_command() warn: variable dereferenced before check
'rtlhal' (see line 69)
drivers/net/wireless/rtlwifi/rtl8723be/hw.c:1732
_rtl8723be_read_adapter_info() error: __builtin_memcpy()
'&rtlefuse->efuse_map[0][0]' too small (256 vs 512)

The first one is fixed by removing two pointless tests for NULL
pointers.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

10/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Fix array dimension problems
Date: Tue, 28 Jul 2015 15:59:16 +0800

commit: 4e3b3bcd81776527fa6f11624d68849de8c8802e upstream

Commit a619d1abe20c leads to the following static checker warning:

drivers/net/wireless/rtlwifi/rtl8723be/phy.c:667
_rtl8723be_store_tx_power_by_rate()
error: buffer overflow 'rtlphy->tx_power_by_rate_offset[band]' 4 <= 5

This warning arises because the code is testing the indices for the
wrong maximum
values. In addition, the tests merely putput a warning, and then
procedes to
corrupt memory. With this change, any such invalid memory access is
avoided.

Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

11/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: Remove addressof casts to same type
Date: Tue, 28 Jul 2015 16:09:53 +0800

commit: 9cb76aa994682c7a5584cf4a03aeedd7ef1204bd upstream

Using addressof then casting to the original type is pointless,
so remove these unnecessary casts.

Done via coccinelle script:

$ cat typecast.cocci
@@
type T;
T foo;
@@

-       (T *)&foo
+       &foo

Signed-off-by: Joe Perches <joe@perches.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

12/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: disable MSI interrupts mode
Date: Tue, 28 Jul 2015 16:13:54 +0800

commit 329d6e299f92a591acb3a80f6d597a5f9dce7e6d upstream

94010fa0dd07e8b904e7c6b6589f15573008ab15 ("rtlwifi: add MSI interrupts
mode support") introduced MSI interrupts mode support, which seemed
safe enough with RTL8188EE and RTL8723BE as RealTek's testing results,
but some users reported their RTL8188EE modules could not connect to
any wireless network after the MSI mode was enabled by Ubuntu 14.04.

So, let's fallback to pin-based mode until rtlwifi's MSI support get
good compatibility.

BugLink: https://bugs.launchpad.net/bugs/1310512
Signed-off-by: Adam Lee <adam.lee@canonical.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

13/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: add msi module parameter
Date: Tue, 28 Jul 2015 16:15:36 +0800

commit 3924e338d587edbdc5a4dd0b358866b249fa21e1 upstream

The msi module parameter offers an option to enable or disable MSI
interrupts mode, for debugging and workaround(in case) convenience.

Signed-off-by: Adam Lee <adam.lee@canonical.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

14/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: Remove duplicate inclusion of phy.h
Date: Tue, 28 Jul 2015 16:18:45 +0800

commit 8ac070c02df91cbdf5ef418c4e18bd4b169767cc upstream

phy.h was included twice.

Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

15/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi/rtl8723be: Replace magic number by macro
Date: Tue, 28 Jul 2015 16:22:09 +0800

commit e5c3ef3652d8a05890cf49c1e2895f3d1fbd7f41 upstream

For consistency with other drivers, replace a magic number by a macro.

Signed-off-by: Rickard Strandqvist
<rickard_strandqvist@spectrumdigital.se>
Reviewed-by: Peter Wu <peter@lekensteyn.nl>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

16/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: rtl8723be: remove unnecessary break after return
Date: Tue, 28 Jul 2015 16:23:45 +0800

commit 7aa5a159fbec44224395c418dcadb7daefe14a16 upstream

Signed-off-by: Fabian Frederick <fabf@skynet.be>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

17/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: rtlwifi: make MSI support a module parameter
Date: Tue, 28 Jul 2015 16:46:31 +0800

commit 73070c45d50060f686df1f34c649cbc089991a28 upstream

This makes MSI support a module parameter, for debugging and workaround
convenience.

Signed-off-by: Adam Lee <adam.lee@canonical.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

18/24 [
Author: Chang Rebecca Swee Fun
Email: rebecca.swee.fun.chang@intel.com
Subject: x86/byt: enable board file for Baytrail LPSS PCI mode
Date: Tue, 20 May 2014 14:53:33 +0800

commit 5d90019c0d7ce8e9ddfaf4ff8f2c27f90ad5bb10 valleyisland-io-3.0
git://git.yoctoproject.org/linux-yocto-3.10.git

This commit enables the following:
- register SPI slave
- fix device name string for clkdev registration
- insert kernel module param to allow user to disable the BYT
  PCI board file

Signed-off-by: Chew Chiau Ee <chiau.ee.chew@intel.com>
Signed-off-by: Maurice Petallo <mauricex.r.petallo@intel.com>
Signed-off-by: Chang Rebecca Swee Fun <rebecca.swee.fun.chang@intel.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

19/24 [
Author: "Chew, Kean Ho"
Email: kean.ho.chew@intel.com
Subject: pinctrl-baytrail: unmap interrupt when free the gpio pin
Date: Wed, 12 Feb 2014 04:20:41 -0500

commit 30114eadba1a0bfa9958c7953f4464e1ac598213 valleyisland-io-3.0
git://git.yoctoproject.org/linux-yocto-3.10.git

In to_irq() callback, we create the hwirq to linux irq
mapping for the requested GPIO pin. Hence, we unamp
the mapping when the gpio pin is being released.

Signed-off-by: Chew, Kean Ho <kean.ho.chew@intel.com>
Signed-off-by: Chew, Chiau Ee <chiau.ee.chew@intel.com>
Signed-off-by: Sreeju Selvaraj <sreeju.armughanx.selvaraj@intel.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

20/24 [
Author: "Chew, Kean Ho"
Email: kean.ho.chew@intel.com
Subject: pinctrl-baytrail: enable platform device in the absent of ACPI enumeration
Date: Wed, 12 Feb 2014 06:14:33 -0500

commit cfd77f19dce5e0d9d5a11a6ca9c629f2a8d09ec8 valleyisland-io-3.0
git://git.yoctoproject.org/linux-yocto-3.10.git

This is to cater the need for non-ACPI system whereby
a platform device has to be created in order to bind
with the BYT Pinctrl GPIO platform driver.

Signed-off-by: Chew, Kean Ho <kean.ho.chew@intel.com>
Signed-off-by: Chew, Chiau Ee <chiau.ee.chew@intel.com>
Signed-off-by: Sreeju Selvaraj <sreeju.armughanx.selvaraj@intel.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

21/24 [
Author: "Chew, Kean Ho"
Email: kean.ho.chew@intel.com
Subject: pinctrl-baytrail: setup IOAPIC interrupt for GPIO clusters on non-ACPI system
Date: Tue, 11 Feb 2014 11:25:45 -0500

commit 0992d01f5f382f6da60004ef87f67ebd3ca13732 valleyisland-io-3.0
git://git.yoctoproject.org/linux-yocto-3.10.git

BayTrail GPIO NORTH, SOUTH and SUS clusters use IRQ48,
49 and 50 respectively. On non-ACPI system, we need
to setup IOAPIC RTE for device that use interrupt
beyond IRQ23.

Signed-off-by: Chew, Kean Ho <kean.ho.chew@intel.com>
Signed-off-by: Chew, Chiau Ee <chiau.ee.chew@intel.com>
Signed-off-by: Sreeju Selvaraj <sreeju.armughanx.selvaraj@intel.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

22/24 [
Author: chunguang yang
Email: chunguang.yang@windriver.com
Subject: usb: dwc3: introduce dual role switch function with debugfs
Date: Fri, 3 Jul 2015 18:46:06 +0800

The Bakersport board has a usb otg port and due to its hardware design
it only works as usb device port and can't change its role dynamically.
The default dwc3 driver's dual role work is OTG and loads the xhci-hcd module,
which takes irq 22. when loading the usb gadget module like g_printer,
the irq num conflict will occur and the loading failes. Add this patch
to enable dwc3's driver switch to device mode and unload the xhci-hcd module.
Although the patch used for this change was not accepted upstream, it
is technically sound and with Wind River's specific BSP enablement it
is safe for integration into the kernel

This patch is from http://permalink.gmane.org/gmane.linux.usb.general/115277

This patch implemented a feature to dynamic switch to host or device role under
debugfs for some physical limitation that unable to leverage connector A/B
cables (ID pin) to change roles.

The default role should be set as OTG mode. Then use below commands:

[1] switch to host:
echo host > /sys/kernel/debug/dwc3.0.auto/mode

[2] switch to device:
echo device > /sys/kernel/debug/dwc3.0.auto/mode

[3] switch to otg (default mode):
echo otg > /sys/kernel/debug/dwc3.0.auto/mode

Signed-off-by: Huang Rui <ray.huang@amd.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

23/24 [
Author: Andrzej Pietrasiewicz
Email: andrzej.p@samsung.com
Subject: usb: gadget: printer: enqueue printer's response for setup request
Date: Tue, 3 Mar 2015 10:52:05 +0100

commit eb132ccbdec5df46e29c9814adf76075ce83576b upstream

when usb printer repluged into host pc, host pc will dump the following
errors.
[20200.276077] usb 5-3: new high-speed USB device number 12 using ehci_hcd
[20215.388098] usb 5-3: device descriptor read/64, error -110
[20215.628093] usb 5-3: device descriptor read/64, error -71
[20215.844120] usb 5-3: new high-speed USB device number 13 using ehci_hcd
[20215.980082] usb 5-3: device descriptor read/64, error -71
[20216.220305] usb 5-3: device descriptor read/64, error -71

Function-specific setup requests should be handled in such a way, that
apart from filling in the data buffer, the requests are also actually
enqueued: if function-specific setup is called from composte_setup(),
the "usb_ep_queue()" block of code in composite_setup() is skipped.

The printer function lacks this part and it results in e.g. get device id
requests failing: the host expects some response, the device prepares it
but does not equeue it for sending to the host, so the host finally asserts
timeout.

This patch adds enqueueing the prepared responses.

Cc: <stable@vger.kernel.org> # v3.4+
Fixes: 2e87edf49227: "usb: gadget: make g_printer use composite"
Signed-off-by: Andrzej Pietrasiewicz <andrzej.p@samsung.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

24/24 [
Author: Fupan Li
Email: fupan.li@windriver.com
Subject: usb: gadget: printer: fix deadlock caused by nested spinlock
Date: Mon, 3 Aug 2015 19:19:43 +0800

commit a24b071bb4ac37ef51a0ed4765f89be05a617677 upstream

Function printer_func_disable() has called spinlock on printer_dev->lock,
and it'll call function chain of

    printer_reset_interface()
        |
	+---dwc3_gadget_ep_disable()
	        |
                +---__dwc3_gadget_ep_disable()
                        |
                        +---dwc3_remove_requests()
                                |
                                +---dwc3_gadget_giveback()
                                        |
                                        +---rx_complete()

in the protected block.

However, rx_complete() in printer.c calls spinlock on printer_dev->lock
again, which will cause system hang.

The following steps can reproduce this hang:

1. Build the test program from Documentation/usb/gadget_printer.txt as
   g_printer
2. Plug in the USB device to a host(such as Ubuntu).
3. on the USB device system run:
   #modprobe g_printer.ko
   #./g_printer -read_data

4. Unplug the USB device from the host

   The system will hang later.

In order to avoid this deadlock, moving the spinlock from
printer_func_disable() into printer_reset_interface() and excluding the block
of calling dwc3_gadget_ep_disable(), in which the critical resource will be
protected by its spinlock in rx_complete().

This commit will fix the system hang with the following calltrace:

INFO: rcu_preempt detected stalls on CPUs/tasks: { 3} (detected by 0, t=21006 jiffies, g=524, c=523, q=2)
sending NMI to all CPUs:
NMI backtrace for cpu 3
CPU: 3 PID: 718 Comm: irq/22-dwc3 Not tainted 3.10.38-ltsi-WR6.0.0.11_standard #2
Hardware name: Intel Corp. VALLEYVIEW B3 PLATFORM/NOTEBOOK, BIOS BYTICRB1.86C.0092.R32.1410021707 10/02/2014
task: f44f4c20 ti: f40f6000 task.ti: f40f6000
EIP: 0060:[<c1824955>] EFLAGS: 00000097 CPU: 3
EIP is at _raw_spin_lock_irqsave+0x35/0x40
EAX: 00000076 EBX: f80fad00 ECX: 00000076 EDX: 00000075
ESI: 00000096 EDI: ffffff94 EBP: f40f7e20 ESP: f40f7e18
 DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
CR0: 8005003b CR2: b77ac000 CR3: 01c30000 CR4: 001007f0
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: ffff0ff0 DR7: 00000400
Stack:
 f474a720 f80fad00 f40f7e3c f80f93cc c135d486 00000000 f474a720 f468fb00
 f4bea894 f40f7e54 f7e35f19 ffffff00 f468fb00 f468fb24 00000086 f40f7e64
 f7e36577 f468fb00 f4bea810 f40f7e74 f7e365a8 f468fb00 f4bea894 f40f7e9c
Call Trace:
 [<f80f93cc>] rx_complete+0x1c/0xb0 [g_printer]
 [<c135d486>] ? vsnprintf+0x166/0x390
 [<f7e35f19>] dwc3_gadget_giveback+0xc9/0xf0 [dwc3]
 [<f7e36577>] dwc3_remove_requests+0x57/0x70 [dwc3]
 [<f7e365a8>] __dwc3_gadget_ep_disable+0x18/0x60 [dwc3]
 [<f7e366e9>] dwc3_gadget_ep_disable+0x89/0xf0 [dwc3]
 [<f80f9031>] printer_reset_interface+0x31/0x50 [g_printer]
 [<f80f9270>] printer_func_disable+0x20/0x30 [g_printer]
 [<f80e6d8b>] composite_disconnect+0x4b/0x90 [libcomposite]
 [<f7e39a8b>] dwc3_disconnect_gadget+0x38/0x43 [dwc3]
 [<f7e39ad4>] dwc3_gadget_disconnect_interrupt+0x3e/0x5a [dwc3]
 [<f7e373b8>] dwc3_thread_interrupt+0x5c8/0x610 [dwc3]
 [<c10ac518>] irq_thread_fn+0x18/0x30
 [<c10ac800>] irq_thread+0x100/0x130
 [<c10ac500>] ? irq_finalize_oneshot.part.29+0xb0/0xb0
 [<c10ac650>] ? wake_threads_waitq+0x40/0x40
 [<c10ac700>] ? irq_thread_dtor+0xb0/0xb0
 [<c1057224>] kthread+0x94/0xa0
 [<c182b337>] ret_from_kernel_thread+0x1b/0x28
 [<c1057190>] ? kthread_create_on_node+0xc0/0xc0

Signed-off-by: Fupan Li <fupan.li@windriver.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>
Signed-off-by: chunguang yang <chunguang.yang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>