ixgbe: use msleep for long delays
Issue: LIN8-4791

1/1 [
Author: Arnd Bergmann
Email: arnd@arndb.de
Subject: ixgbe: use msleep for long delays
Date: Sat, 16 Apr 2016 22:35:08 +0200

commit d4f90d9dca26efef7a1112a8f4258c90b73bb37f upstream.

The newly added x550em_a support causes a link failure on ARM because of
an overly long time passed into udelay():

ERROR: "__bad_udelay" [drivers/net/ethernet/intel/ixgbe/ixgbe.ko] undefined!

There are multiple variants of the ixgbe_acquire_swfw_sync_*() function,
and the other ones all use msleep(), so we can safely assume that all
callers are allowed to sleep, which makes msleep() a better replacement
than mdelay().

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 49425dfc7451 ("ixgbe: Add support for x550em_a 10G MAC type")
Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>