fix compiling errors from "hugetlb: hugepage migration fixes"
CQID: WIND00298968

1/1 [
    Author: Zumeng Chen
    Email: zumeng.chen@windriver.com
    Subject: fix compiling errors from "hugetlb: hugepage migration fixes"
    Date:   Tue Sep 6 11:16:22 2011 +0800

    This patch is intended to squash with "hugetlb: hugepage
    migration fixes".  Fixes the following build error when
    CONFIG_NUMA is configured:

    fs/built-in.o: In function `hugetlbfs_migrate_page':
    /home/hzhong/work/board/intel_xeon_3420_pch/build/linux/fs/hugetlbfs/inode.c:598:
    undefined reference to `migrate_huge_page_move_mapping'
    remake[6]: *** [.tmp_vmlinux1] Error 1

    There error occurs because the code was only partial introduced. We
    removed to incomplete implementation.

    The related upstream ID is 290408d4 for hugepage core.

    Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

The commit is squashed with "hugetlb: hugepage migration fixes".
Squashing also pulls in commit "Fix build error with !CONFIG_MIGRATION",
which modified extern int migrate_huge_page_move_mapping().

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>