lttng2: Fix build error related to trace_rcu
JIRAID: LIN6-7209

1/1 [
Author: Nam Ninh
Email: nam.ninh@windriver.com
Subject: lttng2: Fix build error related to trace_rcu.
Date: Thu, 17 Apr 2014 13:11:30 -0400

This is the fix for following build error:

ovp-kvm/bitbake_build/tmp/work/intel_x86_64-wrs-linux/linux-windriver/3.10-r0/linux/drivers/staging/lttng2/probes/../instrumentation/events/lttng-module/../../../probes/lttng-events.h:151:6: error: conflicting types for 'trace_rcu_utilization'
|  void trace_##_name(_proto);

rcutree.c defines the argument passed to trace_rcu_utilization to be TPS(x)
which is of type "const char *" while TRACE_EVENT for rcu_utilization
defines the argument to be "char *), so there is a conflicting types for
trace_rcu_utilization

Signed-off-by: Nam Ninh <nam.ninh@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>