rpmsg: add the missing head files
Rally: US104834

1/6 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: driver/ethernet/xilinx_axienet: fix wrong using phydev
Date: Thu, 9 Nov 2017 04:06:16 -0500

Since the merge conflict, the removed phydev is still being used
and causes the building error, here fixing the error.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/6 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: net: macb: break out when ctrl null
Date: Wed, 30 Nov 2016 06:37:15 -0800

ctrl might be null after having done a reset on RX ZynqMP while addr used bit
is only set by software, so null ctrl should be used here to break out. Even
if not ZynqMP, ctrl should never be null if there is rx buffer used, so it's
safe for all.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

3/6 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: arm64/dts/xilinx: remove unstable phy interfaces
Date: Mon, 13 Feb 2017 12:13:14 +0800

Currently xilinx phys ralated designs are still not stable, so remove them and
usb & sata hardisk works well.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

4/6 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: driver: pci: xilinx-nwl: remove wrong definition PCI_XILINX_NWL
Date: Fri, 10 Nov 2017 03:56:08 -0500

Remove the wrong definition PCI_XILINX_NWL to resolve the building error,
and fix wrong using the pointer "dev".

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

5/6 [
Author: "Felipe F. Tonello"
Email: eu@felipetonello.com
Subject: usb: gadget: fix usb_ep_align_maybe endianness and new usb_ep_align
Date: Mon, 8 Aug 2016 21:30:04 +0100

commit 16b114a6d7973cf027e4c2b23eae1076eaf98c25 from
https://github.com/Xilinx/linux-xlnx.git

USB spec specifies wMaxPacketSize to be little endian (as other properties),
so when using this variable in the driver we should convert to the current
CPU endianness if necessary.

This patch also introduces usb_ep_align() which does always returns the
aligned buffer size for an endpoint. This is useful to be used by USB requests
allocator functions.

Signed-off-by: Felipe F. Tonello <eu@felipetonello.com>
Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

6/6 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: rpmsg: add the missing head files
Date: Tue, 14 Nov 2017 01:38:15 -0500

To fix below building errors:
| drivers/rpmsg/rpmsg_core.c:320:9: error: implicit declaration of function 'of_driver_match_device' [-Werror=implicit-function-declaration]
|   return of_driver_match_device(dev, drv);
|          ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>