carry other patches for standard/base branch
RALLY: US19624

1/6 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: intel-iommu: Extend PFN to 64 bits when DMAR >= 40 bits
Date: Wed, 30 Jan 2013 15:52:22 -0800

On x86_32, when the DMAR width is >= 40 bits and IOMMU is enabled,
unbinding a device from the host PCI driver will hang the associated
userspace process on a wait notifier that is never triggered.

This hang is caused on x86_32 when the DMAR width is >= 40 bits, since it
also means that the PFN is more than 32 bits. This cases the kernel to
infinitely loop in dma_pte_free_pagetable as follows:

  while (tmp && tmp + level_size(level) - 1 <= last_pfn)

Since the condition is always true.

Promote start_pfn and last_pfn parameter to 64 bit for dma_pte_clear_range
and dma_pte_free_pagetable. And, pass __DOMAIN_MAX_PFN to them as last_pfn.

Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

2/6 [
Author: Liang Li
Email: liang.li@windriver.com
Subject: wireless/cfg80211: do err handling kfree without holding spin-lock
Date: Tue, 15 Jan 2013 14:52:30 +0800

The error handling code in cfg80211_mlme_register_mgmt calling kfree
while holding spin lock wdev->mgmt_registration_lock, then release the
lock right after the kfree.

There is no restriction to the sequence that do kfree before release
spin lock .. and do kfree after release spin lock should be better way
to do error clean up work.

So just minor change to move the kfree after lock release.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>
Signed-off-by: Liang Li <liang.li@windriver.com>
]

3/6 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: trace: Increase process name size for late boottime analysis
Date: Mon, 16 Sep 2013 15:54:05 -0700

Add CONFIG_WR_BOOT kernel config to increase the buffer for the
process name so that analyse-boottime can display the process
name correctly.

Signed-off-by: Pradeep Tumati <pradeep.tumati@windriver.com>
[yshi: Add text for the config so that it can be showed in menuconfig]
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

4/6 [
Author: Tiejun Chen
Email: tiejun.chen@windriver.com
Subject: powerpc/hugetlb: replace __get_cpu_var with get_cpu_var
Date: Wed, 11 Jul 2012 13:26:13 +0800

Replace __get_cpu_var safely with get_cpu_var to avoid
the following call trace:

BUG: using smp_processor_id() in preemptible [00000000] code: hugetlbperforma/1288
caller is free_hugepd_range.constprop.22+0x90/0x1a4
Call Trace:
[e905dd60] [c0007b34] show_stack+0x10c/0x1c0 (unreliable)
[e905ddb0] [c0648d10] dump_stack+0x24/0x34
[e905ddc0] [c033a9b4] debug_smp_processor_id+0xd8/0xfc
[e905dde0] [c0015ef0] free_hugepd_range.constprop.22+0x90/0x1a4
[e905de00] [c001631c] hugetlb_free_pgd_range+0x7c/0x17c
[e905de40] [c00fa7ac] free_pgtables+0x110/0x12c
[e905de60] [c01003f4] unmap_region+0x108/0x134
[e905dee0] [c0101568] do_munmap+0x264/0x2e4
[e905df10] [c010162c] vm_munmap+0x44/0x68
[e905df30] [c0102c14] sys_munmap+0x1c/0x2c
[e905df40] [c000e33c] ret_from_syscall+0x0/0x3c

    Exception: c01 at 0xff32344
    LR = 0x1000076c

Signed-off-by: Tiejun Chen <tiejun.chen@windriver.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

5/6 [
Author: yhe
Email: yongli.he@windriver.com
Subject: hugeTLB/booke: fix TLB testing call trace
Date: Tue, 15 Jan 2013 13:13:37 +0800

when acquired per cpu variable "bachp" we are in the atomic
context, this is unnecessary when there is no dereference to
per cpu variable. so lock it when just access it.

BUG: sleeping function called from invalid context at linux/kernel/rtmutex.c:646
in_atomic(): 1, irqs_disabled(): 0, pid: 2156, name: hugemmap01
Call Trace:
[c0000001ed7db590] [c00000000000b064] .show_stack+0xe4/0x250 (unreliable)
[c0000001ed7db660] [c000000000890a30] .dump_stack+0x20/0x30
[c0000001ed7db6d0] [c000000000089e48] .__might_sleep+0x108/0x160
[c0000001ed7db770] [c000000000885a44] .rt_spin_lock+0x34/0x90
[c0000001ed7db7f0] [c00000000019172c] .kmem_cache_free+0x8c/0x240
[c0000001ed7db8a0] [c00000000002f730] .free_hugepd_range+0x1e0/0x280
[c0000001ed7db950] [c00000000002fe8c] .hugetlb_free_pgd_range+0x25c/0x3d0
[c0000001ed7dba70] [c00000000016f164] .free_pgtables+0x154/0x190
[c0000001ed7dbb20] [c000000000173e1c] .unmap_region+0x13c/0x190
[c0000001ed7dbc50] [c000000000175620] .do_munmap+0x310/0x3e0
[c0000001ed7dbd10] [c000000000175744] .vm_munmap+0x54/0x90
[c0000001ed7dbdb0] [c0000000001773e8] .SyS_munmap+0x28/0x40
[c0000001ed7dbe30] [c0000000000005a4] syscall_exit+0x0/0x2c

Signed-off-by: Yongli He <yongli.he@windriver.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

6/6 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: powerpc: don't migrate irq which is explicitly set IRQF_NOBALANCING
Date: Thu, 10 Jan 2013 14:25:39 +0800

Flag IRQF_NOBALANCING is used to exclude one irq from irq balancing.
But when we try to offline a cpu the migrate_irqs doesn't honour this
flag and still migrate these irqs to other cpu. This definitely violate
the primary intention of this flag. So replace irqd_is_per_cpu()
with !irqd_can_balance() in migrate_irqs since it will cover both
IRQF_PERCPU and IRQF_NOBALANCING.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Yang Shi <yang.shi@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>