nlm_xlp serial port prints call trace when runnning multithread program
Issue: LIN4-31530

1/16 [
Author: David Daney
Email: ddaney@caviumnetworks.com
Subject: MIPS: Probe for presence of KScratch registers.
Date: Tue, 21 Dec 2010 14:19:09 -0800

commit e77c32fe284a4da1b4e0994890a4d3527812eb61 upstream

Probe c0_config4 for KScratch registers and report them in /proc/cpuinfo.

Signed-off-by: David Daney <ddaney@caviumnetworks.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/1877/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

2/16 [
Author: David Daney
Email: david.daney@cavium.com
Subject: MIPS: Add uasm UASM_i_SRL_SAFE macro.
Date: Tue, 5 Jul 2011 16:34:45 -0700

commit f0daaaf5236297ea81ec7732cd0df5dbd84a5042 upstream

This can be used from either 32-bit or 64-bit code to generate logical
right shifts of any constant amount.

Signed-off-by: David Daney <david.daney@cavium.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/2576/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

3/16 [
Author: Yong Zhang
Email: yong.zhang@windriver.com
Subject: mips:tlbex: reset back to 2.6.34
Date: Thu, 17 Jul 2014 14:22:58 +0800

Prepare to adopt update from newer SDK.

Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

4/16 [
Author: Yong Zhang
Email: yong.zhang@windriver.com
Subject: mips:mmu_context.h: restore back to v2.6.34
Date: Thu, 17 Jul 2014 14:34:03 +0800

Prepare for tlb handler update from new SDK.

Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

5/16 [
Author: David Daney
Email: ddaney@caviumnetworks.com
Subject: MIPS: Use C0_KScratch (if present) to hold PGD pointer.
Date: Tue, 21 Dec 2010 14:19:11 -0800

commit 3d8bfdd0307223de678962f1c1907a7cec549136 upstream

Decide at runtime to use either Context or KScratch to hold the PGD
pointer.

Signed-off-by: David Daney <ddaney@caviumnetworks.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/1876/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

6/16 [
Author: David Daney
Email: ddaney@caviumnetworks.com
Subject: MIPS: Use BBIT instructions in TLB handlers
Date: Mon, 20 Dec 2010 15:54:50 -0800

commit cc33ae437975416a1b78f99e2715e91ab643526a upstream

If the CPU supports BBIT0 and BBIT1, use them in TLB handlers as they
are more efficient than an AND followed by an branch and then
restoring the clobbered register.

Signed-off-by: David Daney <ddaney@caviumnetworks.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/1873/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

7/16 [
Author: David Daney
Email: ddaney@caviumnetworks.com
Subject: MIPS: Optimize TLB handlers for Octeon CPUs
Date: Mon, 27 Dec 2010 18:07:57 -0800

commit 2c8c53e28f178577dfdf3a69731b998b7e3df8ae upstream

Octeon can use scratch registers in the TLB handlers.  Octeon II can
use LDX instructions.

Signed-off-by: David Daney <ddaney@caviumnetworks.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/1904/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

8/16 [
Author: David Daney
Email: ddaney@caviumnetworks.com
Subject: MIPS: Add an unreachable return statement to satisfy buggy GCCs.
Date: Wed, 19 Jan 2011 15:24:42 -0800

commit e1c87d2a5567c7940d129a6045efadc4b8c0f888 upstream

It was reported that GCC-4.3.3 (with CodeSourcery extensions) fails
without this.

Reported-by: Jonas Gorski <jonas.gorski@gmail.com>
Signed-off-by: David Daney <ddaney@caviumnetworks.com>
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/2010/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

9/16 [
Author: Ralf Baechle
Email: ralf@linux-mips.org
Subject: MIPS: tlbex: Fix GCC 4.6.0 build error
Date: Tue, 29 Mar 2011 10:54:54 +0200

commit 4a9040f451c32cd62971ecda1cb5bc4aed444c78 upstream

  CC      arch/mips/mm/tlbex.o
arch/mips/mm/tlbex.c: In function 'build_r4000_tlb_refill_handler':
arch/mips/mm/tlbex.c:1155:22: error: variable 'vmalloc_mode' set but not used [-Werror=unused-but-set-variable]
arch/mips/mm/tlbex.c:1154:28: error: variable 'htlb_info' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

10/16 [
Author: David Daney
Email: david.daney@cavium.com
Subject: MIPS: Close races in TLB modify handlers.
Date: Tue, 5 Jul 2011 16:34:46 -0700

commit bf28607fbe529e20180080c4a0295b0a47834fde upstream

Page table entries are made invalid by writing a zero into the the PTE
slot in a page table.  This creates a race condition with the TLB
modify handlers when they are updating the PTE.

CPU0                              CPU1

Test for _PAGE_PRESENT
.                                 set to not _PAGE_PRESENT (zero)
Set to _PAGE_VALID

So now the page not present value (zero) is suddenly valid and user
space programs have access to physical page zero.

We close the race by putting the test for _PAGE_PRESENT and setting of
_PAGE_VALID into an atomic LL/SC section.  This requires more registers
than just K0 and K1 in the handlers, so we need to save some registers
to a save area and then restore them when we are done.

The save area is an array of cacheline aligned structures that should
not suffer cache line bouncing as they are CPU private.

[ralf@linux-mips.org: Fix !defined(CONFIG_MIPS_PGD_C0_CONTEXT) build error.]

Signed-off-by: David Daney <david.daney@cavium.com>
To: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/2577/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

11/16 [
Author: Ralf Baechle
Email: ralf@linux-mips.org
Subject: MIPS: tlbex: Fix build error in R3000 code.
Date: Tue, 2 Aug 2011 22:52:48 +0100

commit d954ffe34a606d4ec34cd3c2b0b5974779759f25 upstream

Only some GCC versions such as gcc 4.2 notice that the variable wr in
build_r3000_tlb_modify_handler is used uninitialized.  When using one
of those GCCs the build will fail due to -Werror.  GCC 4.6 does not
warn about the uninitialized use of wr.

This issue was introduced by 7211f4d7a3dcbe57c5d396c334dca525315dceb2
[MIPS: Close races in TLB modify handlers.]

Reported-by: Ganesan Ramalingam <ganesan18@gmail.com>
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

12/16 [
Author: David Daney
Email: david.daney@cavium.com
Subject: MIPS: No branches in delay slots for huge pages in handle_tlbl
Date: Fri, 16 Sep 2011 18:06:02 -0700

commit 0f4ccbc835036cbcc2513585bb2e93ee62e12674 upstream

For the case PM_DEFAULT_MASK == 0, we were placing a branch in the
delay slot of another branch.  This leads to undefined behavior.

Signed-off-by: David Daney <david.daney@cavium.com>
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/2775/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

13/16 [
Author: Yong Zhang
Email: yong.zhang@windriver.com
Subject: MIPS:tlbex: update tlbex to support XLP
Date: Thu, 17 Jul 2014 14:56:34 +0800

Based on Broadcom SDK 2.3.

Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

14/16 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: bcm-xlp: fix the definition of cache coherency bit
Date: Thu, 6 Jun 2013 15:03:13 +0800

SDK use the fixed offset value in the three cache attributes macro.
It's incorrect when we disable the HUGETLB_PAGE.
The _CACHE_CACHABLE_NONCOHERENT affects the PAGE_NONE macro in protection_map[]
which is the mapping table of vm and hardware protection attributes.
The kernel would get incorrect attribute bits when using the table. The cache
attribute becomes 0x7 on mprotect() system call, but 0x7 is illegal in XLS/XLR/XLP
platform and it will cause kernel unaligned access.

The Call Trace info as follow:
====================================================================================
root@xlp:/opt/wr-test# ./main_test.sh -s tracing
Unhandled kernel unaligned access[#1]:
Cpu 28
$ 0 : 0000000000000000 0000000000000001 0000000000000000 ffffff0000000000
$ 4 : a80000012201feb0 000000002aac8000 0000000000409b94 0000000000000000
$ 8 : 000000002aac8000 0000000000000000 0000000000420000 000000002adc7160
$12 : 000000001000dce1 000000001000001e ffffffffffffffff 0000000000430000
$16 : a80000012201feb0 000000002aac8000 ffffffff8e050000 ffffffff8342049c
$20 : 0000000000000129 0000000000000000 0000000000000000 0000000000000000
$24 : 000000000042e674 000000002ae2a84c
$28 : a80000012201c000 a80000012201fbe0 0000000000420000 ffffffff8342049c
Hi : 000000000000026b
Lo : 00000000000001b6
epc : ffffffff834202b8 emulate_load_store_insn+0x3b0/0x470
Not tainted
ra : ffffffff8342049c do_ade+0x124/0x2b0
Status: 1000dce3 KX SX UX KERNEL EXL IE
Cause : 00800010
BadVA : 000000002aac8000
PrId : 000c0009 (XLP832 Rev B2)
Modules linked in: ..........
a800000123feeb40 ffffffff8340fa3c 00000000906c0397 ffffffff83522d5c
0000000023b9a0c0 a80000012418fe40 0000000000000180 ffffffff8340ff08
000000001000dce1 ffffffff8340ff08 000000001000dce1 000000000043006c
a800000123feeba0 ffffffff838c9dc0 ffffffff83e50000 ffffffff83400484
a800000123f2ab40 ffffffff8340f9f8 000000000043006c ffffffff8342aad4
a800000100030002 a8000001263f5ce0 0000000000000000 a800000123feeb40
000000000000001c ffffffff8342cc24 000000002aac8000 000000002aac9000
a8000001238f0540 000000002aac9000 000000002aac8000 a800000123feeb40
a800000123feeb40 ffffffffffe00000 a8000001238f0540 a80000012201feb0
...
Call Trace:
[<ffffffff834202b8>] emulate_load_store_insn+0x3b0/0x470
[<ffffffff8342049c>] do_ade+0x124/0x2b0
[<ffffffff83400484>] ret_from_exception+0x0/0x10

Code: 00431024 5440ff4c de030100 <8a230000> 9a230003 24020000
Disabling lock debugging due to kernel taint

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
Signed-off-by: Jack Tan <jack.tan@windriver.com>
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

15/16 [
Author: Yong Zhang
Email: yong.zhang@windriver.com
Subject: mips:tlbex: fix build
Date: Thu, 17 Jul 2014 16:09:56 +0800

Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

16/16 [
Author: Zi Shen Lim
Email: zlim@netlogicmicro.com
Subject: mips:xlp: Fix TLB flushing issue
Date: Thu, 17 Jul 2014 16:32:22 +0800

Stale tlbsize was used resulting in incomplete TLB flushes.
During mmu_init, make sure we update tlbsize *after* configuration.

Based on Broadcom SDK 2.3.

Signed-off-by: Zi Shen Lim <zlim@netlogicmicro.com>
Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
[Yong Zhang: Restore what commit 92bbe1b988d3 does]
Signed-off-by: Yong Zhang <yong.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>