tdm: include the missing header files for fsl tdm
Issue: LIN7-4779

1/1 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: tdm: include the missing header files for fsl tdm
Date: Thu, 17 Sep 2015 13:59:45 +0800

Fix the following build errors:
  drivers/tdm/device/tdm_fsl.c: In function 'tdm_fsl_probe':
  drivers/tdm/device/tdm_fsl.c:730:2: error: implicit declaration of function 'of_address_to_resource' [-Werror=implicit-function-declaration]
     ret = of_address_to_resource(ofdev->dev.of_node, 0, &res);
     ^
  drivers/tdm/device/tdm_fsl.c:737:2: error: implicit declaration of function 'of_iomap' [-Werror=implicit-function-declaration]
     priv->tdm_regs = of_iomap(ofdev->dev.of_node, 0);
     ^
  drivers/tdm/device/tdm_fsl.c:756:2: error: implicit declaration of function 'irq_of_parse_and_map' [-Werror=implicit-function-declaration]
     priv->dmac_done_intr = irq_of_parse_and_map(ofdev->dev.of_node, 0);
     ^

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>