backport perf kvm tool from Wind River Linux 5 to 4.3
CQID: WIND00411699

1/16 [
Author: Masami Hiramatsu
Email: mhiramat@redhat.com
Subject: perf probe: Move add-probe routine to util/
Date: Tue, 16 Mar 2010 18:05:37 -0400

commit e0faa8d35845bb1893cf9e608a5a5d92e9390bf0 upstream

Move add-probe routine to util/probe_event.c. This simplifies
main routine for reducing maintenance cost.

Signed-off-by: Masami Hiramatsu <mhiramat@redhat.com>
Cc: systemtap <systemtap@sources.redhat.com>
Cc: DLE <dle-develop@lists.sourceforge.net>
Cc: Frederic Weisbecker <fweisbec@gmail.com>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Paul Mackerras <paulus@samba.org>
Cc: Mike Galbraith <efault@gmx.de>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
LKML-Reference: <20100316220537.32050.72214.stgit@localhost6.localdomain6>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

2/16 [
Author: Arnaldo Carvalho de Melo
Email: acme@redhat.com
Subject: perf symbols: Avoid unnecessary symbol loading when dso list is specified
Date: Wed, 24 Mar 2010 16:40:15 -0300

commit 96415e4d3f5fdf9cdb12eedfcbc58152b1e1458c upstream

We were performing the full thread__find_addr_location
operation, i.e. resolving to a map/dso _and_ loading its symbols
when we can optimize it by first calling thread__find_addr_map
to find just the map/dso, check if it is one that we are
interested in (passed via --dsos/-d in 'perf annotate', 'perf
report', etc) and if not avoid loading the symtab.

Nice speedup when we know which DSO we're interested in.

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Frédéric Weisbecker <fweisbec@gmail.com>
Cc: Mike Galbraith <efault@gmx.de>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Paul Mackerras <paulus@samba.org>
LKML-Reference: <1269459619-982-2-git-send-email-acme@infradead.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

3/16 [
Author: Arnaldo Carvalho de Melo
Email: acme@redhat.com
Subject: perf symbols: Pass the mmap parameters instead of using mmap_event
Date: Thu, 25 Mar 2010 19:58:57 -0300

commit b177f63f5226e75280855bbcd106e677250778bd upstream

To reduce the coupling of the symbol system with the rest of
perf.

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Frédéric Weisbecker <fweisbec@gmail.com>
Cc: Mike Galbraith <efault@gmx.de>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Paul Mackerras <paulus@samba.org>
LKML-Reference: <1269557941-15617-2-git-send-email-acme@infradead.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

4/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf symbols: Move map related routines to map.c
Date: Sun, 7 Apr 2013 14:26:17 +0800

commit 4b8cf84624e9a58a21aaac3d064222092ae234e0 upstream

Thru series of refactorings functions were being renamed but not
moved to map.c to reduce patch noise, now lets have them in the
same place so that use of the symbol system by tools can be
constrained to building and linking fewer source files:
symbol.c, map.c and rbtree.c.

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Frédéric Weisbecker <fweisbec@gmail.com>
Cc: Mike Galbraith <efault@gmx.de>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Paul Mackerras <paulus@samba.org>
LKML-Reference: <1269557941-15617-3-git-send-email-acme@infradead.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

5/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf symbols: Move more map_groups methods to map.c
Date: Sun, 7 Apr 2013 14:29:47 +0800

commit c6e718ff8cdcf5e7855077687720b37c4a07650a upstream

While writing a standalone test app that uses the symbol system to
find kernel space symbols I noticed these also need to be moved.

Cc: Frédéric Weisbecker <fweisbec@gmail.com>
Cc: Mike Galbraith <efault@gmx.de>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Paul Mackerras <paulus@samba.org>
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

6/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Add pipe-specific header read/write and event processing code
Date: Sun, 7 Apr 2013 14:57:49 +0800

commit 8dc58101f2c838355d44402aa77646649d10dbec upstream

This patch makes several changes to allow the perf event stream
to be sent and received over a pipe:

- adds pipe-specific versions of the header read/write code

- adds pipe-specific version of the event processing code

- adds a range of event types to be used for header or other
  pseudo events, above the range used by the kernel

- checks the return value of event handlers, which they can use
  to skip over large events during event processing rather than actually
  reading them into event objects.

- unifies the multiple do_read() functions and updates its
  users.

Note that none of these changes affect the existing perf data
file format or processing - this code only comes into play if
perf output is sent to stdout (or is read from stdin).

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-2-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

7/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Convert perf header attrs into attr events
Date: Sun, 7 Apr 2013 15:04:13 +0800

commit 2c46dbb517a10b18d459e6ceffefde5bfb290cf6 upstream

Bypasses the attr perf header code and replaces it with a
synthesized event and processing function that accomplishes the
same thing, used when reading/writing perf data to/from a pipe.

Making the attrs into events allows them to be streamed over a
pipe along with the rest of the header data (in later patches).
It also paves the way to allowing events to be added and removed
from perf sessions dynamically.

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-6-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

8/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Convert perf event types into event type events
Date: Sun, 7 Apr 2013 15:07:09 +0800

commit cd19a035f3b63fee6dcbdb5371c4b22276f7dc8c upstream

Bypasses the event type perf header code and replaces it with a
synthesized event and processing function that accomplishes the
same thing, used when reading/writing perf data to/from a pipe.

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-7-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

9/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Convert perf tracing data into a tracing_data event
Date: Sun, 7 Apr 2013 15:09:25 +0800

commit 9215545e99d8c0b27323df2de504f4294bf5e407 upstream

Bypasses the tracing_data perf header code and replaces it with
a synthesized event and processing function that accomplishes
the same thing, used when reading/writing perf data to/from a
pipe.

The tracing data is pretty large, and this patch doesn't attempt
to break it down into component events.  The tracing_data event
itself doesn't actually contain the tracing data, rather it
arranges for the event processing code to skip over it after
it's read, using the skip return value added to the event
processing loop in a previous patch.

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-8-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

10/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Convert perf header build_ids into build_id events
Date: Sun, 7 Apr 2013 15:11:54 +0800

commit c7929e4727e8ff2d6fc8327188820e3b1c2f1dc3 upstream

Bypasses the build_id perf header code and replaces it with a
synthesized event and processing function that accomplishes the
same thing, used when reading/writing perf data to/from a pipe.

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-9-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

11/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf record: Enable the enable_on_exec flag if record forks the target
Date: Sun, 7 Apr 2013 16:39:15 +0800

commit bedbfdea31daf3880745001d56450c683959ee7e upstream

When forking its target, perf record can capture data from
before the target application is started.  Perf stat uses the
enable_on_exec flag in the event attributes to keep from
displaying events from before the target program starts, this
patch adds the same functionality to perf record when it is will
fork the target process.

Signed-off-by: Eric B Munson <ebmunson@us.ibm.com>
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Paul Mackerras <paulus@samba.org>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Frederic Weisbecker <fweisbec@gmail.com>
LKML-Reference: <1268664418-28328-1-git-send-email-acme@infradead.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

12/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf record: Enable counters only when kernel is execing subcommand
Date: Sun, 7 Apr 2013 16:41:05 +0800

commit 46be604b5ba738d53e5f5314813a4e7092864baf upstream

'perf record' starts counters before subcommand is execed, so
the statistics is not precise because it includes data of some
preparation steps. I fix it with the patch.

In addition, change the condition to fork/exec subcommand. If
there is a subcommand parameter, perf always fork/exec it. The
usage example is:

 # perf record -f -a sleep 10

So this command could collect statistics for 10 seconds
precisely. User still could stop it by CTRL+C. Without the new
capability, user could only input CTRL+C to stop it without
precise time clock.

Signed-off-by: Zhang Yanmin <yanmin_zhang@linux.intel.com>
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Avi Kivity <avi@redhat.com>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Sheng Yang <sheng@linux.intel.com>
Cc: oerg Roedel <joro@8bytes.org>
Cc: Jes Sorensen <Jes.Sorensen@redhat.com>
Cc: Marcelo Tosatti <mtosatti@redhat.com>
Cc: Gleb Natapov <gleb@redhat.com>
Cc: <zhiteng.huang@intel.com>
Cc: Zachary Amsden <zamsden@redhat.com>
LKML-Reference: <1268922965-14774-2-git-send-email-acme@infradead.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

13/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf record: Introduce special handling for pipe output
Date: Sun, 7 Apr 2013 16:42:33 +0800

commit 529870e37473a9fc609078f03cc5b4148cf06a87 upstream

Adds special treatment for stdout - if the user specifies '-o -'
to perf record, the intent is that the event stream be written
to stdout rather than to a disk file.

Also, redirect stdout of forked child to stderr - in pipe mode,
stdout of the forked child interferes with the stdout perf
stream, so redirect it to stderr where it can still be seen but
won't be mixed in with the perf output.

Signed-off-by: Tom Zanussi <tzanussi@gmail.com>
Acked-by: Thomas Gleixner <tglx@linutronix.de>
Cc: fweisbec@gmail.com
Cc: rostedt@goodmis.org
Cc: k-keiichi@bx.jp.nec.com
Cc: acme@ghostprotocols.net
LKML-Reference: <1270184365-8281-3-git-send-email-tzanussi@gmail.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

14/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: Enhance perf to allow for guest statistic collection from host
Date: Sun, 7 Apr 2013 16:55:12 +0800

commit 39447b386c846bbf1c56f6403c5282837486200f upstream

Below patch introduces perf_guest_info_callbacks and related
register/unregister functions. Add more PERF_RECORD_MISC_XXX bits
meaning guest kernel and guest user space.

Signed-off-by: Zhang Yanmin <yanmin_zhang@linux.intel.com>
Signed-off-by: Avi Kivity <avi@redhat.com>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

15/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf: 'perf kvm' tool for monitoring guest performance from host
Date: Sun, 7 Apr 2013 17:43:43 +0800

commit a1645ce12adb6c9cc9e19d7695466204e3f017fe upstream

Here is the patch of userspace perf tool.

Signed-off-by: Zhang Yanmin <yanmin_zhang@linux.intel.com>
Signed-off-by: Avi Kivity <avi@redhat.com>
Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

16/16 [
Author: Xufeng Zhang
Email: xufeng.zhang@windriver.com
Subject: perf/x86: resolve the undeclared PERF_EFLAGS_EXACT and PERF_RECORD_MISC_EXACT symbols
Date: Thu, 11 Apr 2013 12:09:35 +0800

This is part of upstream commit ef21f683a045a79b6aa86ad81e5fdfc0d5ddd250:
"perf, x86: use LBR for PEBS IP+1 fixup".

Resolve the below building errors:
  CC      arch/x86/kernel/cpu/perf_event.o
  linux/arch/x86/kernel/cpu/perf_event.c: In function 'perf_misc_flags':
  linux/arch/x86/kernel/cpu/perf_event.c:1782: error: 'PERF_EFLAGS_EXACT' undeclared \
  (first use in this function)
  linux/arch/x86/kernel/cpu/perf_event.c:1782: error: (Each undeclared identifier \
  is reported only once
  linux/arch/x86/kernel/cpu/perf_event.c:1782: error: for each function it appears in.)
  linux/arch/x86/kernel/cpu/perf_event.c:1783: error: 'PERF_RECORD_MISC_EXACT' undeclared \
  (first use in this function)
  linux/scripts/Makefile.build:411: *** [arch/x86/kernel/cpu/perf_event.o] Error 1

Signed-off-by: Xufeng Zhang <xufeng.zhang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>