cav-octeon2:fix flash build error by adding CONFIG_MTD flag
CQID: WIND00396466

Refresh:
features/cavium/sdk-2.3.0-427/MIPS-Octeon-Initialize-and-fixup-device-tree.patch

1/1 [
Author: Zhang Ruibo
Email: ruibo.zhang@windriver.com
Subject: cav-octeon2:fix flash build error by adding CONFIG_MTD flag
Date: Thu, 10 Jan 2013 14:01:05 +0800

If CONFIG_MTD set to "m", the flash compile error will occur:

 arch/mips/built-in.o: In function `flash_init':
 linux/arch/mips/cavium-octeon/flash_setup.c:59:
 undefined reference to `do_map_probe'
 linux/arch/mips/cavium-octeon/flash_setup.c:62:
 undefined reference to `mtd_device_parse_register'
 make[2]: *** [.tmp_vmlinux1] Error 1

so modify flash build flag from "y" to "CONFIG_MTD".
all flash usage should depend on MTD subsystem.

Because symbol "mtd_device_parse_register" use EXPORT_SYMBOL_GPL
to export,so add MODULE_LICENSE("GPL") to flash_setup.c

Signed-off-by: Ruibo Zhang<ruibo.zhang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>