Add MMC support for CN61XX and update it to SDK 3.1.0p3
Rally: US40406

1/20 [
Author: Seungwon Jeon
Email: tgih.jun@samsung.com
Subject: mmc: queue: amend buffer swap for non-blocking transfer
Date: Fri, 28 Sep 2012 19:12:53 +0900

commit 45c5a914e68fdbbc2635c3cc197566aa24e8de5b upstream

In case both 'req' and 'mq->mqrq_prev->req' are null, there is no request
to be processed. That means there is no need to switch buffer.
Switching buffer is required only after finishing 'issue_fn'.

Signed-off-by: Seungwon Jeon <tgih.jun@samsung.com>
Reviewed-by: Per Forlin <per.forlin@stericsson.com>
Tested-by: Johan Rudholm <johan.rudholm@stericsson.com>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

2/20 [
Author: Seungwon Jeon
Email: tgih.jun@samsung.com
Subject: mmc: queue: exclude asynchronous transfer for special request
Date: Wed, 26 Dec 2012 10:40:17 +0900

commit 369d321ed1baa7748e770aaaae4d8effad699633 upstream

Unlike normal r/w request, special requests(discard, flush)
is finished with a one-time issue_fn. Request change to
mqrq_prev makes unnecessary call.

Signed-off-by: Seungwon Jeon <tgih.jun@samsung.com>
Reviewed-by: Konstantin Dorfman <kdorfman@codeaurora.org>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

3/20 [
Author: Jaehoon Chung
Email: jh80.chung@samsung.com
Subject: mmc: support BKOPS feature for eMMC
Date: Mon, 17 Sep 2012 08:42:02 +0000

commit 950d56acce5d401f477b91d0177605b543d63d07 upstream

Enable eMMC background operations (BKOPS) feature.

If URGENT_BKOPS is set after a response, note that BKOPS are required.
Immediately run BKOPS if required.  Read/write operations should be
requested during BKOPS(LEVEL-1), then issue HPI to interrupt the
ongoing BKOPS and service the foreground operation.
(This patch only controls the LEVEL2/3.)

When repeating the writing 1GB data, at a certain time, performance is
decreased.  At that time, card triggers the Level-3 or Level-2.  After
running bkops, performance is recovered.

Future considerations:
 * Check BKOPS_LEVEL=1 and start BKOPS in a preventive manner.
 * Interrupt ongoing BKOPS before powering off the card.
 * How do we get BKOPS_STATUS value (periodically send ext_csd command)?
 * If using periodic bkops, also consider runtime_pm control.

Signed-off-by: Jaehoon Chung <jh80.chung@samsung.com>
Signed-off-by: Kyungmin Park <kyungmin.park@samsung.com>
Signed-off-by: Konstantin Dorfman <kdorfman@codeaurora.org>
Reviewed-by: Maya Erez <merez@codeaurora.org>
Signed-off-by: Chris Ball <cjb@laptop.org>
[Just a minior modification to rebase to current context]
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

4/20 [
Author: Konstantin Dorfman
Email: kdorfman@codeaurora.org
Subject: mmc: fix async request mechanism for sequential read scenarios
Date: Mon, 14 Jan 2013 14:28:17 -0500

commit 2220eedfd7aea69008173a224975e10284fbe854 upstream

When current request is running on the bus and if next request fetched
by mmcqd is NULL, mmc context (mmcqd thread) gets blocked until the
current request completes. This means that if new request comes in while
the mmcqd thread is blocked, this new request can not be prepared in
parallel to current ongoing request. This may result in delaying the new
request execution and increase it's latency.

This change allows to wake up the MMC thread on new request arrival.
Now once the MMC thread is woken up, a new request can be fetched and
prepared in parallel to the current running request which means this new
request can be started immediately after the current running request
completes.

With this change read throughput is improved by 16%.

Signed-off-by: Konstantin Dorfman <kdorfman@codeaurora.org>
Reviewed-by: Seungwon Jeon <tgih.jun@samsung.com>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

5/20 [
Author: Ulf Hansson
Email: ulf.hansson@linaro.org
Subject: mmc: core: Use generic CMD6 time while switching to eMMC HS200 mode
Date: Tue, 14 Jan 2014 17:36:21 +0100

commit 57de31f6351ecad9212a26d2112b546e4c8b4a5b upstream

Conform to the eMMC spec and use the CMD6 generic timeout from the
EXT_CSD register, when switching to HS200 mode.

Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Chris Ball <chris@printf.net>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

6/20 [
Author: Dong Aisheng
Email: b29396@freescale.com
Subject: mmc: core: mmc DDR mode should not depend on UHS_DDR50
Date: Wed, 30 Oct 2013 22:09:53 +0800

commit 83cc16d767f94edf5821cc89d8300ddb6785810c upstream

The MMC_CAP_UHS_DDR50 must work on 1.8v.
However, the eMMC DDR mode can work on either 1.8v or 3.3v and
should not depend on UHS_DDR50.
So get rid of this limitation to let controller without 1.8v
signal voltage support can also work for eMMC DDR mode if it claims.

Signed-off-by: Dong Aisheng <b29396@freescale.com>
Acked-by: Shawn Guo <shawn.guo@linaro.org>
Acked-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

7/20 [
Author: Minjian Wu
Email: minjianwu@micron.com
Subject: mmc: core: Set data timeout for mmc bus test commands (CMD14 and CMD19).
Date: Sat, 24 Aug 2013 23:25:12 -0400

commit 84532e33975bd8fc969c77c8a2a980df2ec096a5 upstream

Signed-off-by: Minjian Wu <minjianwu@micron.com>
Acked-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

8/20 [
Author: Fredrik Soderstedt
Email: fredrik.soderstedt@stericsson.com
Subject: mmc: core: Only execute tuning for SDR50 and SDR104
Date: Wed, 17 Apr 2013 13:50:53 +0200

commit 810e08ee425f8d7327e4b30069a9b2b3dccfc67d upstream

Only execute tuning for sd and sdio devices that are using
SDR50 or SDR104.

Make sure clock is hold during tuning for sdio devices.

Signed-off-by: Fredrik Soderstedt <fredrik.soderstedt@stericsson.com>
Acked-by: Johan Rudholm <jrudholm@gmail.com>
Acked-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Chris Ball <cjb@laptop.org>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

9/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc: octeon_mmc: Use octeon_bootbus_sem.
Date: Fri, 26 Jul 2013 11:50:47 -0700

Source: Cavium SDK 3.1.0-515

Use the global bootbus semaphore to prevent bus errors in drivers that
share the bootbus.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

10/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc: octeon_mmc: Handler multiple slots, and fix bugs.
Date: Tue, 29 Oct 2013 13:56:30 -0700

Source: Cavium SDK 3.1.0-515

Get rid of unneeded bus resets, multi-block DMA not supported, and fix
power GPIO things.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

11/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc: octeon_mmc: Add driver parameters to limit multi-block transfers.
Date: Thu, 31 Oct 2013 14:26:38 -0700

Source: Cavium SDK 3.1.0-515

These are to aid is reducing bus contention issues.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

12/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc: octeon_mmc: Fix error recovery.
Date: Fri, 1 Nov 2013 14:18:49 -0700

Source: Cavium SDK 3.1.0-515

Also remove dead code from failed SG dma attempt.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

13/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc octeon_mmc: Clean up device tree accesses.
Date: Thu, 14 Nov 2013 16:41:39 -0800

Source: Cavium SDK 3.1.0-515

Use the of_property_read_u32() helper instead of open coding it.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

14/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc octeon_mmc: Add configurable clock skew settings.
Date: Fri, 15 Nov 2013 11:35:05 -0800

Source: Cavium SDK 3.1.0-515

"cavium,cmd-clk-skew" and "cavium,dat-clk-skew" device tree properties
specify (in pS) the amount of delay past the clock edge to sample the
respective signals.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

15/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: mmc octeon_mmc: Set MIO_BOOT_CTL correctly on cn70XX
Date: Fri, 15 Nov 2013 12:07:15 -0800

Source: Cavium SDK 3.1.0-515

Part of acquiring access to the bootbus is selecting mmc mode on
cn70xx.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

16/20 [
Author: Yang Wei
Email: Wei.Yang@windriver.com
Subject: mmc:octeon-mmc:Backport mmc features from SDK3.1.0-P3
Date: Mon, 4 Aug 2014 14:16:22 +0800

Source: Cavium SDK 3.1.0-P3

It includes:
1) Scatter-Gather DMA fix in the eMMC driver
2) (N-1) eMMC block fix
3) eMMC driver DDR support

Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

17/20 [
Author: David Daney
Email: david.daney@cavium.com
Subject: MIPS: OCTEON: Add semaphore to serialize bootbus accesses.
Date: Fri, 26 Jul 2013 11:35:44 -0700

Source: Cavium SDK 3.1.0-515

Some hardware blocks attached to the OCTEON bootbus run asynchronously
to accesses from the CPUs.  These include MMC/SD host, CF(when using
DMA), and NAND controller.  A bus error, or corrupt data may occur if
a CPU is trying to access a bootbus connected device at the same time
the bus is running asynchronous operations.

To work around these problems we add this semaphore that must be
acquired before initiating bootbus activity.  Subsequent patches will
add users for this.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

18/20 [
Author: Chandrakala Chavva
Email: cchavva@caviumnetworks.com
Subject: MIPS: OCTEON: Export octeon_bootbus_sem.
Date: Mon, 14 Oct 2013 11:07:15 -0700

Source: Cavium SDK 3.1.0-515

Export the symbol so that eMMC driver can be built as module.

Bug #8409

Signed-off-by: Chandrakala Chavva <cchavva@caviumnetworks.com>
Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

19/20 [
Author: Yang Wei
Email: Wei.Yang@windriver.com
Subject: mmc:octeon-mmc:Fix building errors:
Date: Mon, 4 Aug 2014 14:38:19 +0800

There are two building errors:

drivers/mmc/host/octeon_mmc.c:131:7: error: 'OCTEON_CN70XX'
undeclared (first use in this function)
drivers/mmc/host/octeon_mmc.c:132:19: error: 'CVMX_MIO_BOOT_CTL'
undeclared (first use in this function)

The fix is picked from a patch of SDK-3.1.0-515
0110-MIPS-OCTEON-Import-new-S.E.-and-adjust-things-to-mat.patch

Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

20/20 [
Author: Yang Wei
Email: Wei.Yang@windriver.com
Subject: mmc:octeon_mmc:use devm_request_and_ioremap instead of devm_ioremap_resource
Date: Mon, 4 Aug 2014 14:46:59 +0800

In 3.4 kernel, devm_ioremap_resource is not introduced, so we have to
use the older API.

Signed-off-by: Yang Wei <Wei.Yang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>