fsl-t2xxx:add hugetlb support
1/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: powerpc: add preempt_enable to function hugepd_free
Date: Sun, 8 Nov 2015 15:07:38 +0000

Because of upstream commit 69111bac42f5
("powerpc: Replace __get_cpu_var uses"), get_cpu_var in function
hugepd_free has been changed to this_cpu_ptr. But get_cpu_var also
contains preempt_disable() and we need the preemption protect when
we call smp_processor_id(). So add preempt_disable() or it will
occurr calltrace as below:

BUG: using smp_processor_id() in preemptible [00000000] code: hugeshmdt01/12258
caller is .free_hugepd_range+0xd4/0x294
CPU: 3 PID: 12258 Comm: hugeshmdt01 Tainted: G        W       4.1.12-WR8.0.0.0_standard #3
Call Trace:
[c000000072f1b760] [c000000000b0f074] .dump_stack+0x9c/0xfc (unreliable)
[c000000072f1b7e0] [c00000000056ea10] .check_preemption_disabled+0x14c/0x154    please wait |
[c000000072f1b880] [c000000000030608] .free_hugepd_range+0xd4/0x294
[c000000072f1b930] [c000000000030e2c] .hugetlb_free_pgd_range+0x1e4/0x420
[c000000072f1ba40] [c0000000001ad724] .free_pgtables+0x170/0x198
[c000000072f1bae0] [c0000000001b4670] .unmap_region+0xe0/0x15c
[c000000072f1bc10] [c0000000001b7524] .do_munmap+0x2d0/0x41c
[c000000072f1bcd0] [c0000000004de2bc] .SyS_shmdt+0xcc/0x1ac
[c000000072f1bd80] [c0000000004de65c] .SyS_ipc+0x2c0/0x318
[c000000072f1be30] [c000000000000698] system_call+0x38/0xc4

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: powerpc: create a function descriptor for init_core_book3e
Date: Thu, 5 Nov 2015 10:34:55 +0800

because of upstream commit 6a3bab90cf78
("powerpc: Remove some unnecessary uses of _GLOBAL() and _STATIC()"),
init_core_book3e was changed to be a local label. But we reference this function
in arch/powerpc/kernel/head_64.S when CONFIG_RELOCATABLE is set. So change it
back to be a function descriptor, or else it will occurr a compile error as below:

 arch/powerpc/kernel/head_64.o: In function `__after_prom_start':
 arch/powerpc/kernel/head_64.S:508: undefined reference to `.init_core_book3e'

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>