fix a bug in drivers/gpio/Kconfig
Issue: LIN5-19294

1/1 [
Author: fupan li
Email: fupan.li@windriver.com
Subject: fix a bug in drivers/gpio/Kconfig
Date: Fri, 22 Aug 2014 14:56:37 +0800

commit 0571734bf05ea2f4683942b06b7070214986e749
introduce a bug in drivers/gpio/Kconfig where two "space" was missing on
line 170 and 171.

This give us this log when doing make -C build linux-windriver.menuconfig
ERROR: Function failed: do_configure (see
/buildarea4/idp-nightly-log/tnie_idp_1408211319/gigbyte_glibc-idp_allfeatur
e_srm_grsec_2/bitbake_build/tmp/work/intel_atom_baytrail-wrs-linux/linux-wi
ndriver-3.4-r0/temp/do_configure/log.do_configure.11040 for further
information)
ERROR: Logfile of failure stored in:
/buildarea4/idp-nightly-log/tnie_idp_1408211319/gigbyte_glibc-idp_allfeatur
e_srm_grsec_2/bitbake_build/tmp/work/intel_atom_baytrail-wrs-linux/linux-wi
ndriver-3.4-r0/temp/do_configure/log.do_configure.11040
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| NOTE: make oldconfig
|   GEN
/buildarea4/idp-nightly-log/tnie_idp_1408211319/gigbyte_glibc-idp_allfeatur
e_srm_grsec_2/bitbake_build/tmp/work/intel_atom_baytrail-wrs-linux/linux-wi
ndriver-3.4-r0/linux-intel-atom-baytrail-standard-build/Makefile
| scripts/kconfig/conf --oldconfig Kconfig
| drivers/gpio/Kconfig:171: syntax error
| drivers/gpio/Kconfig:170: unknown option "To"
| drivers/gpio/Kconfig:171: unknown option "be"
| make[3]: *** [oldconfig] Error 1
| make[2]: *** [oldconfig] Error 2
| make[1]: *** [sub-make] Error 2
| make: *** [all] Error 2
| ERROR: oe_runmake failed

The fix was to add 2 spaces char in line 170 and 171 to align everything.

Signed-off-by: Arnaud Blanchard <Arnaud.Blanchard@windriver.com>
Signed-off-by: fupan li <fupan.li@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>