kgdb Kconfig: no depend on USB module
Issue: LIN7-3437

1/1 [
Author: Li Wang
Email: li.wang@windriver.com
Subject: kgdb Kconfig: no depend on USB module
Date: Wed, 22 Apr 2015 17:23:31 +0800

when kgdb use usb keyboard, it must depend on usb built-in kernel.
if compile kgdb with usb module, it happens the follow error:
kernel/built-in.o: In function `kdb_get_usb_char':
(.text+xxx): undefined reference to `usb_poll_irq'

Signed-off-by: Li Wang <li.wang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>