add fsl-p10xx async BSP for wrlinux 7.0
Rally: US52720

1/3 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: powerpc/85xx: l2sram: include linux/of_address.h
Date: Mon, 17 Aug 2015 15:19:48 +0800

Fix the following build error:
  arch/powerpc/sysdev/fsl_85xx_l2ctlr.c: In function 'mpc85xx_l2ctlr_of_probe':
  arch/powerpc/sysdev/fsl_85xx_l2ctlr.c:105:2: error: implicit declaration of function 'of_iomap' [-Werror=implicit-function-declaration]
    l2ctlr = of_iomap(dev->dev.of_node, 0);
    ^
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

2/3 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: can: flexcan: fix the access of register with the wrong endian mode
Date: Wed, 2 Sep 2015 10:27:13 +0800

For the flexcan on powerpc platform, both the core and module are in
big endian mode (!core_is_little && !module_is_littel). In this case,
we should use the API for big endian mode instead of little endian.
Actually we shouldn't care about the core endian mode in a specific
driver since it will be handled correctly by the corresponding API.
All we need is to check the module endian mode. If it is in little
endian, the LE API should be used. If it is in big endian, then BE
API should be used.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

3/3 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: can: flexcan: fix two build warnings
Date: Mon, 7 Sep 2015 11:11:44 +0800

Add the ifndef CONFIG_CAN_FLEXCAN_RX_FIFO_EN to fix the following two
build warnings:
  In function 'flexcan_poll':
  drivers/net/can/flexcan.c:836:6:
  warning: unused variable 'mailbox' [-Wunused-variable]
    u32 mailbox;
        ^
  drivers/net/can/flexcan.c:835:16:
  warning: unused variable 'iflag1' [-Wunused-variable]
    unsigned long iflag1;
                ^

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>