cryptodev: fix compile error when enable CONFIG_CRYPTODEV
1/2 [
Author: Liwei Song
Email: liwei.song@windriver.com
Subject: cryptodev: fix compile error when enable CONFIG_CRYPTODEV
Date: Sun, 6 Nov 2016 21:52:43 -0500

Fix the following compile error:
error: implicit declaration of function 'aead_request_set_assoc'
error: implicit declaration of function 'crypto_alloc_ablkcipher'
error: too many arguments to function ‘get_user_pages’
error: implicit declaration of function ‘page_cache_release’
error: implicit declaration of function ‘get_unused_fd’

This is due to the old function was used in cryptodev driver,
as the kernel updated, the function in cryptodev was not touched.

To fix this, use the new version of function instead of the
old ones.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

2/2 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: cryptodev: stomp dynamic version numbering for in tree builds
Date: Sun, 6 Nov 2016 21:52:44 -0500

The temporary creation of a version header adds complications
for builds where src != build (of which it doesn't use $(src)
at all) and plus the dependencies on version.h were not working,
leading to compile failures.

For an in tree build, the version will be never changing, so
just make a static version header and junk all the Makefile
complexity that we don't need.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>