cav-octeon3 : some warning in the kernel's comiple log
Issue: LIN7-1659

1/3 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: OCTEON: fix a compile warning problem about MTD_COMPLEX_MAPPING
Date: Sat, 15 Nov 2014 03:19:20 +0000

There is a compile warning about MTD_COMPLEX_MAPPINGS:
    warning: (CAVIUM_OCTEON_SOC) selects MTD_COMPLEX_MAPPINGS which has
    unmet direct dependencies (MTD && HAS_IOMEM)

MTD_COMPLEX_MAPPINGS depends on MTD config which is not supported for OCTEON, so
remove it.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/3 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: OCTEON: fix a compile warning problem about usb
Date: Sat, 15 Nov 2014 03:19:20 +0000

The commit "ed usb clock init for octeon to be called from dwc3 driver"
introduces the following typo problem of platform_device:
    drivers/usb/dwc3/core.c:49:12: note: expected 'struct paltform_device *'
    but argument is of type 'struct platform_device *'

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

3/3 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: OCTEON: Delete the redefinition of RAPIDIO in Kconfig
Date: Tue, 18 Nov 2014 03:06:26 +0000

There is a compile warning about RAPIDIO:
    warning: ignoring type redefinition of 'RAPIDIO' from 'boolean' to 'tristate'

The RAPIDIO config has been defined in arch/mips/Kconfig, so it is no need to
redefine it in octeon Kconfig, and delete it from octeon Kconfig.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>