IT87 driver of gigabyte
1/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Add support for IT8782F and IT8783E/F
Date: Fri, 2 Mar 2012 11:46:44 -0800

commit 0531d98b1f2ec6f92074e5b2a74927b865bc605c upstream

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Jean Delvare <khali@linux-fr.org>
]

2/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Create voltage attributes only if voltage is enabled
Date: Sat, 24 Mar 2012 21:49:54 -0700

commit 9172b5d124c2f54374d8cc5ed6098ecd8fb988cd upstream

On IT8782F and IT8783F, some voltage input pins may be disabled. Don't create
sysfs attribute files if that is the case.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Jean Delvare <khali@linux-fr.org>
]

3/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Convert to use devm_kzalloc and devm_request_region
Date: Sat, 24 Mar 2012 21:54:41 -0700

commit 62a1d05f0ecf9c6a376bbe310718ed76582496a2 upstream

This makes the code a bit simpler and smaller.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Jean Delvare <khali@linux-fr.org>
]

4/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Make temp3 attribute conditional for IT8782F
Date: Mon, 26 Mar 2012 16:17:41 -0700

commit 4573acbc461b8089198500cee06ef0cdc5b70e82 upstream

On IT8782F, temp3 is only supported if UART6 is disabled.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Jean Delvare <khali@linux-fr.org>
]

5/26 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: hwmon: remove use of __devexit_p
Date: Mon, 19 Nov 2012 13:21:20 -0500

commit 9e5e9b7a92e4e2e4ac1f0d6aa181639637660e45 upstream

CONFIG_HOTPLUG is going away as an option so __devexit_p is no longer
needed.

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Hans de Goede <hdegoede@redhat.com>
Cc: Jean Delvare <khali@linux-fr.org>
Cc: Alistair John Strachan <alistair@devzero.co.uk>
Cc: Fenghua Yu <fenghua.yu@intel.com>
Cc: Juerg Haefliger <juergh@gmail.com>
Cc: Andreas Herrmann <herrmann.der.user@googlemail.com>
Cc: Clemens Ladisch <clemens@ladisch.de>
Cc: Rudolf Marek <r.marek@assembler.cz>
Cc: Jim Cromie <jim.cromie@gmail.com>
Cc: "Mark M. Hoffman" <mhoffman@lightlink.com>
Cc: Roger Lucas <vt8231@hiddenengine.co.uk>
Acked-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

6/26 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: hwmon: remove use of __devinit
Date: Mon, 19 Nov 2012 13:22:35 -0500

commit 6c931ae1c09a9618852c9619dac71f1f77776e3b upstream

CONFIG_HOTPLUG is going away as an option so __devinit is no longer
needed.

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Hans de Goede <hdegoede@redhat.com>
Cc: Jean Delvare <khali@linux-fr.org>
Cc: Alistair John Strachan <alistair@devzero.co.uk>
Cc: Fenghua Yu <fenghua.yu@intel.com>
Cc: Juerg Haefliger <juergh@gmail.com>
Cc: Andreas Herrmann <herrmann.der.user@googlemail.com>
Cc: Clemens Ladisch <clemens@ladisch.de>
Cc: Rudolf Marek <r.marek@assembler.cz>
Cc: Jim Cromie <jim.cromie@gmail.com>
Cc: "Mark M. Hoffman" <mhoffman@lightlink.com>
Cc: Roger Lucas <vt8231@hiddenengine.co.uk>
Acked-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

7/26 [
Author: Bill Pemberton
Email: wfp5p@virginia.edu
Subject: hwmon: remove use of __devexit
Date: Mon, 19 Nov 2012 13:25:51 -0500

commit 281dfd0b6ed5403f5b9b1669f2a37a4f8cfc11c1 upstream

CONFIG_HOTPLUG is going away as an option so __devexit is no
longer needed.

Signed-off-by: Bill Pemberton <wfp5p@virginia.edu>
Cc: Hans de Goede <hdegoede@redhat.com>
Cc: Jean Delvare <khali@linux-fr.org>
Cc: Alistair John Strachan <alistair@devzero.co.uk>
Cc: Fenghua Yu <fenghua.yu@intel.com>
Cc: Juerg Haefliger <juergh@gmail.com>
Cc: Andreas Herrmann <herrmann.der.user@googlemail.com>
Cc: Clemens Ladisch <clemens@ladisch.de>
Cc: Rudolf Marek <r.marek@assembler.cz>
Cc: Jim Cromie <jim.cromie@gmail.com>
Cc: "Mark M. Hoffman" <mhoffman@lightlink.com>
Cc: Roger Lucas <vt8231@hiddenengine.co.uk>
Acked-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
]

8/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Save temperature registers in 2-dimensional array
Date: Wed, 19 Dec 2012 22:17:00 +0100

commit 60ca385a530405ab501773ef4c9e222825a6cd40 upstream

Cleaner code, fewer checkpatch errors, and reduced code size
(saves more than 500 bytes on x86-64).

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

9/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Save voltage register values in 2-dimensional array
Date: Wed, 19 Dec 2012 22:17:00 +0100

commit 929c6a5696f5efe7f4213cf9d8b12144a0c0c650 upstream

Reduces code size (more than 600 bytes on x86_64),
and gets rid of some checkpatch errors.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

10/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Replace macro defining tempX_type sensors with direct definitions
Date: Wed, 19 Dec 2012 22:17:01 +0100

commit 2cece01ffd622ab65a4f5a6704e3a74c1174d2fa upstream

The macro name show_sensor_offset is confusing since it related to the sensor
type, not an offset - even more so when we introduce offset attributes later on.
Replace it with direct definitions, and replace the show_sensor/set_sensor
function names with show_temp_type/set_temp_type. This also resolves a
checkpatch error.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

11/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Introduce support for tempX_offset sysfs attribute
Date: Wed, 19 Dec 2012 22:17:01 +0100

commit 161d898ac974818156afe48d755578bfd0d6e7c0 upstream

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

12/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Save fan registers in 2-dimensional array
Date: Wed, 19 Dec 2012 22:17:01 +0100

commit e1169ba0aea187d0ea15d6f98bc818cab37335e5 upstream

Also unify fan functions to use the same code for 8 and 16 bit fans.

This patch reduces code size by approximately 1,200 bytes on x86_64.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

13/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Avoid quoted string splits across lines
Date: Wed, 19 Dec 2012 22:17:01 +0100

commit 1d9bcf6aef0af67901a54ad4c4458e6a2124b769 upstream

Fix the respective checkpatch warnings.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

14/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Replace pwm group macro with direct attribute definitions
Date: Wed, 19 Dec 2012 22:17:02 +0100

commit c4458db3688a603a4cb4b1d01ca10ff0d58bc8eb upstream

Fix checkpatch error:

ERROR: Macros with multiple statements should be enclosed in a do - while loop

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

15/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Manage device specific features with table
Date: Wed, 19 Dec 2012 22:17:02 +0100

commit 483db43e81f4958e3cd11a990112e8082a6a5261 upstream

This simplifies the code, improves runtime performance, reduces
code size (about 280 bytes on x86_64), and makes it easier
to add support for new devices.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

16/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Report thermal sensor type as Intel PECI if appropriate
Date: Wed, 19 Dec 2012 22:17:02 +0100

commit 5d8d2f2bdbd0812dfad05ca37e4b28912fca7e33 upstream

IT8721 and IT8728 support Intel PECI temperature reporting. Each sensor
can be programmed to display the temperature reported on the PECI interface.

If configured for Intel PECI, the driver reported the wrong sensor type for
the respective thermal sensor. Fix the code to correctly report it as
"Intel PECI (6)".

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

17/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Support PECI for additional chips
Date: Wed, 19 Dec 2012 22:17:02 +0100

commit 19529784785d8fd164079e1008c8b1970d6062ee upstream

Extend support for reporting and selecting PECI temperature sensors
to IT8718, IT8720, IT8782, and IT8783. For IT8721, report the sensor
type for temp2 as Intel PECI (6) if the chip is configured to report
the PCH temperature.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

18/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: Replace SENSORS_LIMIT with clamp_val
Date: Wed, 9 Jan 2013 08:09:34 -0800

commit 2a844c148e1f714ebf42cb96e1b172ce394c36c9 upstream

SENSORS_LIMIT and the generic clamp_val have the same functionality,
and clamp_val is more efficient.

This patch reduces text size by 9052 bytes and bss size by 11624 bytes
for x86_64 builds.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: George Joseph <george.joseph@fairview5.com>
Acked-by: Jean Delvare <khali@linux-fr.org>
]

19/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: (it87) Add support for IT8771E and IT8772E
Date: Fri, 7 Sep 2012 17:34:41 -0600

commit b06367070de3d9f50e4f8f82b92e77ba9a8ebf8f upstream

Assume that IT8771E and IT8772E are fully compatible with IT8728F.

IT8771E support contributed by Kelly Anderson.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Reviewed-by: Jean Delvare <khali@linux-fr.org>
]

20/26 [
Author: Guenter Roeck
Email: linux@roeck-us.net
Subject: hwmon: Fix CamelCase checkpatch warnings
Date: Wed, 13 Mar 2013 16:40:39 -0700

commit 088ce2ac9ebac5c74faf4d39083627875fa6f0f0 upstream

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
]

21/26 [
Author: Jingoo Han
Email: jg1.han@samsung.com
Subject: hwmon: use dev_get_platdata()
Date: Tue, 30 Jul 2013 17:13:06 +0900

commit a8b3a3a53f9a814e9938ea9cc179086ff5c0a387 upstream

Use the wrapper function for retrieving the platform data instead of
accessing dev->platform_data directly.

Signed-off-by: Jingoo Han <jg1.han@samsung.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
]

22/26 [
Author: Rudolf Marek
Email: r.marek@assembler.cz
Subject: hwmon: (it87) Add support for the ITE IT8603E
Date: Wed, 29 Jan 2014 20:40:08 +0100

commit c145d5c628c8ca02dabbf6829ae19ce525d42796 upstream

Add support for IT8603E.

This closes bug #57861:
https://bugzilla.kernel.org/show_bug.cgi?id=57861

[JD: Fixes and clean-ups.]

Signed-off-by: Rudolf Marek <r.marek@assembler.cz>
Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

23/26 [
Author: Jean Delvare
Email: khali@linux-fr.org
Subject: hwmon: (it87) Print proper names for the IT8771E and IT8772E
Date: Wed, 29 Jan 2014 20:40:08 +0100

commit b523bb75098b1ed4dd98cb651b7b71e5b8c4f533 upstream

The driver prints IT8771F and IT8772F instead of IT8771E and IT8772E
respectively when the driver is loaded. This is a cosmetic only bug
but let's fix it.

Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

24/26 [
Author: Jean Delvare
Email: khali@linux-fr.org
Subject: Update Jean Delvare's e-mail address
Date: Wed, 29 Jan 2014 20:40:08 +0100

commit 7c81c60f3789a082e141d7a013392af5f78db16a upstream

Signed-off-by: Jean Delvare <khali@linux-fr.org>
]

25/26 [
Author: Rudolf Marek
Email: r.marek@assembler.cz
Subject: hwmon: (it87) Fix IT8603E define name
Date: Fri, 4 Apr 2014 18:01:35 +0200

commit 7183ae8c203f81d1727cfaf430a9f6fa8a07c99c upstream

Fix small typo in the define name for IT8603E.

Signed-off-by: Rudolf Marek <r.marek@assembler.cz>
Signed-off-by: Jean Delvare <jdelvare@suse.de>
]

26/26 [
Author: Rudolf Marek
Email: r.marek@assembler.cz
Subject: hwmon: (it87) Add support for IT8623E
Date: Fri, 4 Apr 2014 18:01:35 +0200

commit 574e9bd8fa44d8c6d90a46d97d1a75257a89b424 upstream

Add support for the IT8623E found on Asus motherboards. It has same
hardware monitoring block as IT8603E.

Signed-off-by: Rudolf Marek <r.marek@assembler.cz>
Signed-off-by: Jean Delvare <jdelvare@suse.de>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>