ipv6/dccp: do not inherit ipv6_mc_list from parent
Issue: LIN7-8204

1/2 [
Author: Qi Hou
Email: qi.hou@windriver.com
Subject: ipv6: correct dccp_doff to dccph_doff
Date: Wed, 8 Mar 2017 09:59:13 +0800

In struct dccp_hdr, there is no field named "dccp_doff" but a dccph_doff.

So correct the reference to dccp_doff to dccph_doff. Or there would be a
compile error, like below:

|kernel-source/net/dccp/ipv6.c:769:40: error: 'const struct dccp_hdr' has
 no member named 'dccp_doff'
|   return __sk_receive_skb(sk, skb, 1, dh->dccp_doff * 4) ? -1 : 0;
|                                         ^

It is introduced by commit 960570cea4fc ("tcp: take care of truncations
done by sk_filter()"). According to the changes made by this commit, it
seems that this commit has made by merging two commit commits from upstream
They are commit ac6e780070e30 ("tcp: take care of truncations done by
sk_filter()") and commit 4f0c40d94461 ("dccp: limit sk_filter trim to
payload").

In commit 960570cea4fc, "dccph_doff" was mistakenly written as "dccp_doff".
To fix it, correct "dccp_doff" to "dccph_doff".

Signed-off-by: Qi Hou <qi.hou@windriver.com>
]

2/2 [
Author: WANG Cong
Email: xiyou.wangcong@gmail.com
Subject: ipv6/dccp: do not inherit ipv6_mc_list from parent
Date: Tue, 9 May 2017 16:59:54 -0700

commit 83eaddab4378db256d00d295bda6ca997cd13a52 upstream

Like commit 657831ffc38e ("dccp/tcp: do not inherit mc_list from parent")
we should clear ipv6_mc_list etc. for IPv6 sockets too.

Cc: Eric Dumazet <edumazet@google.com>
Signed-off-by: Cong Wang <xiyou.wangcong@gmail.com>
Acked-by: Eric Dumazet <edumazet@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>