fsl-t2xxx: Add uio driver suppport
1/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio: Allow drivers to override the pgprot for mmap()
Date: Wed, 3 Sep 2014 18:06:05 +0800

For some devices, the default behavior of pgprot_noncached() is not
appropriate for all of its mappable regions. This provides a means for
the kernel side of the UIO driver to override the flags without having
to implement its own full mmap callback.

Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: Geoff Thorpe <geoff@geoffthorpe.net>
Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

2/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio/srio: Add FSL Serial RapidIO UIO driver support
Date: Thu, 4 Sep 2014 18:14:55 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add support to expose Serial RapidIO controller to user space.  We
split the controller between general control and per port memory bus
access.

Also add support to handle the SRIO error interrupt.

Signed-off-by: Kai Jiang <Kai.Jiang@freescale.com>
Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: Liu Gang <Gang.Liu@freescale.com>
Change-Id: Ic8ef32d5b665a94b35a3dd174691c3eca41339ea
Reviewed-on: http://git.am.freescale.net:8181/979
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

3/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio/dma: Add FSL PPC DMA UIO driver support
Date: Thu, 4 Sep 2014 18:16:11 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add support to expose FSL PPC DMA controller to user space.  Each DMA
controller is split until multiple (normally four) separate channels.
We map each channel into a unique UIO device.

Signed-off-by: Kai Jiang <Kai.Jiang@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: Liu Gang <Gang.Liu@freescale.com>
Change-Id: I6914bda4bf59ccf6a9f261b88260f03e7965ffa3
Reviewed-on: http://git.am.freescale.net:8181/980
Reviewed-by: Lian Minghuan-B31939 <Minghuan.Lian@freescale.com>
Reviewed-by: Zang Tiefei-R61911 <tie-fei.zang@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

4/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: powerpc/uio: Add uio driver for rapidio message and doorbell units
Date: Thu, 4 Sep 2014 18:16:56 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

For using the rapidio message and doorbell units in linux user space,
need to build the uio devices in kernel space. The message and
doorbell uio devices in kernel will map the units registers to user
space and then the applications in user space can configure those
registers and use the rapidio message and doorbell units.

Signed-off-by: Liu Gang <Gang.Liu@freescale.com>
Change-Id: Icfbc6e3cedc627b88143ae1656e6aebc4bd75684
Reviewed-on: http://git.am.freescale.net:8181/981
Reviewed-by: Lian Minghuan-B31939 <Minghuan.Lian@freescale.com>
Reviewed-by: Zang Tiefei-R61911 <tie-fei.zang@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

5/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio: add support to map SEC to user space
Date: Thu, 4 Sep 2014 18:20:43 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

This driver would map all SEC spaces to uio devices and
map all the job rings to uio devices. The SEC space map
the whole SEC register space to user space. Job ring uio
device is convenient for job descriptor. The current
version reserve the interrupt function for job ring.

Change-Id: I876d46de1870e664ac87a526aead2cfe9592fc81
Signed-off-by: Liu po <po.liu@freescale.com>
Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/1196
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

6/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio: Add FSL RMan UIO driver support
Date: Thu, 4 Sep 2014 18:33:51 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

Add support to expose FSL RMan controller to user space via UIO system.
The RMan is composed of a global configuration and multiple inbound
classification units. We map the global configuration as one UIO device
and each classification unit as a unique UIO device.

Change-Id: Ia491dae0d82c5fee9eb7e2b535305b557ba7329a
Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/922
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

7/15 [
Author: "Lu.Jiang"
Email: lu.jiang@windriver.com
Subject: uio: add support to map SRAM to userspace
Date: Mon, 22 Sep 2014 11:00:58 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

This driver config the L2 Cache to be SRAM mode and map the SRAM to user
space. The size and the address of SRAM are passed in the U-boot command
line as format: cache-sram=addr,size.
Please notice that this driver is exclusive with config FSL_85XX_CACHE_SRAM.

Signed-off-by: Hou Zhiqiang <B48286@freescale.com>
Change-Id: Ib0433acd459413fec5f5218751b0db79309895fd
Reviewed-on: http://git.am.freescale.net:8181/10295
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Mingkai Hu <Mingkai.Hu@freescale.com>
Reviewed-by: Po Liu <Po.Liu@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
Signed-off-by: Lu.Jiang <lu.jiang@windriver.com>
]

8/15 [
Author: Hou Zhiqiang
Email: B48286@freescale.com
Subject: uio: fix up fsl_sec_uio driver compilation error
Date: Wed, 2 Apr 2014 17:12:52 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

| drivers/uio/fsl_sec_uio.c: In function 'fsl_sec_jr_probe':
| drivers/uio/fsl_sec_uio.c:186:2: error: implicit declaration of function 'of_address_to_resource' [-Werror=implicit-function-declaration]
|   ret = of_address_to_resource(jr_node, 0, &regs);
|   ^
| drivers/uio/fsl_sec_uio.c:211:2: error: implicit declaration of function 'irq_of_parse_and_map' [-Werror=implicit-function-declaration]
|   jr->irq = irq_of_parse_and_map(jr_node, 0);
|   ^
| drivers/uio/fsl_sec_uio.c: In function 'fsl_sec_probe':
| drivers/uio/fsl_sec_uio.c:296:2: error: implicit declaration of function 'of_iomap' [-Werror=implicit-function-declaration]
|   sec_dev->global_regs = of_iomap(sec_node, 0);

Signed-off-by: Hou Zhiqiang <B48286@freescale.com>
Change-Id: I5bcaa4e15c48c7aa80edb478ac86ad1aa6f2eea4
Reviewed-on: http://git.am.freescale.net:8181/10591
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Mingkai Hu <Mingkai.Hu@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

9/15 [
Author: Liu Gang
Email: Gang.Liu@freescale.com
Subject: uio/dma: Update the UIO DMA module based on the new DMA dts
Date: Mon, 11 Nov 2013 18:34:26 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

The updated DMA dts files added a new compatible "fsl,elo3-dma"
for some new platforms, and removed the property "cell-index".
So the code should be updated based on those changes.

Signed-off-by: Liu Gang <Gang.Liu@freescale.com>
Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Change-Id: I66603f76ca0feeb689c49b9eeb9c0621eb5c3897
Reviewed-on: http://git.am.freescale.net:8181/6555
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Tiefei Zang <roy.zang@freescale.com>
Reviewed-by: Thomas Trefny <Tom.Trefny@freescale.com>
(cherry picked from commit 18af7f2d2fe1f182b7c2716eaabb613d5523d2d8)
Reviewed-on: http://git.am.freescale.net:8181/10811
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

10/15 [
Author: Liu Gang
Email: gang.liu@freescale.com
Subject: UIO/DMA: Add dma uio private mmap function
Date: Thu, 17 Apr 2014 18:19:16 +0800

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

UIO mmap cannot map an unaligned page address, and
the PowerPC DMA register space has an unaligned
page base address. So the mmap for DMA register
address should be supported via a private function.

Signed-off-by: Liu Gang <gang.liu@freescale.com>
Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Change-Id: Ic5672dd4f86031fab34830d47e231fb1c46b2070
Reviewed-on: http://git.am.freescale.net:8181/11081
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Mingkai Hu <Mingkai.Hu@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

11/15 [
Author: Minghuan Lian
Email: Minghuan.Lian@freescale.com
Subject: fsl/RMan: add RMan private mmap function
Date: Tue, 6 May 2014 17:26:31 +0000

[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

The latest kernel UIO mmap() can not map an unaligned page
address, however the RMan global register is not page aligned,
and an inbound block register size is also less than a page size.
So, the patch provides a private mmap function to support RMan
register map.

Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Change-Id: Idfff04bb0cfa418b3ccb07448ad31a75d8f04ca7
Reviewed-on: http://git.am.freescale.net:8181/11886
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Gang Liu <Gang.Liu@freescale.com>
Reviewed-by: Tiefei Zang <tie-fei.zang@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
]

12/15 [
Author: Jiang Lu
Email: lu.jiang@windriver.com
Subject: fsl_uio:Add missing header for fsl uio drivers
Date: Fri, 24 Oct 2014 16:59:17 +0800

Add missing header for fsl uio drivers.

Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

13/15 [
Author: Liu Gang
Email: Gang.Liu@freescale.com
Subject: UIO/RapidIO: Add workaround for erratum A-008116
Date: Wed, 29 Oct 2014 19:56:26 +0800

Erratum A-008116 can cause a SRIO phyiscal or logical/transport
error interrupt (PINTn) that orginates on port 2 is incorrectly
reported as originating on port 1.

Valid workaround needed if using Serial RapidIO port 2. Upon
detection of a Serial RapidIO interrupt, each port's LTLEDCSR
and PnEDCSR registers must be read to determine the port origin.

Signed-off-by: Liu Gang <Gang.Liu@freescale.com>
Change-Id: I309106e79853cf08b9b546924a41ec74ad4b8b53
Reviewed-on: http://git.am.freescale.net:8181/22437
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Reviewed-by: Mingkai Hu <Mingkai.Hu@freescale.com>
Reviewed-by: Richard Schmitt <richard.schmitt@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

14/15 [
Author: Minghuan Lian
Email: Minghuan.Lian@freescale.com
Subject: fsl/RMan: Fix RMan global register initialization
Date: Thu, 23 Oct 2014 20:29:39 +0800

If RMan dts node does not contain child node 'fsl,rman-global-cfg'
or the child node does not contain property 'reg', RMan global
register will not be initialized correctly. The patch is to fix
this issue.

Signed-off-by: Minghuan Lian <Minghuan.Lian@freescale.com>
Change-Id: Ifc781a28b3f6c59efe7fe44c37fd6f7c0e5efc1a
Reviewed-on: http://git.am.freescale.net:8181/21985
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Tiefei Zang <tie-fei.zang@freescale.com>
Reviewed-by: Richard Schmitt <richard.schmitt@freescale.com>
[Lu:Original patch taken from
QorIQ-SDK-V1.7-SOURCE-20141218-yocto.iso]
Signed-off-by: Jiang Lu <lu.jiang@windriver.com>
]

15/15 [
Author: Bin Jiang
Email: bin.jiang@windriver.com
Subject: uio: align uio memory region
Date: Tue, 18 Feb 2014 15:17:09 +0800

The uio memory region should be at page boundaries in order for
user mmap() to work. The region size is rounded to a multiple of
PAGE_SIZE.

Signed-off-by: Bin Jiang <bin.jiang@windriver.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>