add the p2020rdb-pca board support for fsl-p2020 BSP
CQID: WIND00416484

1/4 [
Author: Tang Yuantian
Email: Yuantian.Tang@freescale.com
Subject: powerpc/85xx: Fix pci base address error for p2020rdb-pc in dts
Date: Fri, 13 Jul 2012 10:27:35 +0800

commit 771e6089e3638ea1e06700a9dc4660cd678e35bb upstream

Signed-off-by: Tang Yuantian <Yuantian.Tang@freescale.com>
Signed-off-by: Kumar Gala <galak@kernel.crashing.org>
]

2/4 [
Author: Tang Yuantian
Email: Yuantian.Tang@freescale.com
Subject: powerpc/85xx: Adds IEEE1588 node in dts
Date: Thu, 19 Apr 2012 16:16:39 +0800

The new property "fsl,ts-to-buffer" is introduced for
platforms which can get tx time stamp from skb buffer.
Some platforms, like mpc8572ds, can only get tx time stamp from
register, so these platforms have no this property.

Signed-off-by: Tang Yuantian <b29983@freescale.com>
[Kevin: Original patch taken from the FSL
QorIQ-SDK-V1.3-SOURCE-20121114-yocto.iso.]
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

3/4 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: powerpc/85xx: add a dummy rio device node for p2020rdb-pc board
Date: Wed, 8 May 2013 12:01:26 +0800

The sRIO is not enabled on the p2020rdb-pc board. But the label 'rio"
is referenced by p2020si-post.dtsi. So add a dummy rio device node
for p2020rdb-pc board to fix the following build error:
  Error: arch/powerpc/boot/dts/fsl/p2020si-post.dtsi:142.2-3
  label or path, 'rio', not found

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

4/4 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: powerpc/mpc85xx: match with the pci bus address used by u-boot for p2020rdb-pca board
Date: Thu, 16 May 2013 15:15:44 +0800

In p2020rdb-pca board the bus address set in dtb don't match the one
used by u-boot. And this will trigger a kernel bug in 32bit kernel
and cause the pci device malfunction. For example, on a p2020rdb-pc
board the u-boot use the 0xa0000000 as both bus address and cpu
address for one pci controller and then assign bus address such
as 0xa00004000 to some pci device. But in the kernel, the dtb set
the bus address to 0xe0000000 and the cpu address to 0xa0000000.
The kernel assumes mistakenly the assigned bus address 0xa0004000
in pci device is correct and keep it unchanged. This will definitely
cause the pci device malfunction.

So set these bus address to match with the u-boot. This issue can't
be reproduced on 36bit kernel. But I still think it makes sense to
tweak the 36bit dtb to match with the u-boot.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>