Fix build error when unset DMA_ENGINE
CQID: WIND00424688

1/1 [
Author: Yunguo Wei
Email: yunguo.wei@windriver.com
Subject: Fix build error when unset DMA_ENGINE
Date: Wed, 17 Jul 2013 14:47:22 +0800

Commit b2f31e06f (async_tx: allow generic async_memcpy() not be effected
by channel switch) introduced this issue, and causes the following build
error if DMA_ENGINE is unset:
| crypto/built-in.o: In function `async_memcpy':
|
/buildarea2/fli/bitbake_build/tmp/work/intel_xeon_core_haswell-wrs-linux/linux-windriver-3.4-r0/linux/crypto/async_tx/async_memcpy.c:107:
undefined reference to `dma_find_channel'
| make[2]: *** [.tmp_vmlinux1] Error 1
| make[1]: *** [sub-make] Error 2
| make: *** [all] Error 2
| ERROR: oe_runmake failed
| WARNING:
/buildarea2/fli/bitbake_build/tmp/work/intel_xeon_core_haswell-wrs-linux/linux-windriver-3.4-r0/temp/do_compile/run.do_compile.14818:121
exit 1 from

Pick up the orignal implementation for async_memcpy() if DMA_ENGINE is
not set.

Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
]

Signed-off-by: Yue Tao <yue.tao@windriver.com>