fsl_qbman: fix a bman compile error
1/2 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: fsl_qbman: fix a bman compile error
Date: Wed, 2 Nov 2016 10:38:11 +0800

This is to fix the below error:

drivers/staging/fsl_qbman/bman_test_high.c: In function 'bman_test_high':
drivers/staging/fsl_qbman/bman_test_high.c:169:2:
error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
   struct bm_buffer tmp_buf;
   ^~~~~~
 cc1: all warnings being treated as errors

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

2/2 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: fsl_qbman: fix a qman compile error
Date: Wed, 2 Nov 2016 10:40:44 +0800

This is to fix the below error:
drivers/staging/fsl_qbman/qman_test_high.c: In function 'cb_dqrr':
include/linux/kern_levels.h:4:18: error:
 format '%llx' expects argument of type 'long long unsigned int', but argument 2 has type 'int' [-Werror=format=]

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>