vioapic cleanup
1/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: io_apic.h: delete reference to nonexistent file
Date: Mon, 14 Dec 2009 16:18:20 -0500

There is no such vbMgr file in the VBI reference implementation,
so delete the include of it.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

2/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: io_apic: delete duplicate definitions, use header file
Date: Mon, 14 Dec 2009 16:19:29 -0500

The definitions of these io_apic structs existed in two
places; the source file, and an unused header file.  The
definitions are the same, so delete the source file ones,
and use the header file ones.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

3/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: io_apic.h: don't include unneeded header files.
Date: Mon, 14 Dec 2009 18:12:03 -0500

There is nothing in this file that needs any other header
file, so don't include random junk.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

4/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: io_apic.h: fix compile failure
Date: Mon, 14 Dec 2009 18:13:04 -0500

This file has some extern decl that rely on "HY_CTX", but nothing in
the VBI reference defines the HY_CTX structure, so compilation will
fail, with an error message like:

error: expected ')' before '*' token

Further investigation reveals that all the extern lines are for
functions that are nowhere to be found, so it looks like they all can
be deleted.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

5/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: vbi: VIOAPIC_ID --> vioapic_id
Date: Mon, 14 Dec 2009 18:26:37 -0500

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

6/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: typedef VIOAPIC_VERSION --> union vioapic_version
Date: Tue, 15 Dec 2009 10:42:24 -0500

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

7/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: vpi: cleanup vioapic direction fields
Date: Tue, 15 Dec 2009 14:13:22 -0500

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

8/8 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: VIOAPIC_ENTRY --> struct vioapic_entry
Date: Tue, 15 Dec 2009 16:07:19 -0500

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>