fsl-t2xxx: misc compile error fix
1/2 [
Author: Wang Quanyang
Email: quanyang.wang@windriver.com
Subject: fsl_eth: replace __get_cpu_var with this_cpu_ptr in module qman-test
Date: Thu, 8 Oct 2015 04:16:15 -0400

According to the upstream commit 69111bac42f5
("powerpc: Replace __get_cpu_var uses"), use this_cpu_ptr
instead of __get_cpu_var, or else we will get a compile error
as below:

drivers/staging/fsl_qbman/qman_test_hotpotato.c:276:27: error: implicit declaration of function '__get_cpu_var' [-Werror=implicit-function-declaration]
  struct hp_cpu *hp_cpu = &__get_cpu_var(hp_cpus);
                           ^
drivers/staging/fsl_qbman/qman_test_hotpotato.c:276:26: error: lvalue required as unary '&' operand
  struct hp_cpu *hp_cpu = &__get_cpu_var(hp_cpus);

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/2 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: iommu/fsl: fix compile error
Date: Sun, 6 Apr 2014 23:58:32 +0530

This is a part of commit 93f1de0be908. Fix a compile error as below:

drivers/iommu/fsl_pamu.c:1382:3: error: too few arguments to function 'setup_one_pamu'
 setup_one_pamu(pamu_reg_base, ppaact_phys, spaact_phys,
 ^

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>