NXP: Integrate misc patches
1/5 [
Author: Andrei Varvara
Email: andrei.varvara@freescale.com
Subject: crypto: caam - Add define for NULL encryption
Date: Thu, 18 Jul 2013 12:25:04 +0300

This define is required for making descriptors
with NULL encryption.

drivers/staging/fsl_dpa_offload/dpa_ipsec.c:45:355: error: ‘OP_PCL_IPSEC_NULL_ENC’ undeclared here (not in a function)
  struct ipsec_alg_suite ipsec_algs[] = IPSEC_ALGS;
drivers/staging/fsl_dpa_offload/dpa_ipsec.c: In function ‘check_sa_params’:
drivers/staging/fsl_dpa_offload/dpa_ipsec.c:2991:17: warning: comparison between pointer and integer [enabled by default]
  if (cipher_alg != OP_PCL_IPSEC_NULL_ENC &&
                 ^

Dropped during: b7c81aa Merge remote-tracking branch 'linus/master' into merge

Signed-off-by: Andrei Varvara <andrei.varvara@freescale.com>
Signed-off-by: Emil Medve <Emilian.Medve@Freescale.com>
Change-Id: I61ef1a7d6bcf115f99f5160f76154c09e5f7f7da
Reviewed-on: http://git.am.freescale.net:8181/7991
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Emilian Medve <Emilian.Medve@freescale.com>
(cherry picked from commit c0ba7ddbedcbf435bc2d8c653a16286d077e9183)
[Original patch taken from QorIQ-SDK-V2.0-20160527-yocto]
Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

2/5 [
Author: Sandeep Malik
Email: Sandeep.Malik@freescale.com
Subject: dpa_ipsec: Patch to update the append_math_ldshift command.
Date: Sun, 16 Feb 2014 08:48:50 +0530

This patch updates the append_math_ldshift command to
append_math_shld.

Signed-off-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Change-Id: Icade31ac19f7ac8c370f9afdc14d542ac606feef
Reviewed-on: http://git.am.freescale.net:8181/8900
Reviewed-by: Horia Ioan Geanta Neag <horia.geanta@freescale.com>
Tested-by: Review Code-CDREVIEW <CDREVIEW@freescale.com>
Reviewed-by: Jose Rivera <German.Rivera@freescale.com>
(cherry picked from commit 5c46d5e00b92ec28b16dff1a5256de959d6b5eeb)
[Original patch taken from QorIQ-SDK-V2.0-20160527-yocto]
Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

3/5 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: fsl_dpa_offload: update some fields for ipsec
Date: Thu, 20 Oct 2016 10:21:02 +0800

upstream commit ("crypto: caam - handle core endianness != caam endianness")
uses an u32 "options" to combines some u8 and u16 fields for struct
ipsec_encap_pdb and ipsec_decap_pdb. So we need to update their callers.

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

4/5 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: fsl_dpa_offload: ipsec: rename addr_match() to dpa_addr_match()
Date: Wed, 19 Oct 2016 10:47:20 +0000

include/net/xfrm.h has a same name function.

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

5/5 [
Author: Yanjiang Jin
Email: yanjiang.jin@windriver.com
Subject: t4240: update t4240 relative DTS files
Date: Wed, 19 Oct 2016 10:46:16 +0800

Sync up with QorIQ-SDK-V2.0-20160527-yocto, up to the below kernel commit:

commit 85bf24e2e71ec1a2aa1142534828afb0d0cf62ee
Author: Ahmed Mansour <Ahmed.Mansour@nxp.com>
Date:   Mon May 9 16:28:51 2016 -0400

    fsl_qbman: Fix endianness for wq query

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
]

Signed-off-by: Yang Shi <yang.shi@windriver.com>