LTTNG2: kconfig fix for mips
NOCQID

When LTTNG2 was enabled in commit:
3243b5a3c39da919b5153dcb0b5251af793f2f12 LTTNG2 kernel config fragment

it revealed a Kconfig selection problem for mti-malta:

mti-malta32-be, preempt-rt:
drivers/staging/lttng2/lttng-events.c: In function
'_lttng_session_metadata_statedump':
drivers/staging/lttng2/lttng-events.c:988:2: error: implicit declaration
of function 'trace_clock_uuid' [-Werror=implicit-function-declaration]
drivers/staging/lttng2/lttng-events.c:1003:3: error: implicit
declaration of function 'trace_clock_freq'
[-Werror=implicit-function-declaration]

1/1 [
Author: Paul Barrette
Email: paul.barrette@windriver.com
Subject: LTTNG2: kconfig fix for mips
Date: Tue, 17 Jul 2012 17:13:39 -0400

Make sure HAVE_TRACE_CLOCK is selected for LTT, not LTTNG2.  LTTNG 2
does not support this CONFIG define, but LTT v 1.x does.

Signed-off-by: Paul Barrette <paul.barrette@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>