Freescale P4080 to sdk dpaa-1.0 - patches for preempt_rt
CQID: WIND00283218

1/2 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: net/dpa: replace local_irq* with local_irq*_nort
Date: Fri, 1 Jul 2011 17:21:25 +0800

In preempt_rt kernel, sometimes following call trace appears:
BUG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 0 0 in_atomic(): 0, irqs_disabled(): 1, pid: 924, name: modprobe
Call Trace:
[e9fa9ba0] [c0007c20] show_stack+0x44/0x160 (unreliable)
[e9fa9bd0] [c00350a8] __might_sleep+0xe4/0x108
[e9fa9be0] [c05f5dd4] rt_spin_lock+0x38/0xb4
[e9fa9bf0] [c010022c] _slab_irq_disable+0x50/0x8c
[e9fa9c20] [c01023c8] __kmalloc+0x80/0x268
[e9fa9c60] [c047464c] xx_Malloc+0x20/0x78
[e9fa9c70] [c040ce90] DtsecAddHashMacAddress+0x11c/0x2b4
[e9fa9ca0] [c041360c] FM_MAC_AddHashMacAddr+0x2c/0x140
[e9fa9cb0] [c05f6c00] set_multi+0x124/0x2b4
[e9fa9d00] [c04756a4] dpa_set_multicast_list+0x30/0x100
[e9fa9d20] [c05437d0] __dev_set_rx_mode+0x44/0xb4
[e9fa9d40] [c054cfd4] dev_mc_add+0x80/0xa0
[e9fa9d60] [f96962b4] igmp6_group_added+0xf4/0x1a8 [ipv6]
[e9fa9da0] [f96966f0] ipv6_dev_mc_inc+0x328/0x4cc [ipv6]
[e9fa9dd0] [f967aff0] ipv6_add_dev+0x22c/0x344 [ipv6]
[e9fa9df0] [f967ce4c] addrconf_notify+0x64/0x864 [ipv6]
[e9fa9e90] [c0547898] register_netdevice_notifier+0xb4/0x204
[e9fa9ec0] [f959233c] addrconf_init+0x80/0x160 [ipv6]
[e9fa9ee0] [f959217c] inet6_init+0x17c/0x294 [ipv6]
[e9fa9ef0] [c0001d48] do_one_initcall+0x3c/0x1e0
[e9fa9f20] [c0086970] sys_init_module+0xf8/0x21c
[e9fa9f40] [c00114b4] ret_from_syscall+0x0/0x4
Exception: c00 at 0xff63564
LR = 0x100031b8

the root cause is xx_Malloc is called with irq disabled. To fix it,
local_irq*_nort should replace local_irq*.

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

2/2 [
Author: Weiwei Wang
Email: weiwei.wang@windriver.com
Subject: fsl_qbman: modify PORTAL_IRQ_LOCK
Date: Tue, 12 Jul 2011 17:36:33 +0800

When use p4080ds-usdpaa.dtb in preempt_rt kernel, call trace is reported:
UG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 0, pid: 169, name: irq/122-QMan po
Call Trace:
[ebf51e90] [c0007cd0] show_stack+0x44/0x160 (unreliable)
[ebf51ec0] [c0035f6c] __might_sleep+0xe4/0x108
[ebf51ed0] [c05ffde4] rt_spin_lock+0x38/0xb4
[ebf51ee0] [c0524ce4] qman_irqsource_remove+0x114/0x150
[ebf51ef0] [c047ecc0] ingress_rx_default_dqrr+0x2d8/0x3a4
[ebf51f20] [c052ac54] portal_isr+0x244/0x2ac
[ebf51f50] [c00ad70c] irq_thread+0x16c/0x228
[ebf51fa0] [c006aee0] kthread+0x78/0x7c
[ebf51ff0] [c001127c] original_kernel_thread+0x4c/0x68
BUG: sleeping function called from invalid context at kernel/rtmutex.c:707
pcnt: 1 0 in_atomic(): 1, irqs_disabled(): 0, pid: 931, name: touch
Call Trace:
[e9889690] [c0007cd0] show_stack+0x44/0x160 (unreliable)
[e98896c0] [c0035f6c] __might_sleep+0xe4/0x108
[e98896d0] [c05ffde4] rt_spin_lock+0x38/0xb4
[e98896e0] [c0528860] qman_enqueue+0x20c/0x3f0
[e9889720] [c047fc94] dpa_tx+0x174/0x684
[e9889780] [c054fb78] dev_hard_start_xmit+0x1f8/0x510
[e98897d0] [c057f8e4] ip_finish_output+0x150/0x36c
[e9889800] [c057ff74] ip_local_out+0x34/0x48
[e9889810] [c0580208] ip_push_pending_frames+0x280/0x3b0
[e9889840] [c05a1f78] udp_push_pending_frames+0x108/0x494
[e9889870] [c05a4254] udp_sendmsg+0x3ec/0x6a8
[e9889930] [c05ab5bc] inet_sendmsg+0x38/0x7c
[e9889950] [c0539be4] sock_sendmsg+0xc0/0x160
[e9889a30] [c0539cb0] kernel_sendmsg+0x2c/0x44
[e9889a40] [c05de16c] xs_send_kvec+0x98/0xa8
[e9889a80] [c05de1fc] xs_sendpages+0x80/0x270
[e9889ab0] [c05de6d0] xs_udp_send_request+0x60/0x168
[e9889ad0] [c05dbf6c] xprt_transmit+0x70/0x2b0
[e9889af0] [c05d8fe4] call_transmit+0x1b8/0x290
[e9889b10] [c05e1410] __rpc_execute+0xf0/0x2fc
[e9889b60] [c05d9b08] rpc_run_task+0x44/0x90
[e9889b70] [c05d9c80] rpc_call_sync+0x50/0x80
[e9889ba0] [c02042c4] T.1016+0x40/0x7c
[e9889bb0] [c0205138] nfs_proc_getattr+0x54/0xa8
[e9889be0] [c01fafd0] __nfs_revalidate_inode+0xe4/0x204
[e9889ca0] [c01f4388] nfs_lookup_revalidate+0x28c/0x470
[e9889de0] [c011fb64] do_lookup+0x84/0x228
[e9889e10] [c0121944] do_last+0x360/0x74c
[e9889e40] [c0124584] do_filp_open+0x42c/0x628
[e9889f20] [c0112994] do_sys_open+0x64/0x198
[e9889f40] [c0011564] ret_from_syscall+0x0/0x4
Exception: c00 at 0x48017f0c
LR = 0x4800694c

To fix it, use raw_spin_lock* to define PORTAL_IRQ_LOCK

Signed-off-by: Weiwei Wang <weiwei.wang@windriver.com>
]

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>